### ISSUE TITLE
Request: fully differential gm amplifier (fd gm amp)

### ISSUE THREAD

**Issue by Arkh42** [circuitikz/circuitikz#104]
Currently, it exists an 'fd amp' symbol but no 'fd gm amp'. The latter would be as useful as the former when drawing circuits.
The fully differential gm amplifier would be like the single-ended gm amp regarding the general shape, but would have two outputs instead of one. An example of a figure using fully differential gm amp is given [here](https://www.researchgate.net/figure/Fully-differential-two-integrator-loop-g-0-C-filter_fig6_2982215).

**Comment by Rmano** [comment]
Fixed by #137. Please check the new version on http://circuitikz.github.io/circuitikz/
