### ISSUE TITLE
request : open push button and closed push button

### ISSUE THREAD

**Issue by dilawar** [circuitikz/circuitikz#128]
Hi, Great library. 

I guess currently there is only one `push button` style. I needed push button in both `open` and `closed` configuration. I was able to create them by changing `bipoles/pushbutton/height` parameter. 

I guess having every switch in `open` and `closed` styles would be great.

**Comment by Rmano** [comment]
Like this? 

![image](https://user-images.githubusercontent.com/6414907/53112181-fe2b3600-353e-11e9-87d9-1c1aa9ea91d4.png)

**Comment by Rmano** [comment]
Notice that I did the "stems" differently on purpose so that labels are naturally aligned on horizontal lines of switches. 
I'll merge and close, please re-open if needed.

**Comment by septatrix** [comment]
I like these however I think it would be nice to have a _closed_ variant of the _normally open push button_ and vice versa. The difference would be that for the closed normally open button the contact would be at the top of both terminal dots and for the opened normally closed button the gap would be below the terminal circles.

**Comment by Rmano** [comment]
Hmm, that's a good idea... 

Should the stem maintain the same length or should the upper point stay in the same position? Not sure...  

![image](https://user-images.githubusercontent.com/6414907/99910632-68ae6e80-2cef-11eb-9e9f-01ef0c072fb6.png)

**Comment by septatrix** [comment]
For me it would be most important that the text/labels remain at the same height. As their position depends on the anchors I think it would be best to make the stem longer and maintain the same anchor position. Decoupling the anchor from the stam seems like a bad idea (to me at least).

**Comment by Rmano** [comment]
It is possible to have both things (I can fake the size of the stem); I mean, it is possible to have the stem "going down" and maintain the label position. Or at least I think ;-)

**Comment by septatrix** [comment]
I just realized that these buttons are path styles and not nodes so I think they do not even have anchors accessible from the outside. So if they do not allow one to put something at the stem manually I think it would be nice to keep the stem size and move everything down.

Otherwise I would have imagined people attaching things (e.g. lines) to the steam which would either shift or get disconnected when they are moved down but as this does not even seem possible I am in favour of keeping the stem length the same.

**Comment by Rmano** [comment]
> I just realized that these buttons are path styles and not nodes so I think they do not even have anchors accessible from the outside. So if they do not allow one to put something at the stem manually I think it would be nice to keep the stem size and move everything down.

You **can** access anchors! Just name the path object: `to[R, name=myr]` and then you can refer to the anchors `(myr.north west)` etc etc. And the other way around, you can use any path style as a node: `node[resistorshape](){}`  (the shape name is listed in the manual).

**Comment by septatrix** [comment]
Oh that is great to know. Than I am _personally_ in favour of having the upper end of the stem stay in the same position.
