### ISSUE TITLE
Problem in processing `l=` (and similar) keys

### ISSUE THREAD

**Issue by Rmano** [circuitikz/circuitikz#143]
Consider the following piece of `tikz` code: 
```
\draw (0,0) node[node contents=$a=b$]{};
``` 
...it will fail, because the parser for the keys will get confused by the `=` symbol. So far, so good; you can adjust that "hiding" the `=` into braces: 
```
\draw (0,0) node[node contents={$a=b$}]{};
```
will work. Unfortunately, in `circuitikz`, `l={$R=R_1$}` will fail with error: 
```
Extra }, or forgotten $. 
Missing $ inserted.      
Missing } inserted.      
```
...and a fun rendering involving `\pgfextra`. Workarounds are possible, but they are ugly. 
```latex
Complete test code: 
\documentclass[border=10pt]{standalone}
%\usepackage[siunitx]{circuitikz}
\usepackage[siunitx]{circuitikzgit}
\begin{document}
\begin{circuitikz}[
    ]
    % you normally should hide "=" and "," and "[]" in keywords
    \draw (0,0) node[node contents={$a=b$}]{};
    % this fails (shouldn't)
    \draw (0,-2) to[R, l={$R=R_1$}] ++(3,0);
    % this works (but spacing is wrong)
    \draw (0,-4) to[R, l=$R{=}R_1$] ++(3,0);
    % this is correct (but it's a pain)
    \draw (0,-6) to[R, l=$R{{}={}}R_1$] ++(3,0);
\end{circuitikz}
\end{document}
```

and result (cropped): 

![image](https://user-images.githubusercontent.com/6414907/49815334-d3b54380-fd6b-11e8-990d-b0e84da34466.png)

**Comment by sistlind** [comment]
This is an old bug :/ IIRC this is not solvable whitin circuitikz and it should be already documented somewhere in the manual.

**Comment by Rmano** [comment]
Best workaround is `\newcommand{\eq}{=}` and use `\eq` instead of `=` when needed. Will try to add it to the manual...

**Comment by sistlind** [comment]
good idea, but we should maybe use a more unique cmd like \ctikzeq

Am Sa., 15. Dez. 2018, 09:54 hat Romano Giannetti <notifications@github.com>
geschrieben:

**Comment by Rmano** [comment]
> good idea, but we should maybe use a more unique cmd like \ctikzeq

Well, I was thinking of giving the hint in the manual and let the user choose it's "equivalent" ... I would not use `\ctikzeq` really, `\eq` is easier and more intuitive, but I agree that we can't use it in the package.

**Comment by sistlind** [comment]
I am just a  bit afraid that it could collide with other packages using
this macro.Just because it is so intuitive and good abbreviation for equal
as well as equation.

Am Sa., 15. Dez. 2018, 10:36 hat Romano Giannetti <notifications@github.com>
geschrieben:

**Comment by Rmano** [comment]
> I am just a bit afraid that it could collide with other packages using this macro.Just because it is so intuitive and good abbreviation for equal as well as equation.

Yes, you are right. I think it's better not to add anything to `circuitikz`, and letting the user decide. I'll prepare a patch for the user manual.
