### ISSUE TITLE
Files cleanup

### ISSUE THREAD

**Issue by Rmano** [circuitikz/circuitikz#149]
Hi, especially @mredaelli  @der-stefan @sistlind 

I am thinking about making a kind of cleanup of the files, in order to try to indent them better and make lines short. Moreover, the indentation is quite mixed (spaces, hard tabs, 8 spaces, 4 spaces...), and there are quite a lot of trailing spaces and tabs around. 

Would you object going spaces only, 4 chars indent, no trailing spaces, and removing commented out commands?

**Comment by sistlind** [comment]
Hi Rmano,
sounds good, except the commented commands. They should removed by care,  maybe there are helpful.
