### ISSUE TITLE
DIP Chip pins seem misaligned

### ISSUE THREAD

**Issue by zhiayang** [circuitikz/circuitikz#205]
So, with the following code:
```latex
\documentclass{article}
\usepackage{tikz}
\usepackage{circuitikz}
\begin{document}
	\begin{circuitikz}
		\draw (2, 0) node[dipchip, num pins=10](A){A};
		\draw (7, 0) node[dipchip, num pins=8](B){B};

		\draw [red] (A.pin 6)  -- (B.pin 2){};
		\draw [blue] (A.pin 7)  -- (B.pin 2){};
		\draw [green] (A.pin 8)  -- (B.pin 2){};
		\draw [pink] (A.pin 9)  -- (B.pin 2){};
		\draw [purple] (A.pin 10) -- (B.pin 2){};
	\end{circuitikz}
\end{document}
```

I get this output:

![Capture](https://user-images.githubusercontent.com/500236/58105732-8e017e80-7c19-11e9-865e-f5ab3b0ca31b.PNG)

Not entirely sure what's going on here. It happens if B has 8 pins or 6 pins, (the offset is different), but not when it has 4. I messed about and set it to 14, and got this:
![Capture2](https://user-images.githubusercontent.com/500236/58106052-0c5e2080-7c1a-11e9-8626-decf6d9ad86f.PNG)

**Comment by Rmano** [comment]
Yes, I can confirm a problem here. Thanks, I'll look into it.

**Comment by Rmano** [comment]
So, the problem is that there is a kind of "leakage" in the parametric anchor definitions; it seems that the last chip defined overrides the previous anchors positions. This is *not* happening in the multi-inputs logic gates, from where I copied the idea...  If anybody can help, I'll be grateful. Digging in, 

```
\def\showcoord(#1){node[circle, red, draw, inner sep=1pt,pin={[red, overlay, inner sep=0.5pt, font=\tiny, pin distance=0.1cm, pin edge={red, overlay,}]45:#1}](#1){}}
\def\showcoordb(#1){node[circle, blue, draw, inner sep=1pt,pin={[blue, overlay, inner sep=0.5pt, font=\tiny, pin distance=0.1cm, pin edge={blue, overlay,}]-45:#1}](#1){}}
\begin{circuitikz}
		\draw (2, 0) node[dipchip, num pins=10](A){A};
                \foreach \i in {1,...,10} \path (A.pin \i)  \showcoord(\i);
        
		\draw (7, 0) node[dipchip, num pins=14](B){B};
                \foreach \i in {1,...,10} \path (A.pin \i)  \showcoordb(\i);
              
                \draw (2, 4) node[american nor port, number inputs=5](C){};
                \foreach \i in {1,...,5} \path (C.in \i)  \showcoord(\i);

                \draw (7, 4) node[american nor port, number inputs=3](D){};
                \foreach \i in {1,...,5} \path (C.in \i)  \showcoordb(\i);
	\end{circuitikz}
```

that results into 

![image](https://user-images.githubusercontent.com/6414907/58112297-84652000-7bf3-11e9-81a9-3dc0f5bdacbf.png)

**Comment by zhiayang** [comment]
Ah, I was hoping this wouldn't be a difficult thing to fix... Anyway since I have a report to write I'm just manually adjusting the anchor positions till they look right, which, as far as workarounds go, isn't the worst thing ever.

I have 0 clue wrt. the deep latex stuff, so I can't help there.

**Comment by Rmano** [comment]
As a workaround you can save the anchor position before defining the new chip: 

```
\begin{circuitikz}
		\draw (2, 0) node[dipchip, num pins=10](A){A};
                \foreach \i in {1,...,10} \path(A.pin \i) coordinate(mypin-\i);

		\draw (7, 0) node[dipchip, num pins=8](B){B};

		\draw [red] (mypin-6)  -- (B.pin 2){};
		\draw [blue] (mypin-7)  -- (B.pin 2){};
		\draw [green] (mypin-8)  -- (B.pin 2){};
		\draw [pink] (mypin-9)  -- (B.pin 2){};
		\draw [purple] (mypin-10) -- (B.pin 2){};
	\end{circuitikz}
```

**Comment by zhiayang** [comment]
oh, that’s a good idea! I’m already using a macro to draw the chips, so I can just tack this on the end.

**Comment by Rmano** [comment]
...I found the problem. I am on my way trying to solve it...

**Comment by Rmano** [comment]
I published a PR (#206) that should fix it. I attach here a `circuitikzgit.sty` (zipped), if you can check that it solves the problem I'll appreciate it. Thanks for reporting the bug, anyway!

[circuitikzgit.zip](https://github.com/circuitikz/circuitikz/files/3206905/circuitikzgit.zip)

**Comment by Rmano** [comment]
To check, put the `circuitikzgit.sty` file in the same dir as the LaTeX file, and then change the file to use it: 

```
\documentclass{article}
\usepackage{tikz}
\usepackage[RPvoltages]{circuitikzgit}
\begin{document}
	\begin{circuitikz}
		\draw (2, 0) node[dipchip, num pins=10](A){A};
		\draw (7, 0) node[dipchip, num pins=8](B){B};

		\draw [red] (A.pin 6)  -- (B.pin 2){};
		\draw [blue] (A.pin 7)  -- (B.pin 2){};
		\draw [green] (A.pin 8)  -- (B.pin 2){};
		\draw [pink] (A.pin 9)  -- (B.pin 2){};
		\draw [purple] (A.pin 10) -- (B.pin 2){};
	\end{circuitikz}
\end{document}
```

I have: 

![image](https://user-images.githubusercontent.com/6414907/58167881-4288b800-7c8d-11e9-9b3a-87bd5c000e56.png)

which seems correct.

**Comment by zhiayang** [comment]
Woah, that's fast. It does indeed solve the problem, thanks so much!
