### ISSUE TITLE
Need to do a 0.9.2 shortly

### ISSUE THREAD

**Issue by Rmano** [circuitikz/circuitikz#229]
Ok, I realized that the ConTeXt side has been in bad shape since 0.9.0. Unfortunately, I do not know it and it seems that no one is checking it...  I need to: 

- [x] add manually the new includes in `t-circuitikz.tex` (I thought it was automatic!) 
- [x] remove the mention of old versions in README (it works only in LaTeX --- unless someone can help me generate the files, they're not it). 

Too late to target 0.9.1, it will need a 0.9.2 shortly on.

**Comment by sistlind** [comment]
the 'git'-versions are also generated for context at the gh-pages branch,
but to be honest, I never checked them.

If a filename/the defines have changed, it has to be adjusted manually.
Maybe the same is true if the paket option changes, but here I am not sure.

Romano Giannetti <notifications@github.com> schrieb am Mo., 17. Juni 2019,
20:15:

**Comment by Rmano** [comment]
Steps for 0.9.2
- [ ] freeze the repo (just a bit) 

When ready, prepare a PR that: 

- [ ] set version number and date in circtuitiks.sty, t-circuitikz.sty, manual and changelog
- [ ] commit everything
- [ ] run "make ctan" this will produce a zipfile. check the contents of this file (especially the version & date of docs & package)
- [ ] go to page https://ctan.org/pkg/circuitikz
- [ ] click on upload(at the top)
- [ ] upload the zipfile and fill the missing fields ( I copied the changelog to the announcement field)

Now the repository is freezed; I'll wait for:

- [ ] Confirmation of the correct upload 
- [ ] If the package is ok it will take a few days to spawn over all servers

And after that:

- [ ] Push your commit to github
- [ ] Add a github release with same infos & zip file.
- [ ] Add at the the link to the circuitikz-git file of the new release to the circuitikz github pages site (edit https://github.com/circuitikz/circuitikz/blob/gh-pages/index.html manually )
![image](https://user-images.githubusercontent.com/6414907/59628234-6f22d900-9140-11e9-85e4-9f3b5b66f10f.png)

- [ ] reinsert the git headline in the changelog file.

...and now development will continue.

**Comment by Rmano** [comment]
> If a filename/the defines have changed, it has to be adjusted manually. Maybe the same is true if the paket option changes, but here I am not sure.

...we need someone using it in ConTeXt giving feedback...

**Comment by Rmano** [comment]
Started...

**Comment by Rmano** [comment]
Trying to upload, I have an internal server error on CTAN. I reported the problem, will try again later.

**Comment by Rmano** [comment]
> Trying to upload, I have an internal server error on CTAN. I reported the problem, will try again later.

Still kaputt...

**Comment by Rmano** [comment]
Ok, ctan has come back to life. Uploaded!

**Comment by jesseopdenbrouw** [comment]
I am trying to compile this short TeX file with ConText, It produces the resistor, I will try more.
