### ISSUE TITLE
Electronic tubes not working in ConTeXt

### ISSUE THREAD

**Issue by jesseopdenbrouw** [circuitikz/circuitikz#234]
Rendering the electronics tubes (except magentron) fails when using ConTeXt. This is due to ConTeXt not defining `\@tempcnta`, `\@tempdimc` and friends. I am working on a fix.

**Comment by Rmano** [comment]
Yep, nicely spotted. I have defined in `pgfcircmultipoles.tex` this:
```latex
% counters for pin accounting...
\newcount\pgf@circ@count@c
\newcount\pgf@circ@count@b
```
to add to the `\pgf@counta` used somewhere in `tikz`. Maybe we can add them to the start of `pgfcirc.defines.tex` where the various temporary lengths used in shapes are defined.

**Comment by Rmano** [comment]
Well, worth fixing, but I really do not know how many users using ConTeXt are here, so no need to hurry...

**Comment by jesseopdenbrouw** [comment]
Well, as a quick workaround, include the following lines:

```
%% Insert these four lines to prevent TikZ from failing to compile
\unprotect
\def\XC@tgt@mod#1{#1}
\def\XC@sdef#1#2{\edef#1{#2}}
\protect

% Define use counter and dimension
\catcode`\@11\relax
\newcount\@tempcnta
\newdimen\@tempdimc
\catcode`\@12\relax

```

**Comment by jesseopdenbrouw** [comment]
> Well, worth fixing, but I really do not know how many users using circuitikz in ConTeXt are here, so no need to hurry...

Well, you asked for ConTeXt testers ;-)

**Comment by jesseopdenbrouw** [comment]
> Yep, nicely spotted. I have defined in `pgfcircmultipoles.tex` this:
> 
> ```
> % counters for pin accounting...
> \newcount\pgf@circ@count@c
> \newcount\pgf@circ@count@b
> ```
> 
> to add to the `\pgf@counta` used somewhere in `tikz`. Maybe we can add them to the start of `pgfcirc.defines.tex` where the various temporary lengths used in shapes are defined.

Also note that TikZ defines `\c@pgf@counta` {b,c,d}. So I think I'll use those.

**Comment by Rmano** [comment]
> Also note that TikZ defines `\c@pgf@counta` {b,c,d}. So I think I'll use those.

Ah --- nice find. Yes, that would be great.

**Comment by Rmano** [comment]
Using `\c@pgf@counta` created bug #243 --- please look at it. I am not sure how it could happen, but it did...
