### ISSUE TITLE
PMOS arrow symbol 

### ISSUE THREAD

**Issue by Arkh42** [circuitikz/circuitikz#238]
Dear developers,

Currently, the __arrowmos__ option draws correctly the arrow symbols depending on the type of MOS transistor. However, the full circle is still drawn on the PMOS symbol, while it shouldn't be.
I have read many articles and books in microelectronics (this is my field of work) and I've never see that. Either there is an arrow or a circle, as shown [here](https://en.wikipedia.org/wiki/MOSFET#Circuit_symbols) and [there](https://i.stack.imgur.com/1gpMy.jpg).
Could you please do something about it?
If it can be of any help, I found [this](https://tex.stackexchange.com/questions/237682/tikz-change-symbol-of-pmos).

Thank you very much for your great job!

**Comment by Rmano** [comment]
I will propose a PR with the ability to do this: 

![image](https://user-images.githubusercontent.com/6414907/60453060-57634e80-9c30-11e9-9397-2d06f09a0e9d.png)

**Comment by Rmano** [comment]
Although I agree that with `arrowmos` the default should be `nocircle`, I do not like backward-incompatible changes a lot, so I think I will not touch the default. Opinions welcome.

**Comment by Arkh42** [comment]
I understand the problem of backward incompatibility and your desire to not change the default.
Probably not a big deal if there is a note in the manual.

Is the option "emptycircle, noarrows" available as well?

**Comment by Rmano** [comment]
> Is the option "emptycircle, noarrows" available as well?

Yes: 
```latex
\ctikzset{tripoles/pmos style/emptycircle, tripoles/mos style/no arrows}
\draw (0,-2) node[info]{emptycircle} node[pmos]{} (2,-2) node[nmos]{}
```

![image](https://user-images.githubusercontent.com/6414907/60506266-cb9c0180-9cc5-11e9-894a-abc7484e210f.png)

I added things to the manual; please check it out. Suggestions and changes are welcome!
