### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by der-stefan** [circuitikz/circuitikz#24]
The documentation gets more and more confusing because of the sorting by oneports, twoports etc. (or "poles"). I think the user is more interested in the function of a device and if it behaves as a twoport (syntax `(0,0) to[device] (2,0);`) or as a node (syntax `(0,0) node[device] {};`). Futhermore, he wants to know how he addresses the ports (anchor names).

Any ideas?

**Comment by der-stefan** [comment]
A first step is done with cb46e0a. More to follow.

**Comment by Rmano** [comment]
I will start to try to reorganize it, putting together the element, their usage, and the anchors. I will start with the new features and then propagate it if accepted...

**Comment by Rmano** [comment]
#169 should let us close this issue. There are still things to do, but I think it's quite a step in the right direction.
