### ISSUE TITLE
Volage direction arrow not inverted with 'invert'

### ISSUE THREAD

**Issue by agisen** [circuitikz/circuitikz#248]
When inverting an european voltage source, the voltage arrow is not inverted as well (as I would have expected):
```latex
\begin{circuitikz}[european voltages, voltage dir=EF]
	\draw (0,0) to [american voltage source, v=~] (2,0);
\end{circuitikz}
\begin{circuitikz}[european voltages, voltage dir=EF]
	\draw (0,0) to [american voltage source, v=~, invert] (2,0);
\end{circuitikz}
```
(using american voltage sources to clarify the inverting)

I know that I can change the arrow direction using <, but is this behaviour intended?

**Comment by Rmano** [comment]
Yes, it's intended. Or at least expected: 

![image](https://user-images.githubusercontent.com/6414907/60656209-607e3680-9e4f-11e9-97b4-99b1a0d72645.png)

(Pag. 95 in the manual).

**Comment by agisen** [comment]
Ok, thanks!
