### ISSUE TITLE
Option "noconnectors"

### ISSUE THREAD

**Issue by der-stefan** [circuitikz/circuitikz#25]
Some symbols have very long connectors (worst cases are the antenna symbols!). Normally the user wants to draw his own lines, so the connectors the ports/anchors should be either very short or non-existent. We could add an option "noconnectors" to remove all long lines. For default nothing should change in order to keep backward compatibility for users.

![rxant](https://cloud.githubusercontent.com/assets/3618939/13914860/7b942250-ef51-11e5-8d57-71148f541a20.png)

**Comment by Rmano** [comment]
I think this is related basically to antennas so it is quite easier to define no connector equivalents...

**Comment by Rmano** [comment]
I will commit these antennas after the big manual merge...

![image](https://user-images.githubusercontent.com/6414907/54769356-50747b00-4c01-11e9-84d9-22b02e501262.png)

I hope they will suffice.

**Comment by Rmano** [comment]
Closed by #170
