### ISSUE TITLE
Drawing Multiplexer in Circuitikz 

### ISSUE THREAD

**Issue by mickey4u** [circuitikz/circuitikz#253]
I just want to find out how do you draw multiplexer using circuitikz.

**Comment by Rmano** [comment]
It depends on what symbol you want for a multiplexer. I would use a chip as explained in the manual for the generic block, or a multi way rotative switch. What have you tried?

**Comment by mickey4u** [comment]
@Rmano I saw post where someone said using the circuits.logic.IEC library offers an and gate that gives you as many input anchors as required. I just want something like the image below.
![mux](https://user-images.githubusercontent.com/15174041/61188209-adde7d00-a673-11e9-9eb1-93fa5ea0d5be.png)

**Comment by Rmano** [comment]
There is no such a symbol in circuitikz, but I think it's quite easy to do by hand, using the trapezoid shape of tikz. By the way, multiple and ports are available in circuitikz too (look at the manual of new versions), but with a quite different shape.

**Comment by mickey4u** [comment]
@Rmano I will just use this one for now [https://tex.stackexchange.com/a/180351](url).

**Comment by Rmano** [comment]
Closing, please reopen if you need it.
