### ISSUE TITLE
Release a 0.9.4 with styling

### ISSUE THREAD

**Issue by Rmano** [circuitikz/circuitikz#268]
Before 0.9.4
- [x] fix #262 
- [x] fix #272

Steps for 0.9.4
- [x] freeze the repo (just a bit) 

When ready, prepare a PR in my fork  that: 

- [x] set version number and date in circtuitiks.sty, t-circuitikz.sty, and changelog
- [x] commit everything and publish the PR

Once merged, in the main repo:

- [x] run "make ctan" this will produce a zipfile. check the contents of this file (especially the version & date of docs & package)
- [x] go to page https://ctan.org/pkg/circuitikz
- [x] click on upload(at the top)
- [x] upload the zipfile and fill the missing fields ( I copied the changelog to the announcement field)

Now the repository is freezed; I'll wait for:

- [x] Confirmation of the correct upload 
- [x] If the package is ok it will take a few days to spawn over all servers

And after that:

- [x] Push your commits in the main repor to github
- [x] Add a github release with same infos & zip file & styles zip file
- [x] Add at the the link to the circuitikz-git file of the new release to the circuitikz github pages site (edit https://github.com/circuitikz/circuitikz/blob/gh-pages/index.html manually; remember to add the styles `.zip` if creating a checkpoint for this release)

![image](https://user-images.githubusercontent.com/6414907/59628234-6f22d900-9140-11e9-85e4-9f3b5b66f10f.png)

Another trick: to transform the link to a stable link, press "y" in the page showing it...  see https://help.github.com/en/articles/getting-permanent-links-to-files

- [x] reinsert the git headline in the changelog file.

...and now development will continue.

**Comment by Rmano** [comment]
Hmmm... changes are quite big, and styling is a clearly user-visible one... @mredaelli @asinghvi17 @jboalml @jesseopdenbrouw @sistlind @der-stefan : should we jump to `1.0.0`?

**Comment by jesseopdenbrouw** [comment]
I agree with @asinghvi17 -- first bug hunting, that bump to 1.0.0.

**Comment by Rmano** [comment]
Ok --- so that's it. Thanks for your opinion!
