### ISSUE TITLE
Ground with 3 lines

### ISSUE THREAD

**Issue by matthuszagh** [circuitikz/circuitikz#278]
In manual 0.9.0, I notice that ground symbols have 3 lines:

![3-lines](https://user-images.githubusercontent.com/7377393/64367629-60282600-cfcd-11e9-8957-2744ae5d63e5.jpg)

However, when I use ground symbols I get 4:

![4-lines](https://user-images.githubusercontent.com/7377393/64367649-6dddab80-cfcd-11e9-8c6c-6fe3265403d8.jpg)

I like the 3-line style better. How can I use this?

**Comment by Rmano** [comment]
Can you please post the code you are using?

**Comment by Rmano** [comment]
If you look at #279 , I have a ground with three line. That seems some local change... puzzled.

**Comment by matthuszagh** [comment]
Resolved by upgrading to v0.9.4. See #279.
