### ISSUE TITLE
Feature request: center tap transformer

### ISSUE THREAD

**Issue by asinghvi17** [circuitikz/circuitikz#281]
It would be nice to have a center tap transformer (with an arrow pointing to the center, and a dedicated node).

For now, this can be approximated by drawing a path ending in an arrow close enough to the right inductor's midpoint.

**Comment by Rmano** [comment]
Shouldn't be too difficult; the only problem I see is to precisely touch the coil, especially if the number of loops is not standard...

**Comment by Rmano** [comment]
I am wondering: would an access to the internal "L" shapes suffice? Then you can really do the contact wherever you wont, like 

     ($(traf-l1.north west)!0.3!(traf-l1.north east)$)

?

**Comment by Rmano** [comment]
Like: 

![image](https://user-images.githubusercontent.com/6414907/65528693-24f68400-def5-11e9-84e0-7d28c09f958a.png)

**Comment by asinghvi17** [comment]
That would be perfect!

**Comment by Rmano** [comment]
> That would be perfect!

Ok, so it's almost here. As soon as I find the time, I'll publish a PR!
