### ISSUE TITLE
Enable segment letters for the seven segment display

### ISSUE THREAD

**Issue by mickey4u** [circuitikz/circuitikz#293]
How do I enable segment letters for the seven segment display?

**Comment by Rmano** [comment]
I am really sorry, I do not understand your question. Please:

- add a sample code you tried 
- with the result you have obtained
- and explain what you want to obtain instead.

**Comment by mickey4u** [comment]
As shown in the image, I want to add the segment letters to the display.

![Screenshot from 2019-10-06 19-03-47](https://user-images.githubusercontent.com/15174041/66273458-1cdf0280-e86c-11e9-874f-0c3d0cf979de.png)

**Comment by Rmano** [comment]
So, I really do not think this is an issue; it's just a "how do I do *x*" question...  I think that a forum like https://tex.stackexchange.com/questions is more appropriate for this kind of questions; issues here are for bugs or feature requests.  

Said that, seven-segments have the `a`...`g` anchors, in the center of the corresponding segment (see manual section 3.25.1) . So you can do something like this (shown for a and b, you can fill in the rest):

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}
    \node [seven segment bits=0000000 dot empty box off] (D) {}; 
    \node [above, font=\tiny]  at (D.a) {a};
    \node [right, font=\tiny]  at (D.b) {b};
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/66274134-a0ecb680-e87b-11e9-8965-2058f7fd1d49.png)

If I misunderstood your question, please feel free to re-open the issue.

**Comment by Rmano** [comment]
If I misunderstood your question, please feel free to re-open the issue.
