### ISSUE TITLE
Add current transformer

### ISSUE THREAD

**Issue by alexpacini** [circuitikz/circuitikz#297]
I noticed that the symbol for the current transformer is missing.
The symbol is the same as the traditional transformer but has only an half circle on one side to show that it is only a single turn.

I wonder if it is worth adding the symbol. I contributed in the past and it should be not too complicated to make it from the transformer (just leave half a turn), but unfortunately I don't have lot of time available at the moment. Therefore I am not sure if I can make it in a reasonable time (and do it properly with docs, etc.).
If anyone is willing to do that I will appreciate and will say thanks :)

**Comment by Rmano** [comment]
Could you please add an example? I am not sure to understand the description...

**Comment by alexpacini** [comment]
Sure. I apologise for the low quality...
The style should be the same as the transformers, but with a single turn.

![current_trafo](https://user-images.githubusercontent.com/2548281/66779390-f2bdbe00-eec5-11e9-9149-4167836dd272.jpg)

**Comment by Rmano** [comment]
I am thinking to allow styling of the inductors, so that you can have diagrams like these: 

![image](https://user-images.githubusercontent.com/6414907/66827757-adde6980-ef4f-11e9-9b65-e5ed8cf4c632.png)

**Comment by alexpacini** [comment]
That is very nice.
Consider though that the current sensing side (the one with a single loop) is often placed inline with the line, therefore without the two "knees" (similarly to my picture).

**Comment by Rmano** [comment]
This could be achieved with the `quadpoles style=inline` (which I prefer anyway): 

![image](https://user-images.githubusercontent.com/6414907/66847495-bf396d00-ef73-11e9-97cd-8c59005b6b4a.png)

**Comment by Rmano** [comment]
Hmm... there is a bug in the core of the `inline` `transformer core` --- will check.

**Comment by Rmano** [comment]
> Hmm... there is a bug in the core of the `inline` `transformer core` --- will check.

Will be fixed by #298

**Comment by alexpacini** [comment]
Perfect!

**Comment by Rmano** [comment]
> Do you also need to set the coil width?

Yes, because the number of coils and the width are independent. But you can easily define a style: 

![image](https://user-images.githubusercontent.com/6414907/66899721-b8563d00-effb-11e9-8721-79ca8be37440.png)
