### ISSUE TITLE
feature proposal - RC Snubber for switch/transistor component

### ISSUE THREAD

**Issue by EdAlvesSilva** [circuitikz/circuitikz#323]
Hello there,

I think it would be nice to have a RC snubber option for transistors/switches in general, in a similiar way that there is for the bodydiode option. 

This is how it looked when hardcoding it to my project, and the code I used to make it: 

With a bodydiode:
![image](https://user-images.githubusercontent.com/30510517/69291760-f4745300-0be2-11ea-8003-7c5609fc373d.png)

`
++(0,-1) node [npn,scale=1,bodydiode,name=npn1] {}
(npn1.E)++(0,0.31) -- ++(0.5,0) to[R]  ++(0,0.5) to[C] ($(npn1.C)+(0.5,-0.31)$) -- ++(-0.31,0)
`

Without a bodydiode:
![image](https://user-images.githubusercontent.com/30510517/69292381-c3951d80-0be4-11ea-9a4e-6579584c617a.png)

`++(0,-1) node [npn,scale=1,name=npn1] {}
(npn1.E)++(0,0.31) -- ++(0.3,0) to[R]  ++(0,0.5) to[C] ($(npn1.C)+(0.3,-0.31)$) -- ++(-0.31,0)
`
Thanks

**Comment by Rmano** [comment]
To be honest, I am not so sure about it. It could be easily done with a macro (passing the reference of a transistor node) and the new `class` scaling of components; adding it as a general option will add complexity for a not-so-common case... especially if I want to fix the standard label positioning of transistors.  

I'll see if someone else comment about this, marking "enhancement" and "discussion"  for now.

**Comment by Rmano** [comment]
I'll add a couple of anchors to simplify the task. Stay tuned...

**Comment by Rmano** [comment]
Like this: 

![image](https://user-images.githubusercontent.com/6414907/69857326-0ebbca00-1290-11ea-95ed-4089ef9368d0.png)

what do you think?

**Comment by EdAlvesSilva** [comment]
This looks great!
