### ISSUE TITLE
New shapes for american OR ports

### ISSUE THREAD

**Issue by Rmano** [circuitikz/circuitikz#340]
Hi all, (especially @asinghvi17 @mredaelli @der-stefan @sistlind @matthuszagh)  --- several people told me that the shape of american-or logic gates and similar are strange because they are supposed to be pointy. So I have modified the shapes, see the diagram below, with a new choice flag. 

Now, I happen to like more the new shapes --- and now I have a doubt. Should I make them the default (could be a nice visual marker for version 1.0) or not? I can always put them in my style file, granted, but... 

Please comment!

![image](https://user-images.githubusercontent.com/6414907/71414595-f608bf00-2657-11ea-8e94-33ffdeb76b9b.png)

**Comment by matthuszagh** [comment]
My vote would be to make the new (pointy) ones default since that’s what I’m more familiar with, but it’s not a strong opinion. Thanks for all the hard work you’ve put into this!

**Comment by JoseDanielMunozFrias** [comment]
I also vote to make the pointy gates the default.

**Comment by Rmano** [comment]
I have merged a version with the pointy gates as default.

**Comment by jason-s** [comment]
>several people told me that the shape of american-or logic gates and similar are strange because they are supposed to be pointy.

YUCK! Where did you get this information? This is not the case. If you look at any of the major logic gate manufacturers you will see standard symbols which circuitikz is now moving away from rather that toward.

**Comment by Rmano** [comment]
Well. You can go back to the old ones which just one switch in your style. I prefer the new ones because they were the ones I was used to when studying. So nothing bad happened; just more options.

**Comment by Rmano** [comment]
Hmmm. I see them quite similar (maybe the ones in `circuitikz` are shorter - they mostly miss the straight part.

**Comment by jason-s** [comment]
I'm filing a new issue...
