### ISSUE TITLE
Reed switch

### ISSUE THREAD

**Issue by fiveop** [circuitikz/circuitikz#352]
I would be grateful if someone added a symbol for a reed switch (https://en.wikipedia.org/wiki/Reed_switch) to the library.

**Comment by Rmano** [comment]
![image](https://user-images.githubusercontent.com/6414907/72897452-48560200-3d22-11ea-85bb-95d129c7f2ca.png)

Is there some better source for the symbols? Seems asymmetric here, should it be so?

**Comment by Rmano** [comment]
Meanwhile, you can simulate it with 

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\usetikzlibrary{fit, shapes.misc}
\begin{document}
\begin{circuitikz}[
    ]
    \draw (0,0) to[nos, name=mynos] ++(3,0);
    \node [rounded rectangle, draw, fit=(mynos), inner xsep=10pt] at (mynos.center) {};
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/72913054-dd65f480-3d3c-11ea-9329-48848f9a65f3.png)

**Comment by fiveop** [comment]
I am a layman when it comes to electronics. I just found the symbol on Wikipedia and think it makes my circuit drawing more precise. A google image search shows many variations, some symmetric some not.

Thank you for the example on how to do it by hand. With a little fiddling with the inner sep values and rotation, I got it to work in my drawing.

**Comment by Rmano** [comment]
Happy to hear it helped. I have no time to code a proper component now, but I'll leave this issue open because this could be a very nice first-time contribution to the project!

**Comment by Rmano** [comment]
Couldn't release 1.0 with an outstanding request... See PR #359
