### ISSUE TITLE
fd amp output line width customization

### ISSUE THREAD

**Issue by matthuszagh** [circuitikz/circuitikz#356]
Is it possible to customize the `fd op amp` node so that the output pin lines are a normal line thickness? They come thick by default. I didn't see anything about this in the manual. I guess I could achieve the same effect with a mux, but that feels unnecessary since that's the only thing I want to change from the default.

**Comment by Rmano** [comment]
It shouldn't do that. I'll check as soon as I can...

**Comment by Rmano** [comment]
So yes, the problem is quite evident: 

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}[
    circuitikz/amplifiers/fill=yellow]
    \draw (0,0) node [fd op amp](A){} (A.out +) -- ++(1,0);
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/73523607-8aaacd80-440b-11ea-9371-4a943d0f5f67.png)

**Comment by Rmano** [comment]
After the patch:

![image](https://user-images.githubusercontent.com/6414907/73523971-5be12700-440c-11ea-8a23-12edcbf709bc.png)

Notice that some PDF viewer (notably, `okular`) can get the antialiasing wrong and show the amplifiers terminal "blurred" at some magnification.... 

`okular` at 400%: 

![image](https://user-images.githubusercontent.com/6414907/73524133-c2fedb80-440c-11ea-8d2d-c9d60d643483.png)

`okular` at 800% (same file): 

![image](https://user-images.githubusercontent.com/6414907/73524158-d6aa4200-440c-11ea-9b1f-97dcfc8ad780.png)

**Comment by matthuszagh** [comment]
thanks for the quick fix! looks great
