### ISSUE TITLE
Releasing v1.0

### ISSUE THREAD

**Issue by Rmano** [circuitikz/circuitikz#361]
And finally... version 1.0 (2020-02-04) of `circuitikz` will be released.

The main updates since version 0.8.3, which was the last release before Romano started co-maintaining the project, are the following --- part coded by Romano, part by several collaborators around the internet:

- The manual has been reorganized and extended, with the addition of a tutorial part; tens of examples have been added all over the map.
 - Around 74 new shapes where added. Notably, now there are chips, mux-demuxes, multi-terminal transistors, several types of switches, flip-flops, vacuum tubes, 7-segment displays, more amplifiers, and so on.
 - Several existing shapes have been enhanced; for example, logic gates have a variable number of inputs, transistors are more configurable, resistors can be shaped more, and more.
 - You can style your circuit, changing relative sizes, default thickness and fill color, and more details of how you like your circuit to look; the same you can do with labels (voltages, currents, names of components and so on).
 - A lot of bugs have been squashed; especially the (very complex) voltage direction conundrum has been clarified and you can choose your preferred style here too.

A detailed list of changes can be seen in the manual. 

When ready, prepare a PR in my fork  that: 

- [x] set version number and date in circtuitiks.sty, t-circuitikz.sty, and changelog
- [x] commit everything and publish the PR

Once merged, in the **main repository**:

- [x] run "make ctan" this will produce a zipfile. check the contents of this file (especially the version & date of docs & package)
- [x] go to page https://ctan.org/pkg/circuitikz
- [x] click on upload(at the top)
- [x] upload the zipfile and fill the missing fields ( I copied the changelog to the announcement field)
- [x] Add a github release with same infos & zip file & styles zip file
- [x] Add at the the link to the circuitikz-git file of the new release to the circuitikz github pages site (edit https://github.com/circuitikz/circuitikz/blob/gh-pages/index.html manually; remember to add the styles `.zip` if creating a checkpoint for this release)

![image](https://user-images.githubusercontent.com/6414907/59628234-6f22d900-9140-11e9-85e4-9f3b5b66f10f.png)

Another trick: to transform the link to a stable link, press "y" in the page showing it...  see https://help.github.com/en/articles/getting-permanent-links-to-files

Now the repository is frozen; I'll wait for:

- [x] Confirmation of the correct upload 
- [x] If the package is ok it will take a few days to spawn over all servers

And after that:

- [x] Prepare a branch in my repo to reinsert the git headline in the changelog file, and do a PR.
- [x] Merge your commits in the main repo to github

...and now development will continue.

**Comment by der-stefan** [comment]
Thank you very much, Romano! Your work on CircuiTikZ is totally amazing and I am glad that you took over the development and maintenance of the project. On conferences one can easily see if someone used CircuiTikZ for his schematics - and it is increasingly used...

**Comment by Rmano** [comment]
I just built upon the shoulder of giants...
 
I think that the package has its share of problems (sometimes the path-building is a bit fragile, and it's really monolithic --- should be divided into modules) but it's pretty usable now. I used it in my last paper and the circuits look really nice.

Thanks a lot for the nice words!
