### ISSUE TITLE
Circuitikz scale battery2 error 

### ISSUE THREAD

**Issue by AndreaDiPietro92** [circuitikz/circuitikz#367]
Problem with scale in circuitikz. The following code produce 

\documentclass[border=10pt]{standalone}
\usepackage[RPvoltages]{circuitikz}

\begin{document}

\begin{circuitikz}[scale=1.2, transform shape]
	\draw (12,1) to [battery2, v_=$V_{cc}$] ++(0,2);
\end{circuitikz}

\end{document}

The problem does not arise when the scale is an int value (scale=1,2,3 ..etc) or with no scale.

![img](https://user-images.githubusercontent.com/36949583/74765282-8c85e500-5283-11ea-99bb-306b8ba1c9da.png)

**Comment by Rmano** [comment]
Yes, confirmed. Puzzling.

**Comment by Rmano** [comment]
Oops, wrong button ;-). Reopening.

**Comment by Rmano** [comment]
I suspect some precision error in the positioning of the component in the path. That will not be easy to track down...

**Comment by Rmano** [comment]
If you change the coordinate `(12,1)` to `(0,1)` all is right. So it's a difficult problem... I opened a question here: https://tex.stackexchange.com/questions/529099/path-joining-in-to-path-with-non-integer-scale-factors

**Comment by AndreaDiPietro92** [comment]
it's a really strange problem.

**Comment by AndreaDiPietro92** [comment]
Little workaround! Using the scope enviroment for the shift.
```latex
\documentclass[border=10pt]{standalone}
\usepackage[RPvoltages]{circuitikz}

\begin{document}
	
	\begin{circuitikz}[scale=1.2, transform shape]
	\begin{scope}[shift={(11,0)}]
		\draw (1,1) to [battery2, v_=$V_{cc}$] ++(0,2);
	\end{scope}	
	\end{circuitikz}
	
\end{document}
```
![image](https://user-images.githubusercontent.com/36949583/74841864-ac6fe400-5329-11ea-927e-a170575aa242.png)

Much better then before!

**Comment by Rmano** [comment]
Yes, I suppose this is a kind of loss of precision in Ti*k*Z (well, in `pgfmath` basically). All calculations are done in 32-bit fixed arithmetic...
Let's see if the magical people from the TeX core can suggest a way to amend this, but I suspect it's not `circuitikz` related...

**Comment by Rmano** [comment]
Yes, I suppose this is a kind of loss of precision in Ti*k*Z (well, in `pgfmath` basically). All calculations are done in 32-bit fixed arithmetic...
Let's see if the magical people from the TeX core can suggest a way to amend this, but I suspect it's not `circuitikz` related...

**Comment by Rmano** [comment]
Well, the incredible Schrödinger's cat at https://tex.stackexchange.com/a/529159/38080 solved the issue... 

```
\documentclass[border=10pt]{standalone}
\usepackage[RPvoltages]{circuitikz}
\usetikzlibrary{fpu}
\makeatletter
%%
%% this code has been contributed by Schrödinger's cat
%% https://tex.stackexchange.com/a/529159/38080
%%
\tikzset{use fpu reciprocal/.code={%
\def\pgfmathreciprocal@##1{%
    \begingroup
    \pgfkeys{/pgf/fpu=true,/pgf/fpu/output format=fixed}%
    \pgfmathparse{1/##1}%
    \pgfmath@smuggleone\pgfmathresult
    \endgroup
}}}%
\makeatother

\begin{document}

\begin{circuitikz}[scale=1.2, transform shape,
    use fpu reciprocal,
    ]
\draw (12,1) to [battery2, v_=$V_{cc}$] ++(0,2);
\end{circuitikz}

\end{document}
```
