### ISSUE TITLE
LED

### ISSUE THREAD

**Issue by karlkappe** [circuitikz/circuitikz#370]
The arrows on the LED und photodiode, at least in the european version, are pointing in a different direction than given by DIN EN 60617 (LED: https://commons.wikimedia.org/wiki/File:Symbol_LED_IEC60617-5_Symbol_Nr_05-03-02.svg )
Stefan Lindner told me he prefers the now implemented ones, so maybe you could add the DIN EN sysmbols also?

**Comment by Rmano** [comment]
I will add a couple of flags to flip LEDs and photodiode arrows.

**Comment by Rmano** [comment]
![image](https://user-images.githubusercontent.com/6414907/75019283-e3143e80-5490-11ea-8a0c-9e0c0f1bf907.png)

**Comment by Rmano** [comment]
![image](https://user-images.githubusercontent.com/6414907/75020080-4e124500-5492-11ea-9d99-28d2c6a2f981.png)
