### ISSUE TITLE
Positioning node voltages correctly using the american voltage

### ISSUE THREAD

**Issue by rhandley** [circuitikz/circuitikz#374]
I recently had difficulty in correctly positioning the open-circuit voltage labels between two nodes using the american voltage notation. This was reported in https://tex.stackexchange.com/questions/529626/how-to-position-open-node-voltages-correctly, when using the `to[open, v=...]`. The only solution so far is to manually position the labels "+" and "-" to the desired position. There was also advice to open an issue as a feature request for this.

**Comment by Rmano** [comment]
The request is logical (position of american-style voltage markers on open circuits has no sense now). I will try to tackle this (I am thinking about revising the voltage label thing anyway, it's a bit of a mess now, also my fault).

**Comment by Rmano** [comment]
I looked at it, but it's quite difficult, and a very big rewrite would be needed. Hmm...
