### ISSUE TITLE
Add Schottky transistors

### ISSUE THREAD

**Issue by jmonclard** [circuitikz/circuitikz#375]
I would be interested in Schottky transistors symbols (a bipolar transistor with an S-shaped base similar to the schottky diode), in normal and multi-terminal variants.
That can be found in (mature) TTL-S and TTL-LS logic families.
Probably a straightforward addition to the library.
BTW : Thanks a lot for your so useful package !

**Comment by Rmano** [comment]
It is not difficult --- I'll see if I can find a moment to do it.
If someone is interested, I think that the best way is to define a new `\ifpgfcircdoschotty` and then add it where the base is drawn (but I'm open to other solutions...).

**Comment by Rmano** [comment]
![image](https://user-images.githubusercontent.com/6414907/75614282-65f36400-5b37-11ea-9239-f25ed9f9884d.png)

What do you think?

**Comment by jmonclard** [comment]
That's great ! Thank you so much for having been so amazingly reactive.
I will look forward for the next package update, or look at the change in your fork and patch my tex if I need to complete my document sooner.

**Comment by Rmano** [comment]
Nice to know you like it. You can also use the `...git` version at https://circuitikz.github.io/circuitikz as soon as I merge the PR...
