### ISSUE TITLE
IGBT symbol

### ISSUE THREAD

**Issue by RA-EE** [circuitikz/circuitikz#384]
I have few suggestions for circuit symbol used for IGBT.

- The present symbol has two identical parallel lines as shown in Fig. 1 in the attachment. However, some standard text books in Power Electronics show the first line (Gate or Base) has to be little shorter compared to the second line. Such a symbol is shown in Fig. 2 in the attachment. I had created it by adding white fill on both sides of the first line. This variation already exists in the nmos shown in Fig. 3 of attachment. I request the authors to include this new IGBT symbol also in the future versions of Circuitikz.

- Also some users may wish to have higher thickness for the first line and different type of arrows. It will be helpful if it is possible to add customization for the Base-line thickness and arrow tip type.

[IGBT.pdf](https://github.com/circuitikz/circuitikz/files/4443184/IGBT.pdf)

**Comment by Rmano** [comment]
This is the image: 
![image](https://user-images.githubusercontent.com/6414907/78654870-7f6d9580-78c5-11ea-82a4-dc8c917a2e9e.png)

**Comment by Rmano** [comment]
The shorter floating base with adjustable thickness should be easy.

The arrow thing, on the other hand, is quite complex --- they are not real arrow tips for a mainly historic reasons, and if I change it, the idea would be to change it for all the transistors, so that would be quite a big task. Anyway, if anyone is interested... ;-)

**Comment by Rmano** [comment]
I have it, using the options:

```latex
\ctikzset{tripoles/igbt/outer base height=0.3}
\ctikzset{tripoles/igbt/outer base thickness=1.5}
```

You have (comparing the normal ones, above, and the modified ones, below):

![image](https://user-images.githubusercontent.com/6414907/78709246-a5218b80-7913-11ea-8fb4-c4f529b77c90.png)

**Comment by Rmano** [comment]
I will merge this one as soon as I can --- so you can use it with the `git` version. 

The "arrow" part is much more complex; if you want you can add an issue for tracking, but, well, don't hold your breath...
