### ISSUE TITLE
Improve european logical NOT gates to match IEC 60613-12

### ISSUE THREAD

**Issue by j-hap** [circuitikz/circuitikz#385]
Hi,

when choosing european logical gates I'd like to have the symbol according to IEC, which has a little circle on the output for NOT, NAND, NOR, XNOR. The current symbols with the little triangle on the port is for indicating the polarity, according to the Standard, the circle is used for negation.
You can see an example of an IEC-NOT here:
https://de.wikipedia.org/wiki/XNOR-Gatter#/media/Datei:IEC_XNOR_label.svg

Thanks for the package!

Regards,

Julian

**Comment by Rmano** [comment]
I know *nothing* ;-) about european gates... somebody else can chime in? @mredaelli @sistlind @der-stefan @jesseopdenbrouw ?

**Comment by jesseopdenbrouw** [comment]
As far as I know, the circle is used when presenting a logic schematic without any ic type numbering (i.e. just a logic schematic) and the triangle is used when indicating a specific ic type (i.e. when placing a gate on a PCB).

**Comment by j-hap** [comment]
I can use this quick workaround. My LaTex skills are a bit rusty, but the package manual helps:
```
  \draw node[european buffer port] (A) {};
  \node at (A.bout) [ocirc, right]{}
```
Which is good enough for me for now.
Suggestion: since the european blocks are mostly the same, you could e.g. add [iec not/nor/nand port] to the possible options, to get the circle and keep the "european" behaviour.

**Comment by Rmano** [comment]
Yes, I was thinking about using an option similar to what you did. Although it's not so easy, because it has to twiddle the anchors in case someone chose to a zero-length external pins.
Will look into it!

**Comment by Rmano** [comment]
I will tackle this as soon as I merge the IEEE standard ports PR.

**Comment by Rmano** [comment]
This is my work-in-progress:
![image](https://user-images.githubusercontent.com/6414907/79634956-12cc8380-816e-11ea-9caa-75ade6b8d7ee.png)
