### ISSUE TITLE
Wrong rendering of IEEE standard logic port not circles

### ISSUE THREAD

**Issue by Rmano** [circuitikz/circuitikz#392]
![image](https://user-images.githubusercontent.com/6414907/79726286-d96d5280-82ea-11ea-988f-af8879fd325e.png)

It does not respect the class' line thickness! Doh. 

I will fix it asap and do a minor release. @asinghvi17  -- do you have any time forecast for when your example will be ready (no hurry, we have a lot of numbers available for minor releases...).

**Comment by asinghvi17** [comment]
I'll probably be able to get an example up by Friday, but don't wait on me.

**Comment by Rmano** [comment]
![image](https://user-images.githubusercontent.com/6414907/79736518-36243980-82fa-11ea-85be-309b73b6b634.png)
