### ISSUE TITLE
Request: Option to place dots on transformer

### ISSUE THREAD

**Issue by mlda065** [circuitikz/circuitikz#41]
Currently transformers look like this.

![no dot](https://cloud.githubusercontent.com/assets/7035647/16181692/35390b40-36e1-11e6-8833-d4a6477d4bcd.png)

I would like to be able to add dots to indicate polarity. Like this.

![same dots](https://cloud.githubusercontent.com/assets/7035647/16181699/4423cfb4-36e1-11e6-8383-9bc75a927fcc.png)
![different dots](https://cloud.githubusercontent.com/assets/7035647/16181700/442c60c0-36e1-11e6-9080-65806ae4dd81.png)

**Comment by gpitel** [comment]
Matt, 
I have the code for what you looking for below.  I used node[circ] -- but I do agree it would be nice to to have those dots built into the library.
http://onesolver.com/#!service=system_saved_load&id=16&tab=3

**Comment by bastien-roucaries** [comment]
Indentically for inductance, it vill be nice to have dot

**Comment by Rmano** [comment]
Would be nice, yes, but there are a couple of delicate things to take into account:
1. the color of the dot must follow the `color` option (not automatic, given the fact that this is a fill and not a stroke) 
2. it's important to choose a reasonable way to specify the dot position

**Comment by sistlind** [comment]
In my opinio its the same problem as #80 . Just draw it by hand. This is much more flexible. Nevertheless, a good idea might be to declare 4 anchors at correct positions to simplify the placement.

**Comment by Rmano** [comment]
Hmmm.... this seems a bug: 

![image](https://user-images.githubusercontent.com/6414907/52902315-55639a80-320f-11e9-9fb2-263c7ed0f393.png)

I will fix it on the way along, hoping it will not break anything.

**Comment by Rmano** [comment]
This is my proposal for the anchors:

![image](https://user-images.githubusercontent.com/6414907/52903131-bbedb600-3219-11e9-9fb4-c4d55f9c1ce2.png)

They will scale nicely with the size of the elements... 

![image](https://user-images.githubusercontent.com/6414907/52903198-4b936480-321a-11e9-8159-103a5559ef23.png)

I'll prepare a PR with it, as soon as I add it to the manual.
