### ISSUE TITLE
straightvoltages and arrow length

### ISSUE THREAD

**Issue by ArchangeGabriel** [circuitikz/circuitikz#410]
Hi there,

I can’t find a way to change arrow length of voltages when using `straightvoltages`. They are often too short, especially on sources:

```
\documentclass{standalone}
\usepackage[straightvoltages,european]{circuitikz}
\begin{document}
\begin{circuitikz}
    \draw (0,0) to [european voltage source,i=$I$,v=${U=E}$] (3,0);
\end{circuitikz}
\end{document}
```
[test.pdf](https://github.com/circuitikz/circuitikz/files/4737535/test.pdf)

I’ve tried to fiddle with `voltage/distance from node`, but to no avail.

**Comment by Rmano** [comment]
Unfortunately, it is fixed. I'll look into it. You can fake something with

```latex
\documentclass{standalone}
\usepackage[EFvoltages, european, straightvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}
    \def\eq{=}
    \draw (0,0) to [european voltage source,i=$I$,] (3,0);
    \draw (0,.5) to[open, v^=$U\eq E$, voltage=straight] ++(3,0);
\end{circuitikz}
\end{document}
```
![image](https://user-images.githubusercontent.com/6414907/83912138-a33a4400-a76d-11ea-851a-e3b382507bd7.png)

The need of `voltage=straight` in the `open` bipole is a bug :-(

**Comment by Rmano** [comment]
Ah, no, it's not a bug. The problem is that `european` and `straightvoltages` option conflicts, and `european` wins.

**Comment by ArchangeGabriel** [comment]
Thanks for the workaround. Regarding priority of `european` and `straightvoltages`, note that I had them in reverse order. ;)

**Comment by Rmano** [comment]
The order of options when loading this package is not really significant (it is not respected). I do not want to change it for backward compatibility. 
This is one reason for which I prefer using styling (`\ctikzset{voltage=straight}`) for this kind of options; it's much more controllable and stable across versions. 
BTW, both  `european` and  `straight` have straight arrows for voltage in case of generators. I do not know why, but it is like this since, well, forever. I still feel that they are really cramped, and I'll try to adjust them a bit in one of the new versions.

**Comment by Rmano** [comment]
> especially since there is no shortcut for `european voltage source`

Notice that you can define your shortcuts easily using Ti*k*Z styles:

```latex
 \documentclass{standalone}
\usepackage[EFvoltages, straightvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}
    \def\eq{=}
    \tikzset{EVS/.style={european voltage source}}
    \tikzset{EVSbig/.style={european voltage source, sources/scale=1.5}}

    \draw (0,2) to [EVS,i=$I$,v=$U\eq E$] ++(3,0);
    \draw (0,0) to [EVSbig,i=$I$,] ++(3,0);
    \draw (0,.8) to[open, v^=$U\eq E$] ++(3,0);
\end{circuitikz}
\end{document}
```

**Comment by Rmano** [comment]
Anyway ... the main problem you have is that the voltage generators have (for historical reasons) a different voltage label treatment than the other bipoles (which involves switching the side of where the label is --- don't ask). So you can simply ask to treat the component as a standard bipole:

```latex\documentclass{standalone}
\usepackage[EFvoltages, straightvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}
    \def\eq{=}
    \draw (0,0) to [european voltage source, bipole/is voltage=false, i=$I$, v=$U\eq E$] (3,0);
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/84050727-68731e80-a9ae-11ea-87ea-8d3383b184e9.png)

...and you can put it into a style as shown above.

**Comment by Rmano** [comment]
There was an error in the order of options. I changed it in commit https://github.com/circuitikz/circuitikz/pull/411/commits/7ffab765853eb1bed8c4c0273da8a5cca18331fe

**Comment by ArchangeGabriel** [comment]
The `bipole/is voltage=false` trick solves the length, but it reverses the arrow direction too (at least with RPvoltages)… So that’s not good.

Good point for fixing the options order though. ;)

**Comment by Rmano** [comment]
> The `bipole/is voltage=false` trick solves the length, but it reverses the arrow direction too (at least with RPvoltages)… So that’s not good.

Yes, but it's expected because now the bipole is treated as a passive element....

**Comment by ArchangeGabriel** [comment]
Indeed, I’m just saying this is not a proper workaround. ;)

**Comment by Rmano** [comment]
> Indeed, I’m just saying this is not a proper workaround. ;)

Well, you can just use `v<` then... ;-) . 

If I could go back on time, I will remove all "direction" versions, use a fixed default direction for voltages, currents, and flows (arrows in the same direction of path, independent on the device, full stop) and then let adjust it with `<` and `>`. 

Too late...

**Comment by ArchangeGabriel** [comment]
OK, so using `v^>=` I finally got what I wanted. But I don’t understand in what way your PR solves the issue…

**Comment by Rmano** [comment]
No, it really doesn't close the first issue, sorry --- reopened. 

The matter is that there are workarounds that are easily applied, and the time to implement an option to make arrows longer I think it's better applied to other things... for now. I will add  the workarounds to the manual, and in the meanwhile, I'll let this issue open to see if somebody shows up with a PR...

**Comment by Rmano** [comment]
Now it's in the manual:

![image](https://user-images.githubusercontent.com/6414907/86109771-05fcd200-bac5-11ea-8b28-fce1efb89353.png)

![image](https://user-images.githubusercontent.com/6414907/86109812-12812a80-bac5-11ea-8d4e-248d70a677a6.png)
![image](https://user-images.githubusercontent.com/6414907/86109836-1ad96580-bac5-11ea-8152-584565695462.png)
