### ISSUE TITLE
Some additional Block Symbols

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#440]
It would be nice to have also these symbols:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/1970554/94307197-a0f63280-ff74-11ea-8b2b-bee4e1c6d0f1.png">

<img width="287" alt="image" src="https://user-images.githubusercontent.com/1970554/94307209-a5bae680-ff74-11ea-8fb0-575fe7377487.png">

**Comment by Rmano** [comment]
Yes, this is a good idea. The `allpass` is missing, yes, and should be added. 

For the other one --- probably it would be better to have a block with two generic labels --- I will look into it as soon as I have a bit of time.

**Comment by Rmano** [comment]
In version 1.2.4, you'll be able to do this:

![image](https://user-images.githubusercontent.com/6414907/94362962-1241fc80-00bf-11eb-8521-e36df23ebfc2.png)

**Comment by myzinsky** [comment]
Thats so awesome! Thank you very much!
