### ISSUE TITLE
Single Port Speaker

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#443]
<img width="54" alt="image" src="https://user-images.githubusercontent.com/1970554/94365697-40c9d280-00d3-11eb-98e7-5b28e9691e5f.png">

A Single-Port Speaker would be also great!

**Comment by Rmano** [comment]
This seems not a standard symbol, or block, and it's easy to do with a `pic` in plain TikZ... Unless you can give me any reference, I am not prone to add random symbols to `circuitikz` , sorry...

**Comment by Rmano** [comment]
For example: 

```
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}
    \draw node[vcoshape](V){} -- ++(2,0) node[loudspeakershape, anchor=south, rotate=-90](L){};
    \draw [-Triangle] (V.east) -- (L.south);
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/94455330-3848c900-01b3-11eb-8d80-e8440fdc9b9a.png)

**Comment by myzinsky** [comment]
Ah great, I was not aware that I can use the loudspeaker shape! Thanks
