### ISSUE TITLE
VFO Symbol

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#444]
![image](https://user-images.githubusercontent.com/1970554/94367042-2d6f3500-00dc-11eb-9a2c-06111f5bd191.png)

Also this would be nice.

**Comment by Rmano** [comment]
I am not sure what symbol is this... The resolution is really low ans I do not know the meaning of VFO.

Can you please give more info?

**Comment by myzinsky** [comment]
Oh Sorry for that. 

VFO is Variable Frequency Oscillator. The shape is like the all pass but it has an arrow in the middle pointing into the upper right corner.

**Comment by Rmano** [comment]
We have the standard VCO (the round one). Usage of round shapes is normal with generators and mixers... Or am I wrong?

**Comment by Rmano** [comment]
Anyway, you can have it easily now:

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}[
    ]
    \node [allpassshape, name=AP]{};
    \draw [-Triangle, shorten >=4pt, shorten <=4pt] ([xshift=4pt]AP.sw) -- ([xshift=-4pt]AP.ne); 
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/94781527-44f33a00-03ca-11eb-894e-6c3fd6e7dbaa.png)

**Comment by Rmano** [comment]
I think that can be closed, what do you think?
