### ISSUE TITLE
wrong label information in voltage source

### ISSUE THREAD

**Issue by judober** [circuitikz/circuitikz#447]
The voltage source seems to use the label of other elements if no label is specified.
```
\documentclass[class=report, ngerman,11pt,a4paper,tikz,]{standalone}

\usepackage[european, straightvoltages, americaninductors, betterproportions, nooldvoltagedirection]{circuitikz}

\begin{document}
\begin{tikzpicture}

\draw (90:3) [L, o-, l={\(L_{ab}\)}] to (90:1.5) [V, -*, v={\(v_{12}\)}] to (90:0);

\end{tikzpicture}%
\end{document}

```
[Voltagesource.pdf](https://github.com/circuitikz/circuitikz/files/5306453/Voltagesource.pdf)

**Comment by Rmano** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/6414907/94776973-f7bf9a00-03c2-11eb-8e16-def2b90285ef.png)

**Comment by Rmano** [comment]
As a workaround, you can use for now

```
\draw (90:3) [L, o-, l={\(L_{ab}\)}] to (90:1.5) [V, -*, l=, v={\(v_{12}\)}] to (90:0);
```

At least is not a regression; tested backward to `0.8.3` and it's still there. Awesome that it didn't show up before.

**Comment by Rmano** [comment]
Ach! ;-) you used the wrong notation... the element are `to[element, option] (coordinate)`, not `[option] to (coordinate)`; the last one use the plain Ti*k*Z `to` that does not reset the component variables.

```
\documentclass[class=report, 11pt,a4paper,tikz,]{standalone}

\usepackage[european, straightvoltages, americaninductors, betterproportions, nooldvoltagedirection]{circuitikz-0.8.3}

\begin{document}
\begin{tikzpicture}

\draw (90:3) to[L, o-, l={\(L_{ab}\)}] (90:1.5) to[V, -*, v={\(v_{12}\)}] (90:0);

\end{tikzpicture}%
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/94780288-82ef5e80-03c8-11eb-97a9-b21b1936cd82.png)

**Comment by judober** [comment]
Allright thanks!
