### ISSUE TITLE
Problem with diamond shape and `\usetikzlibrary{shapes.geometric}`

### ISSUE THREAD

**Issue by samcarter8** [circuitikz/circuitikz#45]
The new diamond shape, introduced in version 0.6, seems to cause problems in combination with `\usetikzlibrary{shapes.geometric}`. See the following questions

http://tex.stackexchange.com/questions/319250/tikz-black-dot-diamond-in-center-of-all-diamond-shapes
http://tex.stackexchange.com/questions/318070/tiny-artefact-diamon-in-tikz

**Comment by sistlind** [comment]
Should be fixed with 0bc542d and 53e5e50
