### ISSUE TITLE
European XNOR Gate

### ISSUE THREAD

**Issue by Schlepptop** [circuitikz/circuitikz#467]
According to the IEC 60617-12, an XNOR Gate should not be represented as a negated XOR (XOR with a small circle) but rather like this:
![image](https://user-images.githubusercontent.com/30201479/102109014-e4ee2a80-3e33-11eb-8e18-9b530f7b6313.png)

I understand that this is probably less intuitive, but would it be possible to at least make this an option, if not the default?

**Comment by Rmano** [comment]
Hmmm --- I am not an expert at all of European symbols (never used in the last 40 years spent in Italy, US, and Spain). 
For sure that change should be added with an option, not in an absolute way. Moreover, IEC say this:

![image](https://user-images.githubusercontent.com/6414907/102124819-06a5dc80-3e49-11eb-9884-e3a9b096fef9.png)

So I am not sure that the symbol is still current.

**Comment by Rmano** [comment]
Momentarily, you can use this trick to use the port you like:

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\pgfcircdeclareeurologicport{xnor}{$=$}{2}{}
\begin{document}
\begin{circuitikz}[
    european]
    \node [xnor port]{};
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/102126174-0ad2f980-3e4b-11eb-980f-984ce9ce15b0.png)

**Comment by Schlepptop** [comment]
> Hmmm --- I am not an expert at all of European symbols (never used in the last 40 years spent in Italy, US, and Spain). 
> For sure that change should be added with an option, not in an absolute way. Moreover, IEC say this:
> 
> ![image](https://user-images.githubusercontent.com/6414907/102124819-06a5dc80-3e49-11eb-9884-e3a9b096fef9.png)
> 
> So I am not sure that the symbol is still current.

The 1997 version of the standard was withdrawn in favor of one published in 2012. Afaik the stance on this specific symbol didn't change, though.

**Comment by Rmano** [comment]
What about this: 

```latex
\begin{document}
\begin{circuitikz}[
    european]
    \node [xnor port]{};
\end{circuitikz}

\ctikzset{european xnor style=iec}

\begin{circuitikz}[
    european]
    \node [xnor port]{};
\end{circuitikz}
\end{document}

**Comment by Rmano** [comment]
Hmmm... ok, although I found also this https://www.robotshop.com/community/tutorials/show/electronics-done-quick-7-logic-gates 

I find the European symbols confusing. The fact that the shapes are the same and you have to read the labels makes the thing much more difficult.

**Comment by Schlepptop** [comment]
> What about this:
> 
> ```
> \begin{document}
> \begin{circuitikz}[
>     european]
>     \node [xnor port]{};
> \end{circuitikz}
> 
> \ctikzset{european xnor style=direct}
> 
> \begin{circuitikz}[
>     european]
>     \node [xnor port]{};
> \end{circuitikz}
> \end{document}
> ```
> 
> ![image](https://user-images.githubusercontent.com/6414907/102258312-189d8300-3f0e-11eb-826f-ecb974bb68bf.png)

That looks good to me.
