### ISSUE TITLE
Extend vacuum tubes to PMTs

### ISSUE THREAD

**Issue by ferdymercury** [circuitikz/circuitikz#469]
Thank you for this very nice Package.

I wanted to suggest a future feature expanding on the already existing diode, triode and pentodes.

![image](https://user-images.githubusercontent.com/10653970/102202866-d46e9c00-3e95-11eb-9fb7-e5592318b55f.png)

It would be nice to be also to draw photomultiplier tubes, which consist of several Dynodes in addition to anode and cathode.

Here some inspiring screenshots from different drawing styles I found in the literature:
![image](https://user-images.githubusercontent.com/10653970/102204868-65467700-3e98-11eb-9e20-213a1c23c0e6.png)
![image](https://user-images.githubusercontent.com/10653970/102203582-c2d9c400-3e96-11eb-8214-ea7311ddfe4e.png)
![image](https://user-images.githubusercontent.com/10653970/102204958-84dd9f80-3e98-11eb-9739-d3773cd4151e.png)
![image](https://user-images.githubusercontent.com/10653970/102203664-ddac3880-3e96-11eb-9dc5-bc9dd69f9db6.png)
![image](https://user-images.githubusercontent.com/10653970/102203988-4693b080-3e97-11eb-9db9-9b4d902619f3.png)
![image](https://user-images.githubusercontent.com/10653970/102204545-f537f100-3e97-11eb-93b2-6ea5494ffce6.png)
![image](https://user-images.githubusercontent.com/10653970/102203057-1ac3fb00-3e96-11eb-88ee-b36068e0edad.png)
![image](https://user-images.githubusercontent.com/10653970/102203107-29aaad80-3e96-11eb-9cb0-c13ffddee00a.png)
![image](https://user-images.githubusercontent.com/10653970/102203215-4cd55d00-3e96-11eb-81f5-775882977d6e.png)

See https://www.hamamatsu.com/resources/pdf/etd/PMT_handbook_v4E.pdf
http://lmu.web.psi.ch/docu/manuals/bulk_manuals/PMTs/Photonis_PMT_basics.pdf

**Comment by Rmano** [comment]
Uy, these are very very specific components --- I suspect that a one-off Ti*k*Z `pic` would be more interesting. 
Let's ping the author of the tubes... @jesseopdenbrouw

**Comment by ferdymercury** [comment]
Thanks! An alternative would be to just define the IEC dynode symbol that looks like a curved capacitor with a line across, and then one builds itself its tube as needed in the tex file.

**Comment by Rmano** [comment]
Yes, that could be an idea. Which size should that component be, for example, with respect to the tubes?

**Comment by ferdymercury** [comment]
Well, that depends on how many dynodes a tube has.
For the symbol, it would be helpful that the size of the dynode symbol is smaller than that of a resistance, so that a resistor fits well inbetween two dynodes, as in the pic below.

![image](https://user-images.githubusercontent.com/10653970/102281503-0b2bcd00-3efd-11eb-8ad8-2800b7739c01.png)

**Comment by Rmano** [comment]
What about this?

![image](https://user-images.githubusercontent.com/6414907/102348962-e427d680-3fa2-11eb-8fbc-b2a3d321c105.png)

Questions: should be the arc half a circle or less? Configurable? 

Now you can configure width, height and the position of the arc.

**Comment by ferdymercury** [comment]
Thanks so much. I think it is a little bit less than half a circle. See https://www.noao.edu/ets/Mechanical/Policies/ANSI%20Y32.2-1975.pdf point 7.1.4.1 on page 51
Looks like it stops at about +/- 60 or 70 degrees, it's hard to see on the IEC picture. I don't think the angle needs to be configurable.

**Comment by Rmano** [comment]
Now is completely configurable:

![image](https://user-images.githubusercontent.com/6414907/102365069-75a14380-3fb7-11eb-8d27-d516c30e39ce.png)

**Comment by ferdymercury** [comment]
Gracias Romano, genial!!

**Comment by ferdymercury** [comment]
I guess that, to fully build the PMT tube, one would also need a photocathode monopole, and an anode monopole.

![image](https://user-images.githubusercontent.com/10653970/102366028-7686a500-3fb8-11eb-97f2-ab8671b711e4.png)


![image](https://user-images.githubusercontent.com/10653970/102365921-5ce55d80-3fb8-11eb-8258-7a7aa57392cd.png)

**Comment by Rmano** [comment]
Ah! Play with the parameters of dynode and... 

![image](https://user-images.githubusercontent.com/6414907/102367474-1db80c00-3fba-11eb-9ae8-6358af93d74f.png)

**Comment by Rmano** [comment]
I think that the grid can be easily made with simple lines...

**Comment by ferdymercury** [comment]
simply amazing... thanks!

**Comment by Rmano** [comment]
Now, should I put it with the antennas (RF) or with the tubes? Opinion?

**Comment by Rmano** [comment]
I think tubes is best, after magnetron

**Comment by Rmano** [comment]
The merge will close this isuue, feel free to repoen if needed (also to @jesseopdenbrouw )

**Comment by ferdymercury** [comment]
Thanks so much.
One minor nomenclature thing. If this element is thought to be used for anode, dynode and cathode, then it should be maybe renamed to the generic term electrode.
The 'electrode' customization creates dynodes, anodes or cathodes, rather than the 'dynode' customization.

On the other hand, if the default values of the parameters create a dynode, then I guess it makes sense to call it "dynode" heheh.

**Comment by Rmano** [comment]
> On the other hand, if the default values of the parameters create a dynode, then I guess it makes sense to call it "dynode" heheh.

Yes, that one was my reasoning ;-)
