### ISSUE TITLE
Amplifier is boxed by default, inner label not displayed

### ISSUE THREAD

**Issue by yigit007** [circuitikz/circuitikz#47]
I am trying the example at the section 6.3 in the documentation, where an amplifier contains LNA label inside it. 
![image](https://cloud.githubusercontent.com/assets/7838452/17671969/7182dcee-6322-11e6-9ae4-508d09691843.png) 

Here is the code for this example:
```
\begin{circuitikz}
\ctikzset{bipoles/amp/width=0.9}
\draw (0,0) to[amp,t=LNA,l_=$F{=}0.9\,$dB,o-o] ++(3,0);
\end{circuitikz}
```

When I try this on my Windows machine (MikTex 2.9, PGF 3, Circuitikz 0.6), I get the following:
![circuitikz](https://cloud.githubusercontent.com/assets/7838452/17671862/d8bbea14-6321-11e6-819e-d31e5732c4c5.png)

This is different than what I've expected; amplifier is boxed, and LNA label is missing in the amplifier. What can be the problem here?

**Comment by der-stefan** [comment]
The current version just works fine. You should check if you are really using the latest version, as you stated. In most cases this is the problem. By the way: You don't use the "box" option, so the amplifier should be without box.

Please check and close the issue in case.
