### ISSUE TITLE
node labels and color

### ISSUE THREAD

**Issue by ferdymercury** [circuitikz/circuitikz#475]
I found here https://tex.stackexchange.com/questions/226534/label-node-in-circuitikz a way to label the node.

I was wondering if there is a way to change the color of both the node name and the dot (circ). (I could not find how).

If yes, maybe all these informations could be added to the manual?

Thanks in advance.

**Comment by Rmano** [comment]
I am not sure if I understand... is this that you are looking for?

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}[
    ]
    \draw (0,0) to[R] ++(3,0) coordinate(a) to[R] ++(3,0);
    \path[color=red] (a) node[circ]{} node[above]{$A$};
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/102599500-d8acea80-411d-11eb-9472-7f85d9932ed1.png)

This is really a Ti*k*Z thing; the only problem (and it is noticed in the manual, in the "color" chapter) is that for `circuitikz` components to follow the path color, you need to use `[color=red]` (not the short form `[red]` normally used in Ti*k*Z).

**Comment by ferdymercury** [comment]
Yes, you understood correctly my question.

The workaround I had used was:
`\fill[red] (coordinate) node[anchor=south] {$A$} circle (2pt);`

Maybe your example can be added on the manual 'How to add labels on nodes' even if it is not using specifically circutikz?
Thanks!

**Comment by ferdymercury** [comment]
Also, would it be possible to achieve the same in one line instead of two, using the label keyword, as in https://tex.stackexchange.com/questions/226534/label-node-in-circuitikz ?

**Comment by Rmano** [comment]
Like this? 

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}
    \draw (0,0) to[R] ++(3,0) node[color=red, circ, label={[red]above:$A$}]{} to[R] ++(3,0);
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/102627598-b54b6500-4148-11eb-8ecb-c9ca963c13e5.png)

About the manual: this is more a Ti*k*Z thing; the `label` keyword applies to any node --- look at 17.10, "The label and pin options", around page 250.

**Comment by ferdymercury** [comment]
Thanks! Solved
