### ISSUE TITLE
Adding a symbol for Graphene Fet. 

### ISSUE THREAD

**Issue by emcees2** [circuitikz/circuitikz#496]
![grafeenfet](https://user-images.githubusercontent.com/51156101/110423395-41fb2480-80a1-11eb-9b65-da8db22182dd.png)
Is it possible to add a symbol for the Graphene Fet?

And how should i do it?

Kind regards,
Cees
Both symbols used in an inverter below
![inverter](https://user-images.githubusercontent.com/51156101/110423912-33f9d380-80a2-11eb-9633-917c6ab724d3.png)

Both pictures are taken form:
Analog Integrated Circuits and Signal Processing (2020) 102:637–644
https://doi.org/10.1007/s10470-020-01624-x
(0123456789().,-volV)(0123456789().,-volV)

**Comment by Rmano** [comment]
Probably the best way to proceed is starting from a form of `igbt` and tweak the shape a bit. As a stop-gap (the hexagon is not a hexagon, I know) the idea could be this:

```latex
\begin{tikzpicture}[]
    \tikzset{gfet/.style={
        nigbt,
        circuitikz/transistors/arrow pos=end,
        circuitikz/tripoles/nigbt/outer base height=0.3,
        circuitikz/tripoles/nigbt/outer base thickness=2,
        circuitikz/tripoles/nigbt/width=0.5,
        circuitikz/tripoles/nigbt/height=1.3,
    }}
    \draw node [gfet](G){} (G.inner up) -- ++(0.4,-0.27) --++(0,-0.3) -- (G.inner down);
\end{tikzpicture}
```

![image](https://user-images.githubusercontent.com/6414907/110440582-1d12ab80-80b9-11eb-932a-d0a883a0efc4.png)

I will see if I can give  it a shot as soon as I have a bit of time. Basically, the idea is to look into `tex/pgfcirctripoles.tex`, duplicate the `igbt` component, and modify it to create the new one.

**Comment by Rmano** [comment]
Do you like these?:

![image](https://user-images.githubusercontent.com/6414907/110970714-50c03080-835a-11eb-8008-19acbf4371d6.png)

**Comment by Rmano** [comment]
@emcees2 I forgot the ping for the above message. I think I have them --- I'll try to integrate them soon.
How do you like to be cited/thanked in the manual?
