### ISSUE TITLE
Allowing labels above and below a short at the same time?

### ISSUE THREAD

**Issue by fixxl** [circuitikz/circuitikz#50]
In the following simple drawing there should be one label above and one label below the line. Still, only the last called label is displayed:

\begin{circuitikz}
    \draw
    (0,0) to [short, l_=Below, l^=Above](3, 0)     ;
\end{circuitikz}

Is there a chance to get both displayed at the same time?

**Comment by sistlind** [comment]
You can use the annotation option "a", please have a look at the manual, section 5.1:

    \begin{circuitikz}
    \draw (0,0) to[R, l=$R_1$,a=1<\kilo\ohm>] (2,0);
    \end{circuitikz}
