### ISSUE TITLE
Flip-flop with nu=1 also draws pin at "down"

### ISSUE THREAD

**Issue by BillNace** [circuitikz/circuitikz#501]
If I use the following to make an active-low preset on a flip-flop, I also suddenly get a pin on the reset position (down).

`\documentclass[tikz]{standalone}
\usepackage{tikz}
\usepackage[RPvoltages]{circuitikz}
\tikzset{flipflop DQ/.style={flipflop, scale=.7,
         flipflop def={t1=D, t6=Q, c3=1,
         clock wedge size=.3, font=\normalsize}
}}
\tikzset{flipflop DQP/.style={flipflop, scale=.7, % Has D, Q, and Preset
         flipflop def={t1=D, t6=Q, c3=1, nu=1,
         clock wedge size=.3, font=\normalsize}
}}
\begin{document}

\begin{circuitikz}
  \node[flipflop DQP] (ff0) at (0,0) {};
  \node[flipflop DQ]  (ff1) at (3,0) {};
\end{circuitikz}

\end{document}`

Rendered thusly:
<img width="211" alt="mwe-image" src="https://user-images.githubusercontent.com/1286667/111055822-b3dbc100-8447-11eb-8d05-07035d1968e5.png">

**Comment by Rmano** [comment]
Yes, thanks. This is fixed in #502

**Comment by Rmano** [comment]
See also a longish answer in https://tex.stackexchange.com/questions/587213/how-do-i-use-the-reset-connection-on-a-flip-flop

**Comment by Rmano** [comment]
This is a small, but quite nasty bug. I will release version 1.3.2 today-ish
