### ISSUE TITLE
Compatibility problems with "label distance", after updating circuitikz to version 1.3.3

### ISSUE THREAD

**Issue by JetherReis** [circuitikz/circuitikz#519]
I've been using circuitikz since version 0.3.0, and for at least two years, I'm using also the tikz library "circuits.plc.ladder".

Today (april, 4, 2021) I updated circuitikz to version 1.3.3 form 1.3.0, and as soon as I used it, the distance of the labels used in ladder diagrams using the circuits.plc.ladder library, became too big and cannot be controled anymore.

See the files attached in the zip file:

[CircuitikzIssues.zip](https://github.com/circuitikz/circuitikz/files/6332284/CircuitikzIssues.zip)

Jether Reis

**Comment by Rmano** [comment]
Hmmm, probably a clash with the `label distance` new switch. Will check. Could you please translate the title into English? Thanks.

**Comment by Rmano** [comment]
Probably the solution is just to remove the lines 35 and 36 here: https://github.com/circuitikz/circuitikz/commit/1f7b5989910b0a857052cfa55639814f004955ed#r49692875

**Comment by JetherReis** [comment]
> 
> 
> Hmmm, probably a clash with the `label distance` new switch. Will check. Could you please translate the title into English? Thanks.

Sorry, I had started to write the text in Portuguese when I was going to send it, I realized that I should write it in English, but I forgot to translate the title, thanks for the warning.

Jether Reis

**Comment by Rmano** [comment]
Hi, no problem! Could you confirm that the fix is working?

**Comment by JetherReis** [comment]
> 
> 
> Hi, no problem! Could you confirm that the fix is working? Please re-open in case of problems.
> Thanks!

Ok it's working, thanks.

Jether Reis
