### ISSUE TITLE
Drawing inductors (cute or american) stopped working

### ISSUE THREAD

**Issue by jnareb** [circuitikz/circuitikz#53]
Drawing inductors (whether with 'cuteinductors' or 'americaninductors' option) works on one machine (with older circuitikz), but does not work on other machine (with most current circuitikz).

```
! Undefined control sequence.
\pgf@sh@bg@americaninductorshape ...onadjustments
\advance \pgf@circ@res@ste...
l.470 \draw (3,1) to[L,l^=$L$] (3,-1)
```

```
! Undefined control sequence.
\pgf@sh@bg@cuteinductorshape ...mationadjustments
\par \pgfmathsetlength {\p...
l.470 \draw (3,1) to[L,l^=$L$] (3,-1)
```

**This combination of versions does not work:**
 pdfTeX, Version 3.1415926-2.3-1.40.12 (MiKTeX 2.9)
 PGF/TikZ from 2014-02-28
 pgf 2013/12/18 v3.0.0 (rcs-revision 1.14)
 circuitikz 2016/09/08 The CircuiTikz circuit drawing package version 0.7

**Comment by sistlind** [comment]
Please update your complete installation, your pgf/tikz version is too old.  This can be done using the miktex update tool. It could be, that you have to run the update several times due to your old installation.

**Comment by sistlind** [comment]
Problem solved? If not, just reopen the issue
