### ISSUE TITLE
Request: Microstrip Transmission Lines

### ISSUE THREAD

**Issue by tcpluess** [circuitikz/circuitikz#54]
The symbol for a coaxial transmission line is already available. However, there is also a wide usage of microstrip transmission lines and stubs. Two new symbols could be added: a bipole for the transmission lines. It has the same shape as an european resistor, but twice as long. Further, a microstrip stub is also needed, which has the same symbol as before, but with only one connection.

Is that possible?

I have already written the code for a microstrip radial stub:

```
\pgfdeclareshape{radialstub}{\anchor{center}{\pgfpointorigin}
\behindforegroundpath{
    \pgfscope
        \pgfstartlinewidth=\pgflinewidth
        \pgfsetlinewidth{\pgfkeysvalueof{/tikz/circuitikz/bipoles/thickness}\pgfstartlinewidth}
        \pgfpathmoveto{\pgfpointorigin}
        \pgfpathlineto{\pgfpointpolar{30}{6mm}}
        \pgfpatharc{30}{150}{6mm}
        \pgfpathclose
        \pgfusepath{draw}
    \endpgfscope
    }
}
```

However, I don't know how to create the bipoles.

**Comment by Rmano** [comment]
Hi @tcpluess  (I know it's a long time...), your symbol is something like this:
![image](https://user-images.githubusercontent.com/6414907/53328598-a13ad180-38ea-11e9-9ead-20bc9c5c3cef.png)
...for which I can't see how the description fits:

> Two new symbols could be added: a bipole for the transmission lines. It has the same shape as an european resistor, but twice as long. Further, a microstrip stub is also needed, which has the same symbol as before, but with only one connection.

...given that an european resistor is just a rectangle. Could you please add an example symbol and how it is connected?

**Comment by tcpluess** [comment]
sorry for my late reply as well. See the attached printscreen from a microwave CAD package. It shows an example of how to use the transmission lines symbols as well as the radial stub. In my original posting it appears as if I had posted some wrong code, don't know how that happened :-)

![microstrips](https://user-images.githubusercontent.com/16662475/55110630-be74e280-50d8-11e9-8496-b45906cd2854.png)

The rectangles and radial stubs don't represent actual circuit elements but transmission lines having a specified width and height. See another example on a PCB here:

https://en.wikipedia.org/wiki/Stub_(electronics)#/media/File:Microstrip_Low_Pass_Bowtie_Stub_Filter.jpg

This kind of symbol is required to draw schematics of commensurate circuits.
https://en.wikipedia.org/wiki/Commensurate_line_circuit

**Comment by Rmano** [comment]
Ah, ok. 
These two components are not difficult to create, I'll see if I can add them.

**Comment by Rmano** [comment]
Hi, I just realized that we have these two components: 

`tline`, `TL`: 
![image](https://user-images.githubusercontent.com/6414907/55414873-4856fc80-556c-11e9-923e-42b832d0dcb8.png)

`tlinestub`: 
![image](https://user-images.githubusercontent.com/6414907/55414927-59a00900-556c-11e9-9da3-38af2a01c5d7.png)

(Forget the colors, just my fiddling). Are they just another style?

**Comment by sistlind** [comment]
one is a stub (end of tline), therefore, they are not te same

Am Di., 2. Apr. 2019 um 17:26 Uhr schrieb Romano Giannetti <
notifications@github.com>:

**Comment by Rmano** [comment]
Yes; but the OP is asking for "simply square" elements, I think --- a transmission line which is simply a rectangle, a linear stub, and a radial stub. We have two of them but with a different shape; I am not into the RF electronics so I do not know if it's just another style or if the "cylindrical" ones we have are correct or whatever.

**Comment by Rmano** [comment]
@tcpluess, what do you think of:
![image](https://user-images.githubusercontent.com/6414907/56056368-448d5c00-5d5c-11e9-9e2b-f8783eb2d3c1.png)

**Comment by Rmano** [comment]
I will merge the change (which will close the issue). @tcpluess, feel free to comment here or reopen the issue if you need to.
