### ISSUE TITLE
Bug with +() coordinates

### ISSUE THREAD

**Issue by Rmano** [circuitikz/circuitikz#569]
See https://tex.stackexchange.com/questions/604366/how-do-i-fix-incorrect-label-placement

```latex
\documentclass[border=0.5cm]{standalone}
% \usepackage[oldvoltagedirection]{circuitikz}[=v0.8.3]
\usepackage[oldvoltagedirection]{circuitikz}


\begin{document}
\pgfcircversion
\begin{circuitikz}%[circuitikz/label/align=rotate]
\draw (0,0) to [L,l=$L_{nn}$] +(5,0);
\end{circuitikz}
\end{document}
```

gives:

![image](https://user-images.githubusercontent.com/6414907/125120907-70dae300-e0f3-11eb-8637-40ff6d845530.png)

**Comment by Rmano** [comment]
This change to `pgfcirclabel.tex`: 
[pgfcirclabel.zip](https://github.com/circuitikz/circuitikz/files/6793262/pgfcirclabel.zip)

seems to fix this:

![image](https://user-images.githubusercontent.com/6414907/125121062-a8498f80-e0f3-11eb-8be1-fc4d1ec30c95.png)

**Comment by ctmalan** [comment]
I am busy installing TexLive2021 on a new machine - will report tomorrow.

**Comment by ctmalan** [comment]
Can confirm the error on:  This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021/W32TeX) (preloaded format=pdflatex 2021.7.10)  10 JUL 2021 10:39

Can also confirm that the upgated pgfcirclabel.tex fixed the issue.

**Comment by Rmano** [comment]
Can you also please give the Pgf/Tikz version for failing and not failing? You can see them with `\pgfversion`...

Thanks for the test, I'll merge the fix as soon as I can (and do a release)

**Comment by Rmano** [comment]
No need, I checked it with overleaf. This is a nasty combination of a bug fix on TikZ and an old change in circuitikz that worked thanks to the bug in TikZ... will merge soon.
