### ISSUE TITLE
Connection corners, dipoles

### ISSUE THREAD

**Issue by iuliuv** [circuitikz/circuitikz#58]
When connecting dipoles at right angle, the connection is not nice:
`\draw (0,0) to[R] (0,2) to[R] (2,2);`
![corner](https://cloud.githubusercontent.com/assets/1033518/22173097/6385e318-dfc1-11e6-8465-76ff9825230f.png)

the same connection with wires looks much better:
`\draw (0,0) -- (0,2) -- (2,2);`
Am I missing something? Any easy way to avoid the issue? If nothing else maybe a node that draws a filled square of linewidth size could be a temporary solution? (similar to `node[circ]{}` )
thanks!

**Comment by sistlind** [comment]
The commit breaks support of relative coordinates at paths--> old behavior reverted and so solution at all

**Comment by sistlind** [comment]
Please try:
`\draw (0,0)to[R,-.]++(0,2)to[R]++(2,0);`
this can be combined with *,o,d as regular pole shape.
