### ISSUE TITLE
node[x]{}; produces nothing with some components

### ISSUE THREAD

**Issue by ctmalan** [circuitikz/circuitikz#580]
`\draw (-1,1) node[op amp](R){};` draws an op amp
`\draw (-1,1) node[ooosource](Q){};` draws nothing

workaround:

`\draw[white] (0,1)to[ooosource,n=Q] (0.5,1);`

**Comment by Rmano** [comment]
User error:

![image](https://user-images.githubusercontent.com/6414907/127176169-cd7fb74b-18a5-4ae4-8dab-fe474b7d4098.png)

`ooosource` is a path-style name, so you have to use:

`\draw (-1,1) node[ooosourceshape](Q){}` ;

**Comment by ctmalan** [comment]
Dear Romano,

I find it difficult to reproduce the following diagram with your suggestion.

[image: image.png]

Here is my current hack:

{\small\centering
\hfill\begin{circuitikz}[scale=0.95]
%\matrix[column sep=1cm,ampersand replacement=\&]{\begin{scope}
 \draw[thick,] (-2,3) to[short,o-o]
(-2,-1)node[anchor=north]{load\textsubscript{A}};
   \draw[thick] (-1,3) to[short,o-o]
(-1,-1)node[anchor=north]{load\textsubscript{B}};
\draw[white] (0,1)to[very thin,ooosource,n=Q] (-0.5,1);

\draw (Q.left)+(0.07,0)node [anchor=east] {\scriptsize$\sum$};
\draw (-1,0)circle [radius=0.25] ++(0.25,0) -| (Q.sec3);
\draw (-2,2)circle [radius=0.25] ++(0.25,0) -| (Q.tert3);
\draw(Q.left) -- (1,1);
{% square watthourmeter a
    \draw (1,1) to [twoport,  name=e, %i_=$\I$,
    t=\shortstack{{$E_\text{sum}$}\\~\\\si{VAh}} ] ++(1,0);
    \draw[very thick] (e.west) -- (e.east);
    \comment{%link
    \draw ($(e.north)+(0,0.125)$) -- ($(e.center)+(0,+0.75)$) -|
    ($(e.center)+(-1.5,0.0)$) to[short, -o] ++(0,-2);
      }
    \draw [thick] (e.north east) -- ++(0,0.125) -| (e.north west);
    \comment{\draw (e.south) -- ($(e.center)-(0,1)$)-- (2.5,2) to
[short,-*] (2.5,1.5);
% \draw ($(e.center)-(0,2)$) to [open, v^>=$\U$,] ($(e.center)+(-0.75,0)$);
    }}
   %summation
    \draw [dashed, semithick] (2,1) -- ++(0.6,0)
++(0.4,0)circle[,semithick,radius=0.4] node{$\sum$};

\end{circuitikz}\hfill}

**Comment by Rmano** [comment]
Sorry, I can't see your post above correctly. I suspected you answered by mail and often images and formatting is destroyed...

Could you please post a minimal, *complete* example that I can compile?

**Comment by Rmano** [comment]
For example, what is `\comment`?

**Comment by Rmano** [comment]
This is what I have: 

![image](https://user-images.githubusercontent.com/6414907/127520311-517a9924-7471-4a74-80d3-d2cb3efed96d.png)


what should

     \draw[white] (0,1)to[very thin,ooosource,n=Q] (-0.5,1);

do? you can't pass a line width in a `to` command (it is not and `edge`!); and if you draw it in white...

**Comment by Rmano** [comment]
I suspect that you want to put your `ooosourceshape` like that:

```
\documentclass[12pt,a4paper]{article}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage[siunitx]{circuitikz}

\begin{document}
\begin{circuitikz}[scale=0.95]
    \draw[thick,] (-2,3) to[short,o-o]
    (-2,-1) node[anchor=north]{load\textsubscript{A}};
    \draw[thick] (-1,3) to[short,o-o]
    (-1,-1) node[anchor=north]{load\textsubscript{B}};

    \draw[very thin]  (-0.25, 1) node[ooosourceshape, xscale=-1](Q){};

    \draw (Q.left)+(0.07,0)node [anchor=east] {\scriptsize$\sum$};
    \draw (-1,0)circle [radius=0.25] ++(0.25,0) -| (Q.tert3);
    \draw (-2,2)circle [radius=0.25] ++(0.25,0) -| (Q.sec3);
    \draw(Q.left) -- (1,1);

\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/127522108-ef8cee1e-6ed1-4373-8929-49c900f9d218.png)

**Comment by Rmano** [comment]
Exploring the code for this problem I found a bug for the `ooosource` thing --- anchors were wrong when using `sources/scale`, see #581

**Comment by ctmalan** [comment]
Dear Romano,

Thanks for solving this!

\newcommand{\comment}[1]{%
}%
\newcommand{\uncomment}[1]{#1%
}%

I use this for debugging, much better than \usepackage{comment}.

Kind regards,

c-:
