### ISSUE TITLE
Arrows of variable capacitors and inductors

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#585]
How to change the arrow type to ```-Triangle 60``` for a ```variable capacitor```? 

The method mentioned for resistors: ```tunable end arrow={Stealth[red]}``` does not seem to work.

**Comment by Rmano** [comment]
This:

```latex
\documentclass[tikz,border=3.14]{standalone}
\usepackage{circuitikz}

\begin{document}
\begin{tikzpicture}[]
    \draw (0,2) node{\pgfcircversion};
    \draw (0,1) to[vC] ++(3,0);
    \ctikzset{tunable end arrow={Triangle[angle=60:6pt]}}
    \draw (0,0) to[vC] ++(3,0);
\end{tikzpicture}
\end{document}
```

gives here:

![image](https://user-images.githubusercontent.com/6414907/136663887-c6f2ade9-13f4-453b-970b-994053db091e.png)

**Comment by Rmano** [comment]
I will close this --- re-open if you have a failing example!
