### ISSUE TITLE
Can't  move straight voltage arrows away from european resistor

### ISSUE THREAD

**Issue by Filip62** [circuitikz/circuitikz#601]
Hi, I would like to know if it's possible to put more distance between the resistor and the voltage arrow, in order to fit both the label and the arrow on one side.

I've tried different `\ctikzset` commands but none of them achieved this.

Thank You.

![image](https://user-images.githubusercontent.com/58399088/145380258-73b36bb3-911f-447e-89ca-98407bd54a95.png)

```
\documentclass{article}

\usepackage[european, straightvoltages]{circuitikz}

\begin{document}
    Plotted using Ti\emph{k}Z version \pgfversion{} and CircuiTi\emph{k}Z version \pgfcircversion{}.
    
    \begin{circuitikz}
        \draw (0,0) to [R,l={$R_1$},i={$I_1$},v^={$U_1$}] (4,0);
    \end{circuitikz}
    
\end{document}
```

**Comment by Rmano** [comment]
You can, using `voltage shift` (see https://texdoc.org/serve/circuitikz/0#subsubsection.5.5.5 )

```latex
\documentclass{article}

\usepackage[european, straightvoltages]{circuitikz}

\begin{document}
    Plotted using Ti\emph{k}Z version \pgfversion{} and CircuiTi\emph{k}Z version \pgfcircversion{}.

    \bigskip
    
    \begin{circuitikz}
        \draw (0,0) to [R,l={$R_1$},i={$I_1$},v^={$U_1$}, voltage shift=4] (4,0);
    \end{circuitikz}
    
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/145427933-1b534143-9dda-4c27-9f08-b842e95ff60e.png)

*PD these kinds of questions are better asked at https://tex.stackexchange.com/questions/tagged/circuitikz --- you can have your answer in minutes ;-)*

**Comment by Filip62** [comment]
I have no clue how was I able to miss that.

Thank You.

**Comment by Rmano** [comment]
You're welcome! No worries... ;-)
