### ISSUE TITLE
overlay option causes TL not to be drawn

### ISSUE THREAD

**Issue by schtandard** [circuitikz/circuitikz#604]
When using the `overlay` option, the transmission line shape is not drawn.
```latex
\documentclass{article}

\usepackage{circuitikz}

\begin{document}

\begin{circuitikz}
  \draw (0,0) to [TL] (2,0);
\end{circuitikz}

\begin{circuitikz} [overlay]
  \draw (0,0) to [TL] (2,0);
\end{circuitikz}

\end{document}
```
![image](https://user-images.githubusercontent.com/23075534/150973526-4fb9a86f-1ce8-4cad-ac89-3552a6afb504.png)

([Related tex.sx question](https://tex.stackexchange.com/q/631395/48973))

**Comment by Rmano** [comment]
This is also related, seems the same cause: https://tex.stackexchange.com/questions/577822/tikz-transparency-group-breaks-with-overlay
