### ISSUE TITLE
Entry arrow inconsistent

### ISSUE THREAD

**Issue by lapreindl** [circuitikz/circuitikz#613]
Hi,
input arrow inconsistent at `[>]` and `[inputarrow]` ... is it wanted? If I want consistency in my document I'll just use `[inputarrow]`, but if there's an easier way ...

regards, Laurenz

see this example

(A)
```
\begin{circuitikz}
\draw
    (0,0) node(in){}
    (in) to ++(1,0) to [twoport, t={$\frac{k_\mathrm{I}}{s}$},>] ++(1,0) to ++(1,0) to [twoport, t={$\frac{1}{1+sT_1}$},>] ++(1,0) to ++(1,0) node[inputarrow]{}
;
\end{circuitikz}
```

(B)
```
\begin{circuitikz}
\draw
    (0,0) node(in){}
    (in) to ++(1,0) to [twoport, t={$\frac{k_\mathrm{I}}{s}$},name=A] ++(1,0) to ++(1,0) to [twoport, t={$\frac{1}{1+sT_1}$},name=B] ++(1,0) to ++(1,0) node[inputarrow]{}
    (A.w) node[inputarrow]{}
    (B.w) node[inputarrow]{}
;
\end{circuitikz}
```
(A)
![a1](https://user-images.githubusercontent.com/58363590/156318600-9c4e9229-3dd2-477a-8c7f-b57174e0588e.png)

(B)
![b1](https://user-images.githubusercontent.com/58363590/156318602-9e367363-9a3f-4676-ad71-21fbab0a1d78.png)

**Comment by Rmano** [comment]
I have an (experimental, I have to study it a bit) patch to fix it, in PR #614, but I have to ponder it a bit more --- the shift was there for a lot of time, and a reason for it must exist. 

Notice however that you have to take care the imperfection on the last (output) arrow by yourself, like this:

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{tikzpicture}[]
 \draw
    (0,0) node(in){}
    (in) -- ++(1,0) to [twoport, t={$\frac{k_\mathrm{I}}{s}$},>,name=A] ++(1,0) 
    -- ++(1,0) node[inputarrow, anchor=west]{};
    \draw [color=red, opacity=0.3] ([yshift=3mm]A.w) node[inputarrow]{};
\end{tikzpicture}
\end{document}
```

This is the output with the patch applied (should apply also to 1.4.6, but I do not guarantee it...)

![image](https://user-images.githubusercontent.com/6414907/156330019-82bb5bef-c752-4456-af33-5f53b079a231.png)
