### ISSUE TITLE
add multi port transformer

### ISSUE THREAD

**Issue by AndreaDiPietro92** [circuitikz/circuitikz#618]
It could be very useful the introduction of multiport transformer, where we have one (o more) primary winding e two (o more) secondary winding (even 1 primary and 2 secondary will be very useful).
example:
https://www.electronics-tutorials.ws/wp-content/uploads/2018/05/transformer-trans59.gif

Thanks.

**Comment by Rmano** [comment]
Hmmm. There are zillions of possible combinations. I would go the subcircuit way in this case, or just drawing it with inductances.

**Comment by Rmano** [comment]
To ease the drawing of such thing, what probably can be done is to add anchors to normal L that are at the same positions as transformers' "dot" anchors are....

![image](https://user-images.githubusercontent.com/6414907/160797894-fff12ee6-b622-4706-b907-af99410d32ca.png)

...what do you think?

**Comment by AndreaDiPietro92** [comment]
This could be very useful. If you can find a solution for the positioning of the "core" (the two parallel lines) between two inductors the problem would be solved.

**Comment by Rmano** [comment]
> This could be very useful. If you can find a solution for the positioning of the "core" (the two parallel lines) between two inductors the problem would be solved.

This is easily done with plain Ti*k*Z: 

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{circuitikz}
\begin{document}
\begin{tikzpicture}
    \draw (0,3) -- ++(1,0) to[L, name=L1] ++(0,-2) -- ++(-1,0);
    \draw (0,0) -- ++(1,0) to[L, name=L2] ++(0,-2) -- ++(-1,0);
    \draw (3,1.5) -- ++(-1,0) to[L, name=L3] ++(0,-2) -- ++(1,0);
    \coordinate (x at center) at ($(L1.center)!0.5!(L3.center)$); % we will use just the x part
    \draw [thick, double,double distance=4pt]  (x at center|-L1.left) -- (x at center|-L2.right);
\end{tikzpicture}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/160807794-a64dd610-9fc7-45a1-baf9-cb4a908a0e35.png)

**Comment by Rmano** [comment]
...and really, also the whole thing is not-so-difficult...

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{circuitikz}
\begin{document}
\begin{tikzpicture}
    \draw (0,3) -- ++(1,0) to[L, name=L1] ++(0,-2) -- ++(-1,0);
    \draw (0,0) -- ++(1,0) to[L, name=L2] ++(0,-2) -- ++(-1,0);
    \draw (3,1.5) -- ++(-1,0) to[L, name=L3] ++(0,-2) -- ++(1,0);
    \coordinate (x at center) at ($(L1.center)!0.5!(L3.center)$); % we will use just the x part
    \draw [thick, double,double distance=4pt]  ([yshift=1cm]x at center|-L1.left) -- ([yshift=-1cm]x at center|-L2.right);
    \draw (L1.left) ++(-0.3,0) node[circ]{};
    \draw (L2.right) ++(-0.3,0) node[circ]{};
    \draw (L3.left) ++(0.3,0) node[circ]{};
\end{tikzpicture}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/160808633-e0493d82-13ce-4bf4-8909-57bfbf299967.png)

**Comment by AndreaDiPietro92** [comment]
I think that this is the best solution for my problem..

**Comment by AndreaDiPietro92** [comment]
Will be in the next release the extra anchors in the inductor?

**Comment by Rmano** [comment]
> Will be in the next release the extra anchors in the inductor?

Yes --- see the linked PR #625
