### ISSUE TITLE
Battery changed behavior

### ISSUE THREAD

**Issue by 25pi** [circuitikz/circuitikz#62]
Hello,
in the version shipped with texlive 2016 (version 0.7 2016-09-08) the battery symbol changed orientation with respect to previous versions and now is reversed.
Best.
P.

\documentclass{standalone}
\usepackage{tikz}
\usepackage{circuitikz}
\begin{document}
\begin{circuitikz}[american voltages]
\draw (0,0) to[battery1,v=$V$] (0,2);
\end{circuitikz}
\end{document}
![test](https://cloud.githubusercontent.com/assets/26439279/23957796/84939e02-09a0-11e7-86ba-3181cd4f966e.png)

**Comment by sistlind** [comment]
This is the intended behaviour:
the longer line is the positive edge and by default the starting point of the path is the higher potential=+, which is here at the bottom
