### ISSUE TITLE
Request for German Mixer Types

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#621]
This would be the mixer symbol according DIN and EN:

<img width="500" alt="Bildschirmfoto 2022-04-07 um 17 11 45" src="https://user-images.githubusercontent.com/1970554/162232780-de3c5c1b-6ac0-4395-bcac-06b82bae5352.png">

Howes in Germany also this variant (similar to the boxed mixer, but without circle) is used:

<img width="120" alt="image" src="https://user-images.githubusercontent.com/1970554/162232940-3ca4813d-9ae7-41a5-b860-cb1a196c8bd6.png">

Would it be possible to integrate both?

**Comment by Rmano** [comment]
Hi! These components (like the antenna in #620) are quite easy to draw with the existing ones... I will see if I can add them, anyway, but I am quite busy now...

**Comment by Rmano** [comment]
I have added the "no-circle" option for the boxed mixer (and similar components). 

I am not sure about the other symbol --- it does not fit with the blocks; they have one input and one output, and the symbol you shows seems to have three inputs (even if the symbol shows 4). 

![image](https://user-images.githubusercontent.com/6414907/163802824-259ded78-9b5b-44fb-8a7c-29b23bfa63e1.png)

Maybe you can have a mixer of that style painting over a generic fourport (which can easily added as a macro or as a subcircuit):

```latex
\documentclass[border=10pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{circuitikz}
\begin{document}
\begin{circuitikz}
    \node [fourport](A){};
    \coordinate (lA) at ($(A.west)!0.3!(A.center)$);
    \coordinate (mA) at ($(A.west)!0.6!(A.center)$);
    \coordinate (eA) at ($(A.east)!0.3!(A.center)$);
    \draw (A.port1 -| lA) -- (mA) (A.port4 -| lA) -- (mA) -- (eA);
    \draw (A.port1) -- ++(-1,0);
    \draw (A.port4) -- ++(-1,0);
    \draw (A.east) -- ++(1,0);
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/163803693-912ded25-7b80-47f0-9dd8-13837d4c5650.png)
