### ISSUE TITLE
bipoles has a line in the middle with the latest version of circuitikz 

### ISSUE THREAD

**Issue by lemosluthier** [circuitikz/circuitikz#64]
```
\documentclass{minimal}
\usepackage{circuitikz}

\begin{document}
	\begin{circuitikz}				
	\draw (0,0)	node[](A){};
	\draw (0,3)	node[](B){};
	\draw (A)	to[R=$R_1$](B);	
\end{circuitikz}
\end{document}
```
with 2016 version it was no happening
![line](https://cloud.githubusercontent.com/assets/3891455/24298212/0d80bdaa-1084-11e7-92a9-8793d1b9d3ac.png)

¿How Can i solve this?

**Comment by sistlind** [comment]
Hi,
this is a very strange Bug. Temporarily you can comment this line:
https://github.com/circuitikz/circuitikz/blob/master/tex/pgfcircpath.tex#L74

Or write \draw (A) to[R]($(B)+(0,0$);

This happens only, is a node is used as target coordinate, i will have a look at this at the weekend.

Best regards,
Stefan
