### ISSUE TITLE
[Feature] option to remove excess wire from the op-amp

### ISSUE THREAD

**Issue by erwindenboer** [circuitikz/circuitikz#645]
**Is your feature request related to a problem? Please describe.**
Hello, I want to use circuitikz for a converting program. For this, I need to change something in the lay-out of components. The component is the op-amp. For now, when I use the op-amp I automatically get the excess wires from  the output/+ input/ - input.

**Describe the solution you'd like**
Could you add an option which removes the excess wires coming from the output/+ input/ - input of the op-amp?

**Describe alternatives you've considered**
I have considered accounting the excess wires from the op-amp in my converting program. This means that I need to scale the op-amp. That's a shame in my opinion, because the op-amp provided by circuitikz is a nice formatted component.

**Additional context**
op-amp as is currently by the manual:
![image](https://user-images.githubusercontent.com/31764383/186520861-d547fd6f-2896-42c0-a0be-7f914b95fb69.png)
The change when the requested feature is activated
![image](https://user-images.githubusercontent.com/31764383/186521216-c82e5297-72c7-4d6e-82d7-d9718340b099.png)

**Comment by Rmano** [comment]
Yes, having an option to change the length of the pins would be nice (like in newer components). Unfortunately,  those are quite old ones and it is not easy to patch them, and I have little time now. But I promise I'll look into it. 

For now, you can always use a mux/demux component and create a pinless amplifier (but you need to add the symbols plus and minus "by hand").

**Comment by Rmano** [comment]
Anyway, there is a possibility. The pin length is set by the difference between the key `tripoles/op amp/width` (total size, default 1.7) and `tripoles/op amp/port width` (triangle size). So you can do this: 

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{tikzpicture}[]
    \draw (0,0) node[op amp](A){}
        (A.out) node[red,circ]{} (A.+) node[blue, circ]{};
    \ctikzset{tripoles/op amp/port width=1, 
        tripoles/op amp/width=1.19, % 1.7*0.7
    }
    \draw (3,0) node[op amp](A){}
        (A.out) node[red,circ]{} (A.+) node[blue, circ]{};
    % too small!
\end{tikzpicture}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/186686229-4f0186e5-d4fc-4d5d-98ad-acbbee819a0a.png)

...to have your op-amp without pins (they are still drawn, but well, they have zero-size). Notice that this is a very old part of the package, so I really had to dig it out. You can find those "internal parameters" looking here: https://github.com/circuitikz/circuitikz/blob/dbc62363d185a63a6d09deae034959fea7e59f98/tex/pgfcirctripoles.tex#L5839-L5845

**Comment by Rmano** [comment]
...so it would be very difficult to change things. Maybe I can provide a documented key to "squeeze out" all the pins in all the amplifiers together, or simply document the current behavior.

**Comment by erwindenboer** [comment]
@Rmano Thanks for your suggestions! I really appreciate your effort to implement this option. For now, the code you have provided is sufficient for me. So please don't rush anything and put your priorities to more important business first ;). In the future, a more slick option can be implemented when the time is right.
