### ISSUE TITLE
Add dots to MOSFETs

### ISSUE THREAD

**Issue by tcpluess** [circuitikz/circuitikz#65]
I would like to have a dot in the MOSFET symbol as shown in the example. Currently is is implemented as follows (see the MOSFET at the top)

![a](https://cloud.githubusercontent.com/assets/16662475/24333273/456b4302-1255-11e7-9e5e-98127d918f67.png)

but the MOSFET symbols (and the other FETs as well) could be updated such that it is possible to add the dot seen here

![b](https://cloud.githubusercontent.com/assets/16662475/24333274/456d0f8e-1255-11e7-9155-d629ae2b85f0.png)

by a configuration option.

**Comment by sistlind** [comment]
This is already included, pls have a look at the doc: "fetsolderdot"

Am 26.03.2017 18:53 schrieb "tcpluess" <notifications@github.com>:
