### ISSUE TITLE
[Bug] Varistor caption cut-off

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#660]
The varistor image gets cut-off in standalone mode:

![image](https://user-images.githubusercontent.com/1970554/201479856-d6552d8b-2859-4a5e-98db-5f519b09104b.png)

```latex
\documentclass[convert=false]{standalone}
\usepackage[straightvoltages, europeanresistors, european inductor]{circuitikz}
\usepackage{tikz}

\begin{document}
    \begin{circuitikz}[european]
        \draw (0,0) to [varistor] (2,0);
    \end{circuitikz}
\end{document}
```

**Comment by Rmano** [comment]
Yes, external labels are not in the component bounding box. This is normal, it happens with more or less all the "internal" text label of `circuititz` (transistors text, for example). 

Normally in complete circuits is not a problem, and it's better not to put the labels into the geographical coordinates to maintain alignment with components with no or different labels. 

If you need the label into the bounding box, just add it manually, like in

```latex
\documentclass[convert=false]{standalone}
\usepackage[straightvoltages, europeanresistors, european inductor]{circuitikz}
\usepackage{tikz}
\begin{document}
    \begin{circuitikz}[european]
        \draw (0,0) to [sR, name=myS] (2,0);
        \node [below left] at(myS.label) {\tiny U};
    \end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/201482627-2a65a10f-594c-4ecf-b5fb-76cc6146a5ec.png)

**Comment by Rmano** [comment]
Or you can manually override the bounding box (this trick is useful in several occasions)

```latex
\documentclass[convert=false]{standalone}
\usepackage[straightvoltages, europeanresistors, european inductor]{circuitikz}
\usepackage{tikz}

\begin{document}
    \begin{circuitikz}[european]
        \path [use as bounding box](0,-0.5) rectangle (2.0,0.5);
        \draw (0,0) to [varistor] (2,0);
    \end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/201483019-e1bb5802-48ee-432f-a85b-ffa4f71de0d5.png)
