### ISSUE TITLE
[Feature] A German Switch

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#662]
![image](https://user-images.githubusercontent.com/1970554/201497701-c02c75ee-2d13-4c3e-ad6d-45502a139917.png)

It would be nice also to have a switch that is a bit greater than the current one and with * at the beginning and the end.

**Comment by Rmano** [comment]
You have it! look at `cute switch customization`:

```latex
\documentclass[margin=2.178mm]{standalone}
\usepackage[RPvoltages]{circuitikz}
\usepackage{tikz}

\begin{document}
    \tikzset{german switch/.style={
        cute open switch, 
        bipoles/cuteswitch/thickness=0.2,
        bipoles/cuteswitch/shape=circ,
    }}
    \begin{circuitikz}[european]
        \draw (0,0) to[battery2] ++(0,3)
            to[german switch] ++(4,0)
            to[R=R] ++(0,-3) -- (0,0);
    \end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/201522033-fc06bfb4-2389-449a-aa71-4b1fd04bccfb.png)

...and if yu want it bigger, add a class scale.
