### ISSUE TITLE
[Feature] Anchorpoint for Variable Resistors

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#663]
It would be also nice to have an anchor point at the beginning of the arrow, like here: 

![image](https://user-images.githubusercontent.com/1970554/201538476-fafe53e3-c5a0-43d6-8635-f8b0cb1c8ef6.png)

The pR hast this, called wiper. But the vR has not ...

**Comment by Rmano** [comment]
Yes, this could be a useful addition. In the meanwhile, you can always add the arrow by hand... ;-)

**Comment by Rmano** [comment]
BTW, the reason the potentiometer has the wiper contact and the variable resistance has not, is because in the first case that is an *electrical* connection, and in the latter it isn't. But the switches have a mid-switch anchor, which is a mechanical one, so... why not? I'll look into it.

**Comment by myzinsky** [comment]
But in many documents you can also see this: 


![](http://www.dieelektronikerseite.de/Pics/Lections/Potentiometer%20-%20Alles%20geregelt%20S06.GIF)

Therefore, it would be nice to have it :-)

**Comment by Rmano** [comment]
I admit I really can't understand that circuit... I suppose P1 is a potentiometer, not a variable resistor. A varistor is, for what I know, a two-terminal device with a knob or a screw head or whatever to change the resistance. I would use a `pR` there, to remove any ambiguity.

**Comment by myzinsky** [comment]
It's often used in Germany:


![](https://www.darc.de/fileadmin/filemounts/referate/ajw/Onlinelehrgang/a16/TJ601.gif)

![](https://www.darc.de/fileadmin/filemounts/referate/ajw/Onlinelehrgang/a16/Bild16-11.gif)

**Comment by Rmano** [comment]
Nice to know. I will add the anchor(s) when I can... (In the middle of a paper submission now, sorry...)
