### ISSUE TITLE
[Feature] Longer Transmission Lines

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#664]
It would be nice to extend the length of a transmission line like in the following picture:

![image](https://user-images.githubusercontent.com/1970554/201538658-585fa3c5-a181-40b3-b0a0-bdaae5a6a0cf.png)

**Comment by Rmano** [comment]
You basically can enlarge them, but the shape is deformed. 

```latex
\documentclass[margin=2.178mm]{standalone}
\usepackage[RPvoltages]{circuitikz}
\usepackage{tikz}

\begin{document}
    \begin{circuitikz}[european]
        \draw (0,0) to[TL, bipoles/tline/width=2, l=TL\textsubscript{5}] ++(3,0);
    \end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/201540475-1c190a06-3f6f-4ec4-a071-cf1dc8e44a90.png)

it could probably be fixable, but I am not sure if to want to touch that part of the code. It's an old, legacy one: my personal opinion is that this symbol is not a schematic one, it is more a drawing. An RF schematic is found in the manual, page 122.

![image](https://user-images.githubusercontent.com/6414907/201540606-dd615feb-3b50-41b6-b72b-463ddbdf1589.png)

**Comment by myzinsky** [comment]
Yeah but I think this RF is more for a pcb view... Would be really nice to have a line like this! 

I found this: https://tex.stackexchange.com/questions/402631/draw-transmission-line-circuits maybe it helps? Sorry I'm just a TeX user and not a TeX-Programmer :-D

**Comment by Rmano** [comment]
There is a standard cylinder shape in Ti*k*Z: https://tikz.dev/library-shapes#pgf.cylinder

**Comment by myzinsky** [comment]
Nice, unfortunately, it does not have a connector in the middle of the circle :-( 


![](https://tikz.dev/pgfmanual-images/image-2612.png)

**Comment by Rmano** [comment]
Ah, but that would be just `($(s.before top)!0.5!(s.after top)$)` - you can put that in a macro or in a sub circuit.

**Comment by Rmano** [comment]
...anyway the deformation when changing the width in TL could be thought as a (veeeeery long standing) bug, I'll have a look.

**Comment by afcuttin** [comment]
thanks for the fix!
Nonetheless, the approach of https://tex.stackexchange.com/a/527729/177 would be more preferable, because it stretches the transmission line automatically, rahter than requiring one to adjust bipoles/tline/width with an absolute value.
