### ISSUE TITLE
A question about the alignment of american voltage signs when using other fonts

### ISSUE THREAD

**Issue by EEpchi** [circuitikz/circuitikz#684]
I don't know if this counts as a bug😂, maybe it's the effect of the font package. That is, when I use the package "newtxtext" and "newtxmath" to draw a circuit, the american voltage signs can't well aligned. The "minus" looks like it's moved up a bit. The MWE is shown below. I draw a line using anchor to show their position offset.

![MWE](https://user-images.githubusercontent.com/84228848/211238976-2561bb9f-0dd8-43ce-b977-d6f4e72a478f.jpg)

```
\documentclass{article}
\usepackage{newtxtext}
\usepackage{newtxmath}
\usepackage[americanvoltages]{circuitikz}
\begin{document}
	\begin{circuitikz}[raised voltages]
		\draw (0,0) to[R, v=$v_1$, name=R] ++(2,0);
		\draw[red] (R-Vto) -- (R-Vfrom);
	\end{circuitikz}
\end{document}
```

**Comment by Rmano** [comment]
I think it's a problem with the font, namely the bounding boxes of the chars. Look:

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{newtxtext}
\usepackage{newtxmath}
\begin{document}
\Large \fbox{$+$} \fbox{$-$}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/211357928-80832796-adba-49b5-9859-ed2c3eaedd76.png)

Maybe there is a workaround (I have the sensation I have already seen this somewhere, but I am unable to find the reference).

Anyway, you can cheat:

```latex
\documentclass{article}
\usepackage{newtxtext}
\usepackage{newtxmath}
\usepackage[americanvoltages]{circuitikz}
\ctikzset{voltage/american plus={${+}$}}
\ctikzset{voltage/american minus={$\vphantom{+}-$}}
\begin{document}
	\begin{circuitikz}[raised voltages]
		\draw (0,0) to[R, v=$v_1$, name=R] ++(2,0);
		\draw[red] (R-Vto) -- (R-Vfrom);
	\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/211359121-512d9092-ca42-4bb3-b3b7-3f00395b1cb7.png)

**Comment by Rmano** [comment]
Ah, I found it:

https://tex.stackexchange.com/questions/609201/circuitikz-american-voltage-signs-not-vertically-aligned-with-unicode-math

**Comment by EEpchi** [comment]
Oh, thank you very much for your answer, which is very helpful to me.🌹
