### ISSUE TITLE
[Feature] Add tail-less mic shape

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#689]
I want to draw such a block diagram: 

![image](https://user-images.githubusercontent.com/1970554/216143211-612de7b2-bfa7-4a84-9083-c264d5bb0740.png)

Right now I'm drawing the mic with a circle. However, I would just use micshape. However, the micshape has the connection lines attached to the shape. However, the loudspeakershape does not! It would be nice if mic and loudspeaker could have the same behaviour. Any thoughts?

**Comment by Rmano** [comment]
Yep, it could be a worthwhile addition to the block thing.

Would you try a shot at it? I do have not a lot of time now, although I use `circuitikz` development to relax a bit...

**Comment by myzinsky** [comment]
I wanted to try it, however, I do not even find the micshape in the code :-D Any pointers?

**Comment by Rmano** [comment]
Anchors: 

![image](https://user-images.githubusercontent.com/6414907/216149794-12c1edf4-85c6-430f-a178-768b9fd8f3c0.png)

**Comment by myzinsky** [comment]
Will you bring that to main?

**Comment by Rmano** [comment]
Yes, this weekend I'll add and merge it. I was thinking to add an option to control the thickness of the "bar" independently, in both `mic` and `tlmic`.

**Comment by myzinsky** [comment]
I made also some other block components. Shall I open a pull request for each of them individually? I really want to learn this by myself, since I have a huge project with a lot of custom Building Blocks, mainly from German DIN.

**Comment by Rmano** [comment]
Well, let's try with one or a first group of them, and then when the structure/details are ok, you can do the rest in a block.

One of the problem I have is that `circuitikz` is becoming quite heavy; I have to find a way to create a "sublibraries" system to avoid loading everything all the time. But this is quite a big job, and I do not think I'll be able to tackle that before this summer...

**Comment by Rmano** [comment]
![image](https://user-images.githubusercontent.com/6414907/216573381-bd9cfc49-2b71-4c2c-8818-316566db6387.png)

**Comment by myzinsky** [comment]
Question, when will this be available in the CPAN tex?

**Comment by Rmano** [comment]
CTAN? Yes, as soon as I make a release... I had *almost* done one last weekend; then things started coming in. 😉

As soon as things calm down a bit, I'll make a release.
