### ISSUE TITLE
[Feature] Correct Anchors for TL 

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#694]
As you know, I'm using a lot of transmission lines: 

<img width="216" alt="image" src="https://user-images.githubusercontent.com/1970554/216841072-4124b1c3-bac5-4580-b88d-bb72fbd2fde0.png">

Sometimes I have to connect things to south west and south east. However, it connects to the rectangular boarding box. 

I tried to overwrite this, however, I know where the \anchor{...} stuff should go (line 417), however, I don't know how to adress the right coordinates:

``` LaTeX
 412 %% Node shapes for RF bipoles%<<<
 413 \ctikzset{bipoles/tline/height/.initial=.3}
 414 \ctikzset{bipoles/tline/width/.initial=.6}
 415
 416 \pgfcircdeclarebipolescaled{RF}
 417 { ###### INSERT ANCHOR STUFF HERE??? ######}
 418 {\ctikzvalof{bipoles/tline/height}}
 419 {tline}
 420 {\ctikzvalof{bipoles/tline/height}}
 421 {\ctikzvalof{bipoles/tline/width}}
 422 {
 423     \pgf@circ@res@step=.4\pgf@circ@res@up % the size of the ellipsis is proportional to the height
 424     \pgfscope
 425         \pgf@circ@setlinewidth{bipoles}{\pgfstartlinewidth}
 426         \pgfpathmoveto{\pgfpoint{\pgf@circ@res@right-\pgf@circ@res@step}{\pgf@circ@res@up}}
 427         \pgfpathlineto{\pgfpoint{\pgf@circ@res@left+\pgf@circ@res@step}{\pgf@circ@res@up}}
 428         \pgfpatharc{-90}{90}{-\pgf@circ@res@step and -\pgf@circ@res@up}
 429         \pgfpathlineto{\pgfpoint{\pgf@circ@res@right-\pgf@circ@res@step}{\pgf@circ@res@down}}
 430         \pgfpatharc{-90}{90}{\pgf@circ@res@step and \pgf@circ@res@up}
 431         \pgf@circ@draworfill
 432         \pgfpathmoveto{\pgfpoint{\pgf@circ@res@right-\pgf@circ@res@step}{\pgf@circ@res@up}}
 433         \pgfpatharc{-90}{90}{-\pgf@circ@res@step and -\pgf@circ@res@up}
 434         \pgfusepath{stroke}
 435     \endpgfscope
 436     \pgfsetlinewidth{\pgfstartlinewidth}
 437     \pgfpathmoveto{\pgfpoint{\pgf@circ@res@right-\pgf@circ@res@step}{0pt}}
 438     \pgfpathlineto{\pgfpoint{\pgf@circ@res@right}{0pt}}
 439     \pgfusepath{stroke}
 440 }
```

any ideas how I could achieve a proper placement, like this: 

<img width="272" alt="image" src="https://user-images.githubusercontent.com/1970554/216841229-804d7aa4-dd1e-433f-b88c-b33ad801c140.png">

**Comment by Rmano** [comment]
Like those?

![image](https://user-images.githubusercontent.com/6414907/216842339-79ffe5f6-0b13-4c05-9192-7815df4086e0.png)

```
\makeatletter
\pgfcircdeclarebipolescaled{RF}
{
    \anchor{center right}{\northeast \advance\pgf@x by -0.4\pgf@y\pgf@y=0pt}
    \anchor{top right}{\northeast \advance\pgf@x by -0.4\pgf@y}
    \anchor{bottom right}{\northeast \advance\pgf@x by -0.4\pgf@y\pgf@y=-\pgf@y}
    \anchor{center left}{\northeast \advance\pgf@x by -0.4\pgf@y\pgf@x=-\pgf@x\pgf@y=0pt}
    \anchor{top left}{\northeast \advance\pgf@x by -0.4\pgf@y\pgf@x=-\pgf@x}
    \anchor{bottom left}{\northeast \advance\pgf@x by -0.4\pgf@y\pgf@x=-\pgf@x\pgf@y=-\pgf@y}
}
{\ctikzvalof{bipoles/tline/height}}
{tline}
{\ctikzvalof{bipoles/tline/height}}
{\ctikzvalof{bipoles/tline/width}}
{
    \pgf@circ@res@step=.4\pgf@circ@res@up % the size of the ellipsis is proportional to the height
    \pgfscope
        \pgf@circ@setlinewidth{bipoles}{\pgfstartlinewidth}
        \pgfpathmoveto{\pgfpoint{\pgf@circ@res@right-\pgf@circ@res@step}{\pgf@circ@res@up}}
        \pgfpathlineto{\pgfpoint{\pgf@circ@res@left+\pgf@circ@res@step}{\pgf@circ@res@up}}
        \pgfpatharc{-90}{90}{-\pgf@circ@res@step and -\pgf@circ@res@up}
        \pgfpathlineto{\pgfpoint{\pgf@circ@res@right-\pgf@circ@res@step}{\pgf@circ@res@down}}
        \pgfpatharc{-90}{90}{\pgf@circ@res@step and \pgf@circ@res@up}
        \pgf@circ@draworfill
        \pgfpathmoveto{\pgfpoint{\pgf@circ@res@right-\pgf@circ@res@step}{\pgf@circ@res@up}}
        \pgfpatharc{-90}{90}{-\pgf@circ@res@step and -\pgf@circ@res@up}
        \pgfusepath{stroke}
    \endpgfscope
    \pgfsetlinewidth{\pgfstartlinewidth}
    \pgfpathmoveto{\pgfpoint{\pgf@circ@res@right-\pgf@circ@res@step}{0pt}}
    \pgfpathlineto{\pgfpoint{\pgf@circ@res@right}{0pt}}
    \pgfusepath{stroke}
}
\makeatother
```

**Comment by Rmano** [comment]
...and probably something like that should be added for the `tlinestub`...

**Comment by Rmano** [comment]
...and by the way, `tlinestub` has wrong anchors since... well, forever, and nobody noticed...

![image](https://user-images.githubusercontent.com/6414907/216846851-7fc5d065-6d50-4cbf-8174-06913eaedab2.png)

**Comment by myzinsky** [comment]
I did ... I also would need it in the other direction, will post a picture tomorrow

**Comment by Rmano** [comment]
`xscale= -1` ?

**Comment by myzinsky** [comment]
No, just the flat end without connection, and the connection hidden behind...

**Comment by Rmano** [comment]
Ah, yes, I see... Anyway, the stub code is beyond salvation, probably the only way out is to add two "stubs" with correct anchors and with the same size parameters (height mainly, and the ellipse shape).

**Comment by Rmano** [comment]
@myzinsky  ...and what about an option to *not* draw the short line on `tline`? That should solve everything with a couple of styles (rotating and mirroring, basically) with a lot of flexibility.

**Comment by myzinsky** [comment]
Yes that would help a lot! Or just a parameter to normal tline, and I could use tlineshape 🤓

**Comment by Rmano** [comment]
> Yes that would help a lot! Or just a parameter to normal tline, and I could use tlineshape nerd_face

Yes, this would be ok I think. I'll give it a shot. The only trick would be to move the `left` anchor to `center left` when the wire is not drawn, but that should be straightforward...

**Comment by Rmano** [comment]
![image](https://user-images.githubusercontent.com/6414907/216951538-e5cdb1cd-ea90-4c69-8653-72f986436f54.png)

**Comment by myzinsky** [comment]
Exactly that What I need. It works charming. Will that be part of the next release too?

**Comment by Rmano** [comment]
> Exactly that What I need. It works charming. Will that be part of the next release too?

Yes!

**Comment by Rmano** [comment]
After merging this, I have only #693  pending before releasing 1.6.1 --- do you prefer to let it for the next release?
