### ISSUE TITLE
Alternative VarCap Style

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#697]
<img width="149" alt="image" src="https://user-images.githubusercontent.com/1970554/218254020-16c72e91-65f3-452a-9700-21e8817ffd6d.png">

It would be nice to have this alternative varcap symbol. I tried to do it by myself, but there are very many ??? in the LED implementations. Would it make sense to take the base LED shape and base C shape and combine that?

**Comment by Rmano** [comment]
Hmm. Why don't you use a subcircuit? Should be easy for this one.

**Comment by Rmano** [comment]
```latex
\documentclass[border=10pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{circuitikz}

\begin{document}
\begin{tikzpicture}[stroke diodes, 
    mini c/.style={C, capacitors/scale=0.3}]
    \draw (0,0) to[D=$D_3$, name=d] ++(0,2) (d.se) 
        ++(0.2,0) to[mini c] ++(0,-.3);
\end{tikzpicture}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/218412386-81a362f2-8a2a-415b-bc73-a575b0ff9229.png)

**Comment by Rmano** [comment]
I will close this for now; I think it's not worth adding a shape for this (it's simple to add a macro or a subcircuit). Please feel free to re-open if needed.
