### ISSUE TITLE
[Bug] Rendering issue for wire to ground connection

### ISSUE THREAD

**Issue by hugolundin** [circuitikz/circuitikz#701]
**Describe the bug**

When adding a ground node and a wire connecting to it, the rendered pdf has minor offsets in the connection between the wires. See image below.

**To Reproduce**

```latex
\documentclass{article}
\usepackage[arrowmos,american,siunitx]{circuitikz}
\ctikzset{tripoles/pmos style/nocircle}

\begin{document}
    Circuitikz: \pgfcircversion{} (\pgfcircversiondate)\par
    Ti\emph{k}Z: \pgfversion{} (\pgfversiondate)\par\bigskip
    
    \begin{circuitikz}[]
        \draw (2, 2) node[nmos](M1){};
        \draw (M1.G) -- (0, 2) to[V=$\si{\volt}$] (0, 0) node[ground]{};
        \draw (M1.S) -- (2,0) node[ground]{};
        \draw (M1.D) -- ++(2,0) -- (4, 0) node[ground]{};
    \end{circuitikz}
\end{document}
```
**Screenshots**

<img width="408" alt="Screenshot 2023-02-22 at 08 16 57" src="https://user-images.githubusercontent.com/9110669/220549657-ef7ce4e1-7433-4fa8-a7db-cd7128d6fa86.png">

<img width="57" alt="Screenshot 2023-02-22 at 08 18 33" src="https://user-images.githubusercontent.com/9110669/220550047-d26dcb7e-0029-444a-ba68-5c37074adfc5.png">

**Operating system, LaTeX distribution**

pdflatex with Overleaf

**Expected behavior**

I expect wires to be connected properly without the offset.

**Comment by Rmano** [comment]
Try to zoom in/out and print it. In `okular`, at 400%:

![image](https://user-images.githubusercontent.com/6414907/220567281-048b7212-4d4f-488d-a1eb-f1ac36c58817.png)

This is a classic antialiasing problem in a lot of PDF renderers (you can spot it here too, the last line of the ground symbol seems smaller) . To my knowledge, there is nothing we can do on the Ti*k*Z side... 

Look at the same `okular` with 33%:

![image](https://user-images.githubusercontent.com/6414907/220568462-f893234e-f436-4a67-b94d-b4c2e8b5b91c.png)

Or (good) `envince` at 100% with 98 dpi display:

![image](https://user-images.githubusercontent.com/6414907/220568803-d4794663-1ca2-4263-af00-b30c92f2801b.png)

**Comment by Rmano** [comment]
And on overleaf, zoomed in:

![image](https://user-images.githubusercontent.com/6414907/220573187-7fd55f77-f55d-43cc-a83e-535ac3a7a46e.png)

**Comment by Rmano** [comment]
Please reopen if you still think is a bug.
