### ISSUE TITLE
Add style to transformer core lines

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#702]
How can I change the style of the core of a transformer? Specifically: I want to dash the double line.

**Comment by Rmano** [comment]
Not really a bug; it's just not provided... so you can do an enhancement request. The lines are drawn here:

https://github.com/circuitikz/circuitikz/blob/ff0ccf13b25d9fd73fb8715fb3124018f0bce1e2/tex/pgfcircquadpoles.tex#L291-L325

And maybe something like https://github.com/circuitikz/circuitikz/commit/bef3898ee6beee7bc83b221c12a5ec5ed8b87e07 can be added to the core line drawing should be easy enough. No time now, but I can see it as soon as I have a free spot...
