### ISSUE TITLE
[New Component] Clock wedge component

### ISSUE THREAD

**Issue by Mario1159** [circuitikz/circuitikz#705]
It would be useful to have a clock wedge component to able to implement clocked custom digital blocks such as this example:

![image](https://user-images.githubusercontent.com/24532325/229219753-a2916c82-25c7-4235-9502-d2b3ab02fae8.png)

This block could be done similar to the 555 example in section 4.24.5 "Mux-Demux special usage" but it needs a clock wedge symbol which could be similar to the signal ground node but tailless.

As far I know the only component that can have the clock wedge symbol are flip flops but they are restricted in pins.

**Comment by Rmano** [comment]
Yes, it could be useful (although it is pretty trivial to add manually...). I'll add it to the list of things nice to do 😉 — I have little time now and `context` new version created a big disruption...

**Comment by Rmano** [comment]
For example, you can use this: 

```latex
\documentclass[border=2.72mm,preview]{standalone}
\usepackage{circuitikz}
\begin{document}
\newcommand{\wedgedown}{+(-0.15,0) -- +(0,-0.15) -- +(0.15,0)}
\begin{circuitikz}
    \node [muxdemux, muxdemux def={Lh=3, Rh=3, NT=2}](A) at (0,0){};
    \draw (A.btpin 1) \wedgedown;
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/229579410-adce2d7b-de41-4d41-a01f-2e9415bdf24b.png)

**Comment by Rmano** [comment]
It is quite complex to define a shape that always has the same size as the wedge in flip-flops, so I am not sure if it's worth it...
