### ISSUE TITLE
[Bug] Changing from deprecated pC to eC gives wrong orientation

### ISSUE THREAD

**Issue by zarniwhoop73** [circuitikz/circuitikz#713]
**Describe the bug**
~Using the mosfet amplifier circuit from http://www.texample.net/tikz/examples/mosfet/ with texlive2023 I noticed that pc is deprecated. But changing tthe pC to eC inverts their polarity

\documentclass[margin=10pt]{standalone}
%%%<
\usepackage{verbatim}
%%%>
\begin{comment}
:Title: 18W MOSFET amplifier with npn transistor
:Tags: Circuits;circuitikz;Electrical engineering
:Author: Ramón Jaramillo
:Slug: mosfet

This example make use of the circuitikz and siunitx packages for drawing
a 18W MOSFET  Amplifier for one-channel. You need to have those packages
installed for compiling.

Truncated after the pC
Source: http://www.circuitstoday.com/mosfet-amplifier-circuits
\end{comment}
\usepackage[siunitx]{circuitikz}
\begin{document}
\begin{tikzpicture}[scale=2]
  \draw[color=black, thick]
    (0,0) to [short,o-] (6,0){} % Baseline for connection to ground
    % Input and ground
    (0,1) node[]{\large{\textbf{INPUT}}}
    % Connection of passive components
    (5,0) node[ground]{} node[circ](4.5,0){}
    (0,2) to [pC, l=$C_1$, o-] (0.5,2)
    to [R,l=$R_1$,](1.5,2)
    to node[short]{}(2.6,2)
    (1.5,2) to [C, l=$C_2$, *-] (1.5,3) -| (5,3)
    (2.2,2) to [R, l=$R_2$, *-*] (2.2,3)
    (2.2,3) to [pC, l=$C_3$, *-] (2.2,5) -| (3,5)
    ;
\end{tikzpicture}
\end{document}

**Comment - capacitor C3 in the truncated example has positive at top, negative at bottom.
But changing pC to eC as follows puts positive at the bottom of C3.**

% 18W MOSFET amplifier, with npn transistor.
% Author: Ramón Jaramillo.
% http://www.texample.net/tikz/examples/mosfet/
\documentclass[margin=10pt]{standalone}
%%%<
\usepackage{verbatim}
%%%>
\begin{comment}
:Title: 18W MOSFET amplifier with npn transistor
:Tags: Circuits;circuitikz;Electrical engineering
:Author: Ramón Jaramillo
:Slug: mosfet

This example make use of the circuitikz and siunitx packages for drawing
a 18W MOSFET  Amplifier for one-channel. You need to have those packages
installed for compiling.

Source: http://www.circuitstoday.com/mosfet-amplifier-circuits
\end{comment}
\usepackage[siunitx]{circuitikz}
\begin{document}
\begin{tikzpicture}[scale=2]
  \draw[color=black, thick]
    (0,0) to [short,o-] (6,0){} % Baseline for connection to ground
    % Input and ground
    (0,1) node[]{\large{\textbf{INPUT}}}
    % Connection of passive components
    (5,0) node[ground]{} node[circ](4.5,0){}
    (0,2) to [eC, l=$C_1$, o-] (0.5,2)
    to [R,l=$R_1$,](1.5,2)
    to node[short]{}(2.6,2)
    (1.5,2) to [C, l=$C_2$, *-] (1.5,3) -| (5,3)
    (2.2,2) to [R, l=$R_2$, *-*] (2.2,3)
    (2.2,3) to [eC, l=$C_3$, *-] (2.2,5) -| (3,5)
    ;
\end{tikzpicture}
\end{document}

```
**Screenshots**
If applicable, add a screenshot of the result to help explain your problem.

**Operating system, LaTeX distribution**

Beyond Linuxfromscratch, texlive-20230313-source

pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023 - BLFS)
kpathsea version 6.3.5
Copyright 2023 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04


**Expected behavior**
A clear and concise description of what you expected to happen.

Polarity of electrolytic capacitor should match polarity of curved capacitor.

**Comment by Rmano** [comment]
No, the problem is that the *old* `pC` (polar capacitor) component did not match  the polarity with the `eC` (elko) component --- way before I took the maintenance of the package. I **can't** change the polarity of the `pC` component because, as you noticed, it would break all old circuits drawn taking into account that "feature". 

So I deprecated and hid `pC`, and added a new `cC` (curved capacitor) which does match the `eC` polarity. In new designs, you use it and be happy. Old circuits will compile correctly.

You have more rationale and the history of the thing here: https://tex.stackexchange.com/questions/509594/polar-capacitor-orientation-in-circuitikz-seems-wrong

BTW, please care for the format of the issue; it's all messed up and difficult to read.

**Comment by zarniwhoop73** [comment]
Sorry about the format, I pasted, did not get a preview (unlike with comments). For some reason I have '%%%>' and similar before and after one line, never noticed that in what I originally copied. Those '%' are legible, the normal % for comments look like ':' when reading it. I suppose that is the markdown parser.
