### ISSUE TITLE
[Bug] Op amp crash document 

### ISSUE THREAD

**Issue by Luk9091** [circuitikz/circuitikz#714]
**Describe the bug**
Cannot use op amp in current project.

**To Reproduce**
```latex
\documentclass{article}

\usepackage[european, american currents, americanvoltages, RPvoltages]{circuitikz}
\usepackage{tikz}

\begin{document}
    \begin{figure}[!h]
        \centering
        \begin{tikzpicture}
            \begin{circuitikz}
                \draw (0, 0) node[op amp](op1){}; % dont work
                % \draw (0, 0) node[plain amp](op1){}; % work
            \end{circuitikz}
        \end{tikzpicture}
    \end{figure}
\end{document}
```
**Screenshots**
![image](https://user-images.githubusercontent.com/42470305/236354298-cb1c3ed2-d902-452d-9dc7-b2a6a3218a08.png)

**Operating system, LaTeX distribution**
Doesnt work on: Overleaf and Ubuntu 22.04  23.04

Ubuntu 23.04
```
pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian)
kpathsea version 6.3.4
Copyright 2022 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04
```

**Expected behavior**
Just draw Op amp

**Comment by Rmano** [comment]
You have nested `tikzpicture`s, which is forbidden. A `circuitikz` environment is the same as a `tikzpicture` one.

Remove either the `\begin{circuitikz}`...`\end{circuitikz}` or the enclosing `\begin{tikzpicture}`...`\end{tikzpicture}`.

Notice that this is not at all related to `circuitikz`... any node there will fail.
