### ISSUE TITLE
[Bug] `|-` cannot close the circuit

### ISSUE THREAD

**Issue by Firestar-Reimu** [circuitikz/circuitikz#717]
**Describe the bug**

`\draw (NA.in 2) to[rmeter, t=mA] ++(-1.5,0) -| (X);` cannot find node `X` and close the circuit

**To Reproduce**
Please add a complete example that shows the problem. You can use the following template (that also
prints the relevant version information); fill the `tikzpicture` environment with your circuit. Please keep it minimal.

```latex
\documentclass{article}
\usepackage{circuitikz}
\begin{document}
\begin{center}
        \begin{circuitikz}
            \ctikzset{logic ports=ieee};
            \draw (0,0) node[ieeestd nand port] (NA) {};
            \draw (NA.north) -- ++(0,0.5) node[vcc]{$+5\,\mathrm{V}$};
            \draw (NA.south) -- ++(0,-1.5) node[ground] (GND) {};
            \draw (GND) ++(0,0.5) to[short, *-] ++(-3,0) node (X) {};
            \draw (NA.in 2) to[rmeter, t=mA] ++(-1.5,0) -| (X);
        \end{circuitikz}
    \end{center}
\end{document}
```
**Screenshots**

![Screenshot_20230513_205527](https://github.com/circuitikz/circuitikz/assets/65082432/2d880adc-115e-420a-8c0e-0d260204288f)

**Operating system, LaTeX distribution**

Archlinux TexLive2023 LuaLatex

**Expected behavior**

The circuit at node `X` should be closed.

**Comment by Rmano** [comment]
Not a bug; sorry, it's a user error. Look at the first FAQ, page 219 of the manual:

![image](https://github.com/circuitikz/circuitikz/assets/6414907/0664281d-b53d-4b35-aa01-e004ec839674)

Change `node (X) {}` (which has a non-zero size) with `coordinate(X)`, and the circuit will be closed correctly.

Have a nice day!

**Comment by Firestar-Reimu** [comment]
Thanks!
