### ISSUE TITLE
[Feature] oosourceshape secondary grounded

### ISSUE THREAD

**Issue by lapreindl** [circuitikz/circuitikz#725]
Hi there,

thank you for your great work!
I have the following feature request:
Sometimes I need to add a secondary neutral node to a switchgear circuit, like
![oosourceshape_with_sec_gnd2](https://github.com/circuitikz/circuitikz/assets/58363590/c74da09a-e43c-49ff-925d-ce7329603d27)

I quickly solved this problem by adding the following to `pgfcircbipoles.tex`
```
\anchor{centersec2}{
    \northeast
    \pgf@y=0pt\relax
    \pgf@x=\ctikzvalof{bipoles/oosourcetrans/circlesize}\pgf@x
}
```
May you can add this as a coordinate or as a fix implemented ground symbol to `wye` and `zig`.

Sorry for my bad English ;-),
Thanks, Laurenz!

**Comment by Rmano** [comment]
Hmmm... if I understand correctly, you are asking for an anchor for the center position of the optional symbol? (Your code works, but a bit due to chance, I fear 😉)

**Comment by lapreindl** [comment]
Thanks,
yeah right, I'm asking for an anchor of the center position of the symbols `wye` and `zig`.

Laurenz

**Comment by Rmano** [comment]
Ok, I'll have a look, and I'll implement them when I have a bit of time.
