### ISSUE TITLE
[Bug] Increasing the AND Symbol in European Style Componets

### ISSUE THREAD

**Issue by sputeanus** [circuitikz/circuitikz#730]
Hey guy,

I am currently trying to draw a European Nand which an scaling of 2 and I realized that the And symbol in the middle is not scaling accordingly.

I already created a workaround but I am curious wheter this is a bug or I did not read the manual properly.

```
\documentclass[english,10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{tikz}
\usepackage{circuitikz}

\begin{document}
	\begin{tikzpicture}[line width=1.5pt]%,font = \huge]
		\ctikzset{
			logic ports/scale=2,
			tripoles/european not symbol=ieee circle,
			tripoles/thickness=1,
			bipoles/thickness=1,
			font=\Huge
		}
	
	% Draw the Nand with AND Symbol
	\draw(0,4cm) node [european nand port] (NAND1) {}
	;
	\draw (NAND1.out) to [european resistor, l=$R$] ++(3cm,0)
	;

	
	% Draw the Nand with big AND symbol workaround
	\draw(0,0) node [european nand port] (NAND2) {\colorbox{white}{\&}}
	;
	\draw (NAND2.out) to [european resistor, l=$R$] ++(3cm,0)
	;

	\end{tikzpicture}
\end{document}
```

![grafik](https://github.com/circuitikz/circuitikz/assets/117989161/388ace86-673c-406d-937f-915c4b3f74af)

Thanks for your help!
Simon

**Comment by sputeanus** [comment]
Ahh and maybe just another question.

Is it true that I can just change the width of the american logic ports but not the width of european logic ports?
When I use

tripoles/european nand port/port width=.4
instead of 
tripoles/american nand port/port width=.4

I get an error message that he does not know the key

**Comment by Rmano** [comment]
Indeed, I didn't give the European ports a lot of love. They were (re-)implemented by John Kormylo to add multiple inputs, and I just added them to the class mechanism and made changes to implement the various "not" markers...

For the first question, it's true that the font is fixed at the standard size. I missed it when adding the scaling, but on the other side, generally, scaling fonts is not advisable. So my proposal is to add an option to set the font. In the following code, you have a temporary code that is doing the same, just as a stopgap solution.

The problem with the width is that the parameter's name is different. Maybe a should add a "class" meta-parameter for it... 

```latex
\documentclass[english,10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{babel}
% \usepackage{tikz}
\usepackage{circuitikz}

% new font parameter, start code
\usepackage{etoolbox}
\makeatletter
\ctikzset{tripoles/european port font/.initial={}}
%% patch the internal command to add the options
\patchcmd{\pgfcircdeclareeurologicport}%
    {\pgftext{#2}}%
    {\pgftext{\ctikzvalof{tripoles/european port font}#2}}%
    {\relax}{\ERRORPACHING}
%% redeclare the ports
\pgfcircdeclareeurologicport{and}{\&}{\pgf@circ@res@count}{}
\pgfcircdeclareeurologicport{or}{$\ge 1$}{\pgf@circ@res@count}{}
\pgfcircdeclareeurologicport{xor}{$=1$}{\pgf@circ@res@count}{}
\pgfcircdeclareeurologicport{not}{$1$}{1}{not}
\pgfcircdeclareeurologicport{buffer}{$1$}{1}{}
\pgfcircdeclareeurologicport{nand}{\&}{\pgf@circ@res@count}{not}
\pgfcircdeclareeurologicport{nor}{$\ge 1$}{\pgf@circ@res@count}{not}
\pgfcircdeclareeurologicport{xnor}{$=1$}{\pgf@circ@res@count}{not}
\makeatother
% end font parameter code

\begin{document}
\begin{tikzpicture}[line width=1.5pt]%,font = \huge]
    \ctikzset{
        logic ports/scale=2,
        tripoles/european not symbol=ieee circle,
        tripoles/thickness=1,
        bipoles/thickness=1,
        % font=\Huge not used
    }

    % Draw the Nand with AND Symbol
    \draw(0,4cm) node [european nand port,
        circuitikz/tripoles/european nand port/width=2.2] (NAND1) {}
        ;
    \draw (NAND1.out) to [european resistor, l=$R$] ++(3cm,0)
        ;

    % Draw the Nand with big AND symbol workaround
    \ctikzset{tripoles/european port font=\Huge}
    \draw(0,0) node [european nand port] (NAND2) {}
        ;
    \draw (NAND2.out) to [european resistor, l=$R$] ++(3cm,0)
        ;

\end{tikzpicture}
\end{document}
```

![image](https://github.com/circuitikz/circuitikz/assets/6414907/f595d4df-28e4-4057-957a-0c9537de248a)

**Comment by Rmano** [comment]
Hmmm... but yes, there is something pesky about the width --- center os not center anymore. 
I'll investigate more!

**Comment by Rmano** [comment]
Nicely seen. Yes, the workaround is relatively simple, I think; can you try the following?:

```latex
\documentclass[english,10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{babel}
% \usepackage{tikz}
\usepackage{circuitikz}

% new font parameter, start code
\usepackage{etoolbox}
\makeatletter
\ctikzset{tripoles/european port font/.initial={}}
%% patch the internal command to add the options
\patchcmd{\pgfcircdeclareeurologicport}%
    {\pgftext{#2}}%
    {\pgfscope
        \pgftransformresetnontranslations
        \pgftext{\ctikzvalof{tripoles/european port font}#2}%
    \endpgfscope}%
    {\relax}{\ERRORPACHING}
%% redeclare the ports
\pgfcircdeclareeurologicport{and}{\&}{\pgf@circ@res@count}{}
\pgfcircdeclareeurologicport{or}{$\ge 1$}{\pgf@circ@res@count}{}
\pgfcircdeclareeurologicport{xor}{$=1$}{\pgf@circ@res@count}{}
\pgfcircdeclareeurologicport{not}{$1$}{1}{not}
\pgfcircdeclareeurologicport{buffer}{$1$}{1}{}
\pgfcircdeclareeurologicport{nand}{\&}{\pgf@circ@res@count}{not}
\pgfcircdeclareeurologicport{nor}{$\ge 1$}{\pgf@circ@res@count}{not}
\pgfcircdeclareeurologicport{xnor}{$=1$}{\pgf@circ@res@count}{not}
\makeatother
% end font parameter code

\begin{document}
\begin{tikzpicture}[line width=1.5pt]%,font = \huge]
    \ctikzset{
        logic ports origin=center,
        logic ports/scale=2,
        tripoles/european not symbol=ieee circle,
        tripoles/thickness=1,
        bipoles/thickness=1,
    }

    % Draw the Nand with big AND symbol workaround
    \ctikzset{tripoles/european port font=\Huge}
    \draw(0,0) node [european nand port, rotate=180] (NAND1) {};
    \draw(0,-3) node [european nand port, rotate=90] (NAND2) {};
    \draw(3,-3) node [european nand port, xscale=-1] (NAND3) {};

\end{tikzpicture}
\end{document}
```

![image](https://github.com/circuitikz/circuitikz/assets/6414907/ae440e95-426e-4bf1-ba82-cf73807b645d)

That way, the text in the European port should always be "straight."  And, by the way,  the problem with the center position is an old one, solved by setting `logic ports origin=center`.

**Comment by Rmano** [comment]
Although maybe it would be also useful to define a couple of "blank" blocks, one negated and the other "straight", so that one can add the symbol/text/whatever in the box?

**Comment by sputeanus** [comment]
Yeah that would be nice if you would be able just to fill in your own symbol. Like witch the american ones.
![grafik](https://github.com/circuitikz/circuitikz/assets/117989161/18ba5a0e-1fc2-42fb-9be6-2796eb0b8a16)

**Comment by sputeanus** [comment]
But the workaround runs smootly :)
![grafik](https://github.com/circuitikz/circuitikz/assets/117989161/28b0d1ef-a3f5-4c03-88c5-09fb2e7f13c9)

**Comment by Rmano** [comment]
I think I'll add both. Let's see if somebody protest, but given that the change is aesthetic only, I feel I can do it.

**Comment by Rmano** [comment]
@sputeanus  notice that the name of the font parameter changed a bit. I hope you like the change... (notice that the workaround will stop working when `circuitikz` will update to 1.6.4).

**Comment by sputeanus** [comment]
Ah I see its plural now ;).

Alright looks nice, waiting for the Patch!

**Comment by Rmano** [comment]
Ok, merged now. It's still too early to release a version, but you can try it by downloading the "bleeding edge" version from https://circuitikz.github.io/circuitikz (when Travis decides to push the changes...)

**Comment by Rmano** [comment]
Ok, Travis started again, so now it's all synced.
