### ISSUE TITLE
[Feature] Additional Nodes for AC\DC DC\DC AC\DC converters

### ISSUE THREAD

**Issue by sputeanus** [circuitikz/circuitikz#769]
Hey ho, 

I am currently drawing a simple circuit with an AC/DC converter and I am not so happy with the distance of the DC Nodes.

![grafik](https://github.com/circuitikz/circuitikz/assets/117989161/a65b5d72-fc35-451a-9460-4a241e3d4bc8)

Intuitively I would place the DC- Node at 10-20% of the height and the DC+ Node at 80-90% of the height.

At the moment it is more like 25% and 75% or even 33% to 66%.
![grafik](https://github.com/circuitikz/circuitikz/assets/117989161/f9e5ee24-c19b-424c-abb3-10dddfa696ed)

Are there strong opinions about keeping the current values and if yes might it be possible to introduce a second set of nodes which are further out?

Warm regards
Simon

**Comment by sputeanus** [comment]
For example if you want draw a typical setup in the field of power electronics, which is a DC-Link, you get unpleasant results when the nodes are so far in the middle and you loose a lot of vertical space.

``
\begin{tikzpicture}

%% Standard Sizes
% Draw Converters
\draw (0,0)node[tacdcshape] (DC1){};
\draw (5,0)node[tacdcshape,xscale=-1] (DC2){};

% Draw DC Link Connections
\draw (DC1.dc up out) to [short] ++(2,0) coordinate (DC+) to (DC2.dc up out);
\draw (DC1.dc down out) to [short] ++(2,0) coordinate (DC-) to (DC2.dc down out);

% Draw Capacitor
\draw (DC+) to [C, v=$U_{DC}$] (DC-);


%% Increased sizes
% Draw Converters
\draw (0,-4)node[/tikz/circuitikz/bipoles/length=2.5cm,tacdcshape] (DC1){};
\draw (5,-4)node[/tikz/circuitikz/bipoles/length=2.5cm,tacdcshape,xscale=-1] (DC2){};

% Draw DC Link Connections
\draw (DC1.dc up out) to [short] ++(2,0) coordinate (DC+) to (DC2.dc up out);
\draw (DC1.dc down out) to [short] ++(2,0) coordinate (DC-) to (DC2.dc down out);

% Draw Capacitor
\draw (DC+) to [C, v=$U_{DC}$] (DC-);

\end{tikzpicture}
``

![grafik](https://github.com/circuitikz/circuitikz/assets/117989161/a3d87ee0-5b7c-4999-9831-e78b02459791)

(By the way, is there a better way to scale the converters?)

**Comment by Rmano** [comment]
Hmm... 

1. to scale blocks, you can use the class: `\ctikzset{blocks/scale=...}`, and that will apply to every block.
2. for the problem of the position of the anchors: yes, I see... what about if I add a parameter that let the user change the position of the generic `left up` etc. anchors? Now is 0.5 (midway center and border) but it seems easy to change that. 
3. I would write your last example as:

```latex
\documentclass[border=10pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{tikzpicture}

%% Standard Sizes
% Draw Converters
\draw (0,0)node[tacdcshape] (DC1){};
\draw (5,0)node[tacdcshape,xscale=-1] (DC2){};

% Draw DC Link Connections
\draw (DC1.right up) to [short] ++(2,0) coordinate (DC+) to (DC2.right up);
\draw (DC1.right down) to [short] ++(2,0) coordinate (DC-) to (DC2.right down);

% Draw Capacitor
\draw (DC+) to [C, v=$U_{DC}$] (DC-);


%% Increased sizes
\ctikzset{blocks/scale=2}
% Draw Converters
\draw (0,-4)node[tacdcshape] (DC1){};
\draw (5,-4)node[tacdcshape,xscale=-1] (DC2){};

% Draw DC Link Connections
\draw (DC1.dc up out) to [short] ++(2,0) coordinate (DC+) to (DC2.dc up out);
\draw (DC1.right down) to [short] ++(2,0) coordinate (DC-) to (DC2.right down);

% Draw Capacitor
\draw (DC+) to [C, v=$U_{DC}$] (DC-);

\end{tikzpicture}
\end{document}
```

![image](https://github.com/circuitikz/circuitikz/assets/6414907/69b4d897-24e7-4e42-ac37-b3c743989962)

Although I will not really invert the block, just use the corresponding inverse (but that's a matter of taste):

```latex
\documentclass[border=10pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{tikzpicture}

%% Increased sizes
\ctikzset{blocks/scale=2}
% Draw Converters
\draw (0,-4)node[tacdcshape] (DC1){};
\draw (5,-4)node[tdcacshape] (DC2){};

% Draw DC Link Connections
\draw (DC1.right up) to [short] ++(2,0) coordinate (DC+) to (DC2.left up);
\draw (DC1.right down) to [short] ++(2,0) coordinate (DC-) to (DC2.left down);

% Draw Capacitor
\draw (DC+) to [C, v=$U_{DC}$] (DC-);

\end{tikzpicture}
\end{document}
```

![image](https://github.com/circuitikz/circuitikz/assets/6414907/5791172f-fb68-4d29-89a1-601fe86a3137)

**Comment by Rmano** [comment]
@sputeanus  what do you think of the PR #770 ? I think it'll solve the problem.
