### ISSUE TITLE
Request : Thermogenerator

### ISSUE THREAD

**Issue by arbolis** [circuitikz/circuitikz#78]
I'd appreciate if someone could implement the thermoelectric generator symbol (can be found there : http://www.electronic-symbols.com/electric-electronic-symbols/heat-sources-symbols.htm) which looks like a box with a thermocouple and a G letter just above the thermocouple.
Thanks!

**Comment by alexpacini** [comment]
I include an image of the linked symbol for reference:
![](http://www.electrical-symbols.com/images/electrical-symbols/heat-generating-sources/thermoelectric-generator.png)

**Comment by Rmano** [comment]
This is a very specific symbol; maybe building it in a `tikz` `pic` would be more appropriate. Where are the terminals/leads?

**Comment by Rmano** [comment]
It seems that there is no more interested in this issue; I will close it. Please re-open if you deem it necessary.
