### ISSUE TITLE
[New Component] Request: Nixie Tubes

### ISSUE THREAD

**Issue by bogger33** [circuitikz/circuitikz#781]
**Show the component and its usage**

Nixie tubes appear to be missing from the circuitikz collection of tube diagrams. They are typically represented by one or sometimes two anodes (drawn the same as in other tube diagrams) and then a circle for each cathode representing a symbol/digit the nixie tube can display (anywhere from 1 - 12 typically). 

Here's a collage of different representations of nixie tubes I found online:

![nixiesymbols](https://github.com/circuitikz/circuitikz/assets/10445063/d5dfb331-c997-4ef9-97c9-7a938bf75a2a)

**Comment by Rmano** [comment]
Interesting. I have no time now (and it can be quite easily built with `tikz` if necessary), but I'll consider it as soon as I can.
