### ISSUE TITLE
The spacing of "dashed short" looks a little odd

### ISSUE THREAD

**Issue by EEpchi** [circuitikz/circuitikz#783]
**Background**: To use a different arrow style, I defined an arrow tip style of my own and use it with current anchors, such as:
```latex
\documentclass{article}
\usepackage{circuitikz}
\newcommand{\iarrow}[3]{\path[iarrow] (#1-Ifrom) -- (#1-Ipos) node[#2]{#3};}
\tikzstyle{iarrow}=[
	tips,arrows={-Triangle[width'=0pt 0.4, length=5pt]},shorten >=-3pt
]
\begin{document}
\begin{circuitikz}
	\scriptsize
	\draw(0,0) to[short,name=sht,i,current/distance=0.2] ++(2,0) node[right]{my own tips};
	\iarrow{sht}{above}{$ I $};
\end{circuitikz}
\end{document}
```
![image](https://github.com/circuitikz/circuitikz/assets/84228848/84f36c8a-696f-4fc9-9702-5b4eaf505002)

**Now** I need a dashed line with the current arrow, so I first tried `to[short]`, but I found the spacing looks a little odd, it seems like two pieces put together, the spacing between the shorts appears uneven. Then I found if I use `--` to draw the line, the spacing is good, but then I wouldn't be able to name the components to activate the current anchors and use my own arrow style.
```latex
\documentclass{article}
\usepackage{circuitikz}
\begin{document}
\begin{circuitikz}
	\scriptsize
	\draw[densely dashed] (0,0) to[short] ++(2,0) node[right]{dashed ``short"};
	\draw[densely dashed] (0,-0.5) -- ++(2,0) node[right]{dashed ``-\,-"};
\end{circuitikz}
\end{document}
```
![image](https://github.com/circuitikz/circuitikz/assets/84228848/bf90a202-452d-4869-9088-cb83f88d2126)

So why does the dashed `[short]` differ from the dashed `--` 🤔

**Comment by Rmano** [comment]
This happens because a `short` is really a bipole of size (almost) zero. So, using `to[short]` is the same as restarting the line midway. 
I don't think it's possible to fix it easily...

**Comment by EEpchi** [comment]
oh, I see. Here's my solution  currently:
```latex
\documentclass{article}
\usepackage{circuitikz}
\newcommand{\iarrow}[3]{\path[iarrow] (#1-Ifrom) -- (#1-Ipos) node[#2]{#3};}
\tikzstyle{iarrow}=[
	tips,arrows={-Triangle[width'=0pt 0.4, length=5pt]},shorten >=-3pt
]
\begin{document}
\begin{circuitikz}
	\scriptsize
	\draw[densely dashed] (0,-1) -- ++(2,0);
	\path[iarrow] (0,-1) -- ++(0.3,0) node[above]{$ I $};
\end{circuitikz}
\end{document}
```
![image](https://github.com/circuitikz/circuitikz/assets/84228848/818e168a-7f7a-4279-a0dd-e7c0a22c8edc)

Do you have any advice for me?🌹

**Comment by Rmano** [comment]
Yes, your solution is ok. It's basically what the `to[...]` is doing when positioning the current arrow.

**Comment by EEpchi** [comment]
> Yes, your solution is ok. It's basically what the `to[...]` is doing when positioning the current arrow.

OK, thank you very much🌹
