### ISSUE TITLE
[New Component] Request: VFD Tubes

### ISSUE THREAD

**Issue by bogger33** [circuitikz/circuitikz#785]
**Show the component and its usage**

Similarly to the #781 request for nixie tubes, VFD tubes are also absent from circuitikz. In its most simple form, a VFD tube is just a directly heated triode. However, they almost always have multiple anodes for the different segments. More complex tubes also have multiple grids, and different segments may share anodes to reduce the number of pins. Though it is unrealistic to cover every possible use case, it would be good to at least have a component for simple VFD tubes with one grid and multiple anodes, and more complex tubes can be split into multiple of these components in the diagram.

As with the nixie tube request, I have made a collage of representations of VFD tubes I have found:

![image](https://github.com/circuitikz/circuitikz/assets/10445063/518ebc76-bb54-4dda-877e-d7f0bfe9b578)

**Comment by Rmano** [comment]
Probably a possibility is a modification of the triode symbols to add more anodes...

![image](https://github.com/circuitikz/circuitikz/assets/6414907/22af186a-b922-41e4-bb71-d48835e9ab02)

**Comment by bogger33** [comment]
That would work, with either "filament,nocathode" or "fullcathode" it would achieve the desired effect

**Comment by Rmano** [comment]
I suppose a multi-anode tube could be used for both this one and Nixie, right? I think I have a bit of time this weekend, and I'll try to see if it is not too complex to implement.

**Comment by bogger33** [comment]
nixie tubes actually have multiple cathodes (and they are cold cathode, so do not have any filament), but they're structurally similar in that a variable number of cathodes exist for different types of nixie tubes

**Comment by Rmano** [comment]
Heads up: at this moment, I have the following.

![image](https://github.com/circuitikz/circuitikz/assets/6414907/a7cccf93-b88a-4de4-b7df-e0b8d55e5f89)

which can be used to draw this (from this issue):

![image](https://github.com/circuitikz/circuitikz/assets/6414907/678718f0-63db-4e9f-a34d-fe8608b9f43e)

and this (from the nixie #781):

![image](https://github.com/circuitikz/circuitikz/assets/6414907/368b6480-c662-48dd-b1ac-f49593d2e8a8)

at least, more or less... I think they can be used, right?

**Comment by bogger33** [comment]
it looks good! Would it be difficult to change the nixie version to have one central pin on the anode, rather than one on each side? other than that, it's perfect, thank you

**Comment by Rmano** [comment]
Yes, I have thought that. The only problem is that it will called "cathode"... but maybe that's not a big problem, I can create aliases... maybe "nixie cathode *n*" and "nixie anode".

**Comment by bogger33** [comment]
I see. I would be okay with aliases if it makes the code simpler for you. If the alias also changes the look of it to look like an anode, I suppose it's not too confusing anyway.

**Comment by Rmano** [comment]
So:

![image](https://github.com/circuitikz/circuitikz/assets/6414907/965d0566-f6d3-4ab4-af40-15b0f260ac81)

Do you think it's ok?

**Comment by bogger33** [comment]
yes, it looks perfect to me!

**Comment by Rmano** [comment]
Ok, I think I'll integrate it today. And the next week I'll release 1.6.8.

**Comment by Rmano** [comment]
Thank you for the comments!

**Comment by bogger33** [comment]
Thank you for implementing it!
