### ISSUE TITLE
[New Component] Differences between old and new instruments

### ISSUE THREAD

**Issue by mxxmxn** [circuitikz/circuitikz#787]
I have noticed that the old instruments (such as ammeter and voltmeter) behave differently from the new ones (such as rmeter and rmeterwa). For example, automatic rotation of the new instruments is better in most cases, but based on the manual I used the old instruments first. In general, better documentation would be helpful.

Is this behavior desirable for backward compatibility?
Ideally, the old instruments would be replaced by the corresponding new ones. If this is not possible, we could introduce abbreviations for the new instruments (as already exists with R for resistors).

**Comment by Rmano** [comment]
You guessed correctly. I have a strong backward compatibility policy: when you recompile a circuit with a new version of `circuitikz`, the electrical meaning of the circuit should not change (at least since version 0.6). 

But I can consider changing the order of the components in the manual ;-)

**Comment by mxxmxn** [comment]
How about if we disable automatic rotation by default and then replace the old meters with the new design? This would only change the look, but the behavior would remain the same. With appropriate documentation, I think this solution would be much more intuitive.

**Comment by Rmano** [comment]
Hmm. No, I prefer to leave the thing like they are. But I will reshuffle the manual to show  the new instruments before the legacy ones, and call explicitly them "legacy."

**Comment by mxxmxn** [comment]
Ok, I can understand that. But I still miss meters with the new behavior specific to volts, amps and ohms (as is the case with sources).  Would it be possible to introduce 3 new meters for this (e.g. `vmeter`, `ameter` and `rmeter`)? If so, I would create a corresponding pr.

**Comment by Rmano** [comment]
Not tested, but `\circuitikz{vmeter/.style={rmeterwa, t=v}}` should give you what you want...

**Comment by Rmano** [comment]
BTW, `rmeter` is already taken, so you can't use that...

**Comment by mxxmxn** [comment]
That works great.
Can you please add an example like the following to the documentation:
```
\documentclass[border=3mm]{standalone}

\usepackage{circuitikz}
    % define meters with new style
    \tikzset{vmeter/.style={rmeterwa, t=V}}
    \tikzset{ameter/.style={rmeterwa, t=A}}
    \tikzset{ometer/.style={rmeterwa, t=\(\Omega\)}}

\begin{document}
    \begin{tikzpicture}
        % Old meter style
        \draw (0,2) to[voltmeter] ++(2,0)
            to[ammeter] ++(2,0)
            to[ohmmeter] ++(2,0);
        % New meter style
        \draw (0,0) to[vmeter] ++(2,0)
            to[ameter] ++(2,0)
            to[ometer] ++(2,0);
    \end{tikzpicture}
\end{document}
```
