### ISSUE TITLE
[Feature] Filament center tap on tubes

### ISSUE THREAD

**Issue by bogger33** [circuitikz/circuitikz#792]
**Is your feature request related to a problem? Please describe.**
I wasn't sure whether to file this as a feature request or component request, but some tubes like e.g. the very popular 12AX7 (ECC83) have a center tapped filament, so it can be used with multiple different voltages (either in series or parallel). It would be useful to allow making a connection to the center point of the tube filament in circuitikz to allow for pinout descriptions as well as just more unambiguous circuit diagrams. (It's worth noting that the 12ax7 is a double triode so it might be represented by two triode symbols, but filament splits also exist on tubes which are just single pentodes, etc)

**Describe the solution you'd like**
An option for connecting to the center point of the filament. I apologize if this already exists and I missed it, but I could not find it in the manual.

**Additional context**

Center taps are usually represented in diagrams in one of two ways. 

Either as two filaments (i.e. two triangles/half-circles each representing one half of the filament):
![image](https://github.com/circuitikz/circuitikz/assets/10445063/2d2235e8-3b1f-44a7-a4a9-7efba957ce48)

Or just a tap in the center of one filament:
![image](https://github.com/circuitikz/circuitikz/assets/10445063/987497bd-9fec-4215-901b-dd6ff365ee00)

It seems to me that the former is more common, but neither is unusual in my estimation, and the latter would probably be simpler to add.

**Comment by Rmano** [comment]
Hi @bogger33  : what do you think of #798?

**Comment by bogger33** [comment]
it looks good to me!
