### ISSUE TITLE
[New Component] Neon Lamp

### ISSUE THREAD

**Issue by bogger33** [circuitikz/circuitikz#793]
**Show the component and its usage**

The neon lamp is still often used as an indicator on mains voltage circuits due to its high voltage drop, requiring only a resistor and otherwise no power supply. Due to its negative resistance property it can also be used as an active switching element, which was sometimes done in e.g. older CRT televisions.

The closest component in the circuitikz library right now appears to be the gas filled surge arrester (in particular the american variant has a similar symbol).

**Add references to standards, usage, etc.**
Once again I have prepared a collage of circuit symbols I could find for the neon bulb

![image](https://github.com/circuitikz/circuitikz/assets/10445063/d48f0c94-84ed-4d96-bf08-7134012dc8bd)

The most common appear to be the two variants at the top, in particular the one on the top left. 

I apologize for all these requests, this should be the last one for a while.

**Comment by Rmano** [comment]
😜 no need to apologize. These are quite easy symbols to add (the top right seems to be a solder jumper with a circle around it, and the top left is basically a circled capacitor). Which one do you think it's the best one to bet on?

**Comment by bogger33** [comment]
I looked around and it seems that the top left is the one that's used the most in modern documents at least at a cursory glance, although there unfortunately really doesn't seem to be any consensus. I also looked if I could find a standard regarding this, interestingly I did find that IEEE 315-1975 defines a the symbol on the bottom left. You can view it here:

https://www.iprocessmart.com/techsmart/elecsymbols.htm

It's on page 4, at the top right. It doesn't seem to be very commonly used, however, though I've seen it a few times. I think I personally would go with the top left, but I also would be happy with any other variation being added instead.

**Comment by Rmano** [comment]
What about these?

![image](https://github.com/circuitikz/circuitikz/assets/6414907/c8805c64-a49b-4005-89de-6728e3509d53)

**Comment by bogger33** [comment]
Those are nice! Actually seeing these side by side now also makes me think it might be useful to have both for dc and ac circuits respectively (where there either is or isn't a clear anode and cathode respectively). 

Maybe the names could be "double cathode style" and "cathode and anode style" rather than "capacitor" and "tube"?

**Comment by Rmano** [comment]
Yes, clearly, I can change the names. Maybe `neonlampcc` and `neonlampca`?

**Comment by bogger33** [comment]
makes sense to me
