### ISSUE TITLE
Transformer with center tap.

### ISSUE THREAD

**Issue by JetherReis** [circuitikz/circuitikz#80]
I realy would like to have transformes with center tap in Circuitikz, with the options: only on the primary, only on the secundary and in both.

**Comment by sistlind** [comment]
In my opinion, the transformer symbol is too unflexible for nearly all schematics, why you do not just draw the primary coil using two inductors?
A year ago i thought about adding new features to the transprmersymbol, but today i think in nearly all cases it is easier to build it from 2 single inductors...
