### ISSUE TITLE
[New Component(may be)]A different form for current probe

### ISSUE THREAD

**Issue by EEpchi** [circuitikz/circuitikz#807]
**Show the component and its usage**
It's just another form of current probe, I think it's widely used in my country.

Add an image of the new component and typical usage in a circuit.

![image](https://github.com/circuitikz/circuitikz/assets/84228848/80b87020-8234-4418-b478-dc0dc412d367)

**references**
Someone had already asked about this form of current probe in https://tex.stackexchange.com/questions/521103/tikz-diagram-for-current-sensor-measurement, and I have drawn a circuit with it using existing version of `circuitikz`. 
```latex
\documentclass[UTF-8,a4paper]{ctexart}
\usepackage{unicode-math}
\setmainfont{TeX Gyre Termes}
\setmathfont{TeX Gyre Termes Math}
\setsansfont{TeX Gyre Termes}
\usepackage[europeanresistors,americaninductors,americanvoltages,siunitx]{circuitikz}
\usetikzlibrary{shapes.geometric}
\begin{document}
\pagestyle{empty}
\ctikzset{tripoles/mos style/arrows, transistors/arrow pos=end}
\ctikzset{resistors/scale=0.6, capacitors/scale=0.6, inductors/scale=0.6, capacitors/height=0.4,capacitors/width=0.15,diodes/scal
\begin{circuitikz}[circuitikz/.cd,nodes width=0.025,bipoles/thickness=1.5,thyristor style=compact,diodes/scale=0.4,resistors/scale=0.4,transistors/scale=0.7,tripoles/thickness=1.5,muxdemuxes/thickness=1.5]
\tikzset{op/.style={muxdemux,muxdemux def={NL=2, Lh=4, NR=1, Rh=0, NB=0,NT=0,w=3.5}}}
	\small
	\draw (0,0) to[short,-*,i,name=s] ++(1.5,0) to[D-,mirror,l=$\mathrm{VD_1}$] ++(0,1) to[short,-*] ++(0.8,0) to[D-,invert,l=$\mathrm{VD_3}$] ++(0,-1) to[short,-*] ++(0,-0.8) to[D-,invert,-*,l=$\mathrm{VD_4}$] ++(0,-1) -- ++(-0.8,0) to[D-,mirror,l=$\mathrm{VD_2}$] ++(0,1) -- ++(0,0.8);
	\draw (0,0) to[open,o-o,v,font=\small,name=o] ++(0,-0.8) -- ++(2.3,0);
	\draw (o-Vfrom) ++(0,-0.05) node{\small $+$} (o-Vto) ++(0,-0.05) node{\small $-$} (o-Vlab) ++(0,-0.05) node{\small $u$};
	\draw (2.3,1) to[short,n=ss,i] ++(1.05,0) arc(180:0:0.15) -- (3.8,1) to[L,l=$L$,-*,label distance=-2pt] ++(1.5,0) to[Tnigfete,n=Q,invert,-*] ++(0,-2.8) -- ++(-3,0) (Q) node[right]{Q};
	\draw (5.3,1) to[D-] ++(1.5,0) to[C,l_=$C$,name=C,i,*-*] ++(0,-2.8) -- ++(-1.5,0);
	\draw (6.8,1) -- ++(1,0) to[R,l_=$R$,i,name=R,v^=$u_\mathrm{d}$,voltage shift=-0.9] ++(0,-2.8) -- ++(-1,0);
	\path[iarrow] (s-Ifrom) -- (s-Ipos) node[below]{$i$};
	\path[iarrow] (ss-Ifrom) -- (ss-Ipos) node[above]{$i_\mathrm{L}$};
	\path[iarrow] (R-Ifrom) -- (R-Ipos) node[left]{$i_\mathrm{R}$};
	\path[iarrow] (C-Ifrom |- R-Ifrom) -- (C-Ipos |- R-Ipos) node[left]{$i_\mathrm{C}$};
	\draw (1.5,-5) node(u){$\lvert u \rvert$} ++(2,0) node[draw](times){\scriptsize multiplier};
	\draw (C-Ipos |- u) node[circle,draw](c1){} ++(0,1) node(ud){$u_\mathrm{d}$} ++(1,-1) node(ur){$u_\text{ref}$} ($(c1)!0.5!(times.east)$) node[draw,minimum width=.5cm,minimum height=.5cm](PI1){\footnotesize PI};
	\draw ($(c1.north)!0.5!(c1.center)$) node{\tiny\bfseries --} ($(c1.east)!0.5!(c1.center)$) node{\tiny\bfseries +};
	\draw (times) ++(0,1) node[circle,draw](c2){} ($(c2.north)!0.5!(c2.center)$) node{\tiny\bfseries --} ($(c2.south)!0.5!(c2.center)$) node{\tiny\bfseries +};
	\draw (c2) ++(0,1) node[draw,align=center,font=\scriptsize,inner sep =2pt](i){Input current \\[-2pt] detection};
	\draw (3.5,1) node[circ,circuitikz/nodes width=0.05](node){} -- (i.north);
	\draw (Q.G) -- ++(0,-1.4) node[op,anchor=rpin 1,rotate=90,scale=0.35,draw only left pins={}](op){} (op.blpin 1) node[above=-2pt]{\footnotesize\bfseries +} (op.blpin 2) node[above=-2pt]{\rotatebox{-90}{\footnotesize\bfseries --}};;
	\draw (c2 -| op.blpin 1) node[draw,minimum width=.5cm,minimum height=.5cm](PI2){\footnotesize PI};
	\draw (op.blpin 2 |- i.south) node(uc){$ u_\mathrm{c} $};
	\foreach \i/\j in {u.east/times.west,
	times.north/c2.south,
	c2.east/PI2,
	i.south/c2.north,
	ur.west/c1.east,
	ud.south/c1.north,
	c1.west/PI1.east,
	PI1.west/times.east,
	PI2.north/op.blpin 1,
	uc.north/op.blpin 2}{
		\draw[farrow] (\i) -- (\j);}	
\end{circuitikz}
\end{document}
```
![image](https://github.com/circuitikz/circuitikz/assets/84228848/6f93e731-8ca7-4636-a920-ba49e2cc6fb9)

I think it's easier to draw if I can use existing components, so I'd be appreciated if  I can have it in this package🌹.

**Comment by Rmano** [comment]
This should be quite easy to add. In which country do you say it's used? It's a quite "non-electrical" symbol (unless the ground connection is implicitly assumed),  but I think I'll add it when I have a bit of time.

**Comment by Rmano** [comment]
For example, this would be ok? 

![image](https://github.com/circuitikz/circuitikz/assets/6414907/1a87ef49-6e20-44dd-9eae-6e81846f3f1c)


```latex
\documentclass[]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[siunitx, RPvoltages]{circuitikz}
\usepackage{ctikzmanutils}


\makeatletter
\ctikzset{bipoles/currtap/height/.initial=0.4}
\ctikzset{bipoles/currtap/dot size/.initial=0.5}
%% currtap
\pgfcircdeclarebipolescaled{instruments}
{
    \savedmacro{\@@dotsize}{\def\@@dotsize{\ctikzvalof{bipoles/currtap/dot size}}}
    \anchor{tap}{\northeast\pgf@x=0pt\pgf@y=\@@dotsize\pgf@y\pgf@y=-\pgf@y}
}
{\ctikzvalof{bipoles/currtap/height}}
{currtap}
{\ctikzvalof{bipoles/currtap/height}}
{\ctikzvalof{bipoles/currtap/height}}
{
    \pgfscope
        \pgfpathmoveto{\pgfpoint{\pgf@circ@res@left}{0pt}}
        \pgfpatharc{180}{0}{\pgf@circ@res@right}
        \pgf@circ@draworfill
    \endpgfscope
    \pgfpathcircle{\pgfpoint{0pt}{0pt}}{\@@dotsize*\pgf@circ@res@up}
    \pgfusepath{fill}
}
\pgfcirc@activate@bipole@simple{l}{currtap}
\makeatother

\begin{document}
\section{Dummy sec}
\subsection{Dummy subsec}
\subsubsection{Dummy subsubsec}

\begin{groupdesc}
    \circuitdescbip*{currtap}{Current tap (probe)}{}(tap/-90/0.2)
\end{groupdesc}

% \geolrcoord{currtapshape}

\begin{LTXexample}[varwidth=true, basicstyle=\small\ttfamily]
\begin{circuitikz}[european]
    \draw (0,0) to[currtap=I, *-*, name=ct] ++(3,0);
    \draw (ct.tap) -- ++(0,-1);
\end{circuitikz}
\end{LTXexample}

\end{document}

```

**Comment by EEpchi** [comment]
> For example

wow, that's very nice.

> In which country do you say it's used?

I'm in China. Our textbook has it:
![image](https://github.com/circuitikz/circuitikz/assets/84228848/99f96389-0c65-4658-aaec-0daeb67c9d86)
maybe they learned it from PSIM😂：

![image](https://github.com/circuitikz/circuitikz/assets/84228848/5f0df2f2-7a3d-4ad7-9749-2c1cdef0ef99)

And I think it would be perfect if I could freely change the size of the solid circle in the middle：

![image](https://github.com/circuitikz/circuitikz/assets/84228848/862070be-017f-4ba2-908e-280229a8af20)

Anyway, thank you for your efforts🌹

**Comment by Rmano** [comment]
> And I think it would be perfect if I could freely change the size of the solid circle in the middle：

You can: 

![image](https://github.com/circuitikz/circuitikz/assets/6414907/4a383b51-7577-460b-9f79-d03830d1e51e)

(It's a relative size). My doubt is if to make it fillable: 
![image](https://github.com/circuitikz/circuitikz/assets/6414907/e0ced23f-6199-4df8-a69e-96e67c684bc4)
Does it make any sense, and if it does, should it fill just the semicircle or a full circle around the inner dot?

**Comment by EEpchi** [comment]
> if to make it fillable

I don't think it makes much sense to me to fill in(or just I can't get it). But I think if it's for emphasis or whatever, it's okay to fill just the semicircle

**Comment by Rmano** [comment]
I am removing the fill option for now. PR in a few minutes...

**Comment by Dr4UX** [comment]
I've just stumbled across this component. Funnily enough, I designed exactly the same component two days ago and wanted to propose it in the next days.

I am used to this component with the circle in the middle only drawn and not filled. Maybe it would be an option to use the `fill`-option to fill the inner circle? Or add a `not filled` parameter to realise this?

**Comment by Rmano** [comment]
What about: 

![image](https://github.com/user-attachments/assets/d404c3f9-9368-4a53-a085-00e145e01320)

**Comment by Dr4UX** [comment]
looks perfect. Thank you!

**Comment by Rmano** [comment]
Going full-monty:

![image](https://github.com/user-attachments/assets/12b5fd8c-abba-40e9-a6d9-f3b543745f4c)
