### ISSUE TITLE
European Symbols not scalable

### ISSUE THREAD

**Issue by bkab** [circuitikz/circuitikz#81]
I noticed that european symbols for resistors and inductors (i have not tested the other ones) can not be scaled with pgfkeys (`\ctikzset{bipoles/resistor/height=.6}` for example).
Would be great, if this issue can be resolved.

**Comment by sistlind** [comment]
Have you tried \ctikzset{bipoles/generic/height=.6} ?

Am 02.07.2017 17:07 schrieb "bkab" <notifications@github.com>:

**Comment by bkab** [comment]
I tried it right away and indeed it is working with `\ctikzset{bipoles/generic/height=.6}` for resistors and `\ctikzset{bipoles/fullgeneric/height=.6}` for inductors respectively, thank you very much.

Nevertheless, in my opinion an adaption regarding the key ´\ctikzset{bipoles/resistor/height}´ would be usefull regarding consistency with US symbols.
