### ISSUE TITLE
[Bug] bad line joint at the thermocouple element

### ISSUE THREAD

**Issue by Dr4UX** [circuitikz/circuitikz#811]
I noticed that the connection of the `thermocouple` element is bad since the line caps are not lining up. You can see it in the picture below.

```latex
\documentclass{standalone}
\usepackage{circuitikz}

\begin{document}
\begin{tikzpicture}
    \draw (0,0) to [thermocouple] ++(1,0);
\end{tikzpicture}
\end{document}
```

![image](https://github.com/user-attachments/assets/0c66102f-0434-4446-96c3-aab6ec8391bb)

It gets better when you correct the left and right points of the component in its definition, but I have no idea, how you can adjust the joints for the thick part. 

```latex
\pgfcircdeclarebipolescaled{misc}
{}
{\ctikzvalof{bipoles/thermocouple/height 2}}
{thermocouple}
{\ctikzvalof{bipoles/thermocouple/height}}
{\ctikzvalof{bipoles/thermocouple/width}}
{
    \pgfpathmoveto{\pgfpoint{\pgf@circ@res@left-\pgfhorizontaltransformationadjustment*0.5*\pgflinewidth}{0}}
    \pgfpathlineto{\pgfpoint{\pgf@circ@res@left-\pgfhorizontaltransformationadjustment*0.5*\pgflinewidth}{.5\pgf@circ@res@down}}
    \pgfusepath{draw}
    \pgfpathmoveto{\pgfpoint{\pgf@circ@res@left-\pgfhorizontaltransformationadjustment*0.5*\pgflinewidth}{.5\pgf@circ@res@down}}
    \pgf@circ@setlinewidth{bipoles}{\pgfstartlinewidth}
    \pgfpathlineto{\pgfpoint{0}{\pgf@circ@res@down}}
    \pgfusepath{draw}
    \pgfsetlinewidth{\pgfstartlinewidth}
    \pgfpathmoveto{\pgfpoint{0}{\pgf@circ@res@down}}
    \pgfpathlineto{\pgfpoint{\pgf@circ@res@right+\pgfhorizontaltransformationadjustment*0.5*\pgflinewidth}{.5\pgf@circ@res@down}}
    \pgfpathlineto{\pgfpoint{\pgf@circ@res@right+\pgfhorizontaltransformationadjustment*0.5*\pgflinewidth}{0}}
    \pgfusepath{draw}
}
```

![image](https://github.com/user-attachments/assets/e84a5ec9-5f3f-4320-b156-ae75ef2660df)

**Edit**
I quickly scrolled through the manual and I think a lot of the switches and the `viscoe` component may have the same problem. Also you can see it for the zig-zag resistors when you change the `linewidth` as shown in the manual. (Probably every component that doesn't start/end with a horizontal line or a vertical line crossing the connection point? But that can get out of hands really fast I think.)

**Comment by Rmano** [comment]
Ouch! Yes, this is a problem when you stop a drawing and start a new one. In this case, I would draw the whole element in one go and then superpose the thick part. I'll try (and check the resistor too). As you say, a perfect solution is basically impossible unless the component starts with a horizontal line. You can probably make it less noticeable with `line cap=round` or something similar.

**Comment by Rmano** [comment]
Like:

```latex
\documentclass{standalone}
\usepackage{circuitikz}
\makeatletter
\pgfcircdeclarebipolescaled{misc}
{}
{\ctikzvalof{bipoles/thermocouple/height 2}}
{thermocouple}
{\ctikzvalof{bipoles/thermocouple/height}}
{\ctikzvalof{bipoles/thermocouple/width}}
{
    \pgfsetrectcap
    \pgfpathmoveto{\pgfpoint{\pgf@circ@res@left}{0}}
    \pgfpathlineto{\pgfpoint{\pgf@circ@res@left}{.5\pgf@circ@res@down}}
    \pgfpathlineto{\pgfpoint{0}{\pgf@circ@res@down}}
    \pgfpathlineto{\pgfpoint{\pgf@circ@res@right}{.5\pgf@circ@res@down}}
    \pgfpathlineto{\pgfpoint{\pgf@circ@res@right}{0}}
    \pgfusepath{draw}
    \pgf@circ@setlinewidth{bipoles}{\pgfstartlinewidth}
    \pgfsetroundcap
    \pgfpathmoveto{\pgfpoint{\pgf@circ@res@left}{.5\pgf@circ@res@down}}
    \pgfpathlineto{\pgfpoint{0}{\pgf@circ@res@down}}
    \pgfusepath{draw}
}
\makeatother
\begin{document}
\begin{tikzpicture}
    \draw (0,0) to [thermocouple] ++(1,0);
\end{tikzpicture}
\end{document}

```

![image](https://github.com/user-attachments/assets/e48a7c5e-9ad7-43f8-955e-77b797cb050d)

**Comment by Rmano** [comment]
BTW, I do not see any special problem with the resistor...

![image](https://github.com/user-attachments/assets/79f82a6d-b99a-4f46-8858-cb63c5accd67)

**Comment by Rmano** [comment]
Like, maybe, this:

![image](https://github.com/user-attachments/assets/af3f4725-f7b2-4982-873e-f2b4ff0cf468)

**Comment by Rmano** [comment]
We can continue the discussion in #814
