### ISSUE TITLE
Sinusoidal sources change

### ISSUE THREAD

**Issue by sputeanus** [circuitikz/circuitikz#818]
Hey there, 

I would like to draw the sinusoidal voltage sourches like this.

![grafik](https://github.com/user-attachments/assets/45a8bc00-9d2c-49e2-8d12-104da16b43c3)

However at the moment I can only draw them like this.

![grafik](https://github.com/user-attachments/assets/4f8b0f93-75fe-46ff-9137-96b370945731)

Can you introduce an additional symbol where the sinus symbol is flipped by 90°?

Warm regards
Simon

**Comment by Rmano** [comment]
This is already implemented, although I spotted a typo in the manual:

![image](https://github.com/user-attachments/assets/ad2c133e-b39e-4322-8774-75552515b28a)

The error is that the key is `sources/symbol`, **not** symbol**s**:

```latex
\documentclass[border=10pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage[siunitx, RPvoltages]{circuitikz}
% \ctikzset{sources/symbol/rotate=auto}
\begin{document}
\begin{tikzpicture}[]
    \draw (0,0) to[sV] ++(2,0);
\end{tikzpicture}
\end{document}
```

![image](https://github.com/user-attachments/assets/dc9503d3-ebce-4646-94a0-4b5b1d6dbfb0)

**Comment by sputeanus** [comment]
Hupps sorry I missed that!

**Comment by sputeanus** [comment]
But thanks as usual ;)

**Comment by Rmano** [comment]
You're welcome; I spotted a documentation bug, thanks to that!
