### ISSUE TITLE
[Bug] Open voltage arrow and label overlap

### ISSUE THREAD

**Issue by wallscheid** [circuitikz/circuitikz#821]
**Describe the bug**
The automatically generated voltage label of an open circuit voltage arrow can overlap with the arrow, see
![grafik](https://github.com/user-attachments/assets/8eb68a04-9a10-4c37-9eee-5a0469e65927)

**To Reproduce**
```latex
\documentclass{article}
\usepackage[european, smartlabels]{circuitikz}
\begin{document}
\begin{circuitikz}[]
            \draw (0,2) to [open, o-o, voltage = straight] ++(0,-2)
            to ++(-4,0)
            to [vsource, v<=$u_\mathrm{in}(t)$, i=$i_\mathrm{in}(t)$] ++(0,2)
            to [variable european resistor] ++(4,0) ;
            \draw (0,2) to [open, v = $ u_\mathrm{in}(t)$, voltage = straight] (0,0);
 \end{circuitikz}
\end{document}
```

**Operating system, LaTeX distribution**
Win 11 pro, MikTeX-pdfTeX 4.19

**Expected behavior**
Label is properly left or right aligned without overlapping - compare voltage source on the left hand side of the above screenshot, where the behavior works as expected

**Comment by Rmano** [comment]
Seen, I'll look at it as soon as I can --- on vacations now!

**Comment by Rmano** [comment]
I can confirm the bug, that can be reproduced with the minimal example:

```latex
\documentclass[]{article}
\usepackage{circuitikz}
\ctikzset{voltage=straight}
\begin{document}
    \begin{circuitikz}[]
        \draw (2,0) to [open, o-o, v = $ u_\mathrm{in}(t)$] ++(0,2);
    \end{circuitikz}
\end{document}
```

![image](https://github.com/user-attachments/assets/40b79f14-fa4c-4024-991b-1d6545a69fe2)

I'll look into it. As a workaround, you can use (adjusting the shift by tries)

```latex
\draw (2,0) to [open, o-o, v = $ u_\mathrm{in}(t)$, voltage shift=2] ++(0,2);
```
![image](https://github.com/user-attachments/assets/3832e72e-959f-4bcb-a40f-20cb7815e067)

**Comment by Rmano** [comment]
So, it seems that these lines:

https://github.com/circuitikz/circuitikz/blob/47c19c27bf7174eb80332c044df4a0c85ffadf3e/tex/pgfcircvoltage.tex#L194-L200

are the culprits for the bug, and removing them will fix it. The puzzling thing is that **I** added those lines, and I can't remember why.  I will give it some more regression checks before applying; in the meantime, you can use the live patch below.


```latex
\documentclass[]{article}
\usepackage[european, smartlabels]{circuitikz}
\usepackage{etoolbox}
\makeatletter
\patchcmd{\pgf@circ@drawvoltagegeneric}{%
        \ifpgf@circuit@bipole@voltage@straight
            \ifx\@@kind\@@open
                \def\pgf@circ@bipole@voltage@label@anchor{center}
                \pgfmathsetlength{\absvshift}{\absvshift+sign(\absvshift)*height{"Q"}} % with the current font.
            \fi
    \fi}{}{}{\typeout{Patching of void straight voltage failed}}
\makeatother
\begin{document}
\begin{circuitikz}[]
    \draw (0,2) to [open, o-o, voltage = straight] ++(0,-2)
    to ++(-4,0)
    to [vsource, v<=$u_\mathrm{in}(t)$, i=$i_\mathrm{in}(t)$] ++(0,2)
    to [variable european resistor] ++(4,0) ;
    \draw (0,2) to [open, v = $ u_\mathrm{in}(t)$, voltage = straight, voltage shift=2] (0,0);
\end{circuitikz}

\vspace{1cm}

\begin{circuitikz}[]
    \ctikzset{voltage=straight}
    \draw (0,0) to [open, o-o, v = $ u_\mathrm{in}(t)$] ++(0,2)
        to [open, o-o, v = $ u_\mathrm{in}(t)$] ++(2,0);
    \ctikzset{voltage=raised}
    \draw (3,0) to [open, o-o, v = $ u_\mathrm{in}(t)$] ++(0,2)
        to [open, o-o, v = $ u_\mathrm{in}(t)$] ++(2,0);
    \ctikzset{voltage=american}
    \draw (6,0) to [open, o-o, v = $ u_\mathrm{in}(t)$] ++(0,2)
        to [open, o-o, v = $ u_\mathrm{in}(t)$] ++(2,0);
    \ctikzset{voltage=european}
    \draw (9,0) to [open, o-o, v = $ u_\mathrm{in}(t)$] ++(0,2)
        to [open, o-o, v = $ u_\mathrm{in}(t)$] ++(2,0);
\end{circuitikz}
\end{document}
```

![image](https://github.com/user-attachments/assets/f15a4c2c-2b5d-4a90-96d3-491bbff671d6)
