### ISSUE TITLE
mov element not working

### ISSUE THREAD

**Issue by hebersarmiento** [circuitikz/circuitikz#824]
I cannot draw a mov element. I keep getting error I do not know the key '/tikz/mov. Is anyone having the same issue?  Thank you for your help

\documentclass{article}
\usepackage{circuitikz}
\begin{document}

Circuitikz: \pgfcircversion{} (\pgfcircversiondate)\par
Ti\emph{k}Z: \pgfversion{} (\pgfversiondate)\par\bigskip

\begin{tikzpicture}
    \draw(4,0) to[mov] ++(0,-2);
\end{tikzpicture}
\end{document}

I am on a fedora linux using texstudio, texlive. 

![image](https://github.com/user-attachments/assets/2b1cf40d-95ad-49fa-a866-76dffc11ba29)

**Comment by Rmano** [comment]
I have this with your code: 

![image](https://github.com/user-attachments/assets/f8dbbc06-3427-4985-9ccd-c220bcea636b)

Which is your version of circuitikz? Remove the tikzpicture, compile and report the two lines printed. If you have a too old version (probable), you can look here: https://tex.stackexchange.com/a/524329/38080

**Comment by hebersarmiento** [comment]
You are correct. I ran on overleaf and it works. My version is not the newest one and I will work on upgrading it.  Thank you so much for the quick reply

**Comment by Rmano** [comment]
No problem! Have a nice day!
