### ISSUE TITLE
[Bug] Voltage Directions Battery

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#825]
<img width="780" alt="image" src="https://github.com/user-attachments/assets/1ef736ae-e002-4c55-9772-c211861fedd0">

Looking in the manual, should the volatage arrow of the battery also not be inverted like for diode and resistors? Seems that it it not influenced at all. 

And another question: 

<img width="478" alt="image" src="https://github.com/user-attachments/assets/5eb66e16-219c-4827-b0e6-a8fc39ab8dee">

Why is the arrow much smaller compared to the other elements? This looks a bit weird :-)

**Comment by Rmano** [comment]
Do you mean the arrow in `EF` ? Maybe... that is a real mess of options there; with the hindsight of all these years of maintenance, what I think would be better is to forget voltage direction, draw everything in the direction of the bipole, and let the user adjust with `<` `>` or whatever. I think I'll not touch that code with a three-meter pole until I decide to go with `circuitikz-ng` and break backward compatibility (don't hold your breath; that is a retirement project, almost eight years to go...)

About the second question, I don't understand what you think is "smaller"... the arrow size can be configured (even styled, I think)...

**Comment by myzinsky** [comment]
Yeah you're right. I have almost 1000 pictures drawn with circuit tikz. If we change this basis, it will break a lot of pictures. I just stumbled over this. :-)

**Comment by Rmano** [comment]
Ok, I'll close as "can't-fix" ;-)
