### ISSUE TITLE
Circuitikz new current source symbol problem

### ISSUE THREAD

**Issue by superashtex** [circuitikz/circuitikz#83]
In the new version of the Circuitikz package, the American style current sources have an extra arrow on the connecting lines in addition to the arrow inside the shape (circle or diamond). The extra arrows are really not necessary because the arrow inside the current source shows the direction of the current.

The other major problem with this arrangement is that if the value of the current is a long expression (an equation for example), it will overlay the symbol. 

Please see the following figure. Any help to fix this problem would be highly appreciated.

![currents1](https://user-images.githubusercontent.com/30004778/27986972-97d9cd0e-63bb-11e7-82ce-9f31879dfff3.png)

**Comment by sistlind** [comment]
Just use l=..... instead of i=.... to name the component.

Am 08.07.2017 6:01 PM schrieb "superashtex" <notifications@github.com>:

**Comment by superashtex** [comment]
I did. No effect. Here is the line:

to[cI_=$z_{nm12}.y_{nm11}.i_{nm22}$]

Am I missing something?
Thanks

**Comment by sistlind** [comment]
Try to[cI_,l=$z_{nm12}.y_{nm11}.i_{nm22}$]



Am 08.07.2017 18:16 schrieb "superashtex" <notifications@github.com>:

**Comment by superashtex** [comment]
It changed the controlled source to independent source with the same format:

![currents2](https://user-images.githubusercontent.com/30004778/27987398-f115f036-63c1-11e7-9ccd-c6ec20e45500.png)

**Comment by sistlind** [comment]
Are you shure? Here it is working:
```
\documentclass{standalone}
\usepackage[american]{circuitikz}
\begin{document}
\begin{tikzpicture}
\draw (0,0) to[cI_=$z_{nm12}.y_{nm11}.i_{nm22}$] (0,2)to[cI,l_=$z_{nm12}.y_{nm11}.i_{nm22}$] (0,4);
\end{tikzpicture}
\end{document}
```
leads to:
![ci](https://user-images.githubusercontent.com/6959674/27987525-22378eb6-640f-11e7-8e09-6b84c6565738.png)

Can you provide a full MWE?

**Comment by superashtex** [comment]
It works. My mistake. I thought the letter before "=" in "cI_,l=" was "I". It is in fact little "L"! It became obvious when you posted the code.

Thanks a lot for your help.
