### ISSUE TITLE
[New Component] German TVS diode

### ISSUE THREAD

**Issue by myzinsky** [circuitikz/circuitikz#836]
![image](https://github.com/user-attachments/assets/e7dc8fec-bf65-43e9-8d4e-b38ede174e91)

![image](https://github.com/user-attachments/assets/7d118533-0ebf-4138-a7d2-a67ad492c07a)

German TVS diodes have different shapes. It would be nice if both could be implemented.

I tried it myself but diodes seem a bit complex in the code base ...

**Comment by Rmano** [comment]
What about a (global) option? So that the TVS diode switches between "45-degree whiskers" to "90-degree whiskers"?

**Comment by myzinsky** [comment]
Sounds reasonable

**Comment by Rmano** [comment]
@myzinsky, the single (one-way) TVS is really a Zener diode, correct?

**Comment by myzinsky** [comment]
They told me that would be the German TVS ^^

**Comment by myzinsky** [comment]
https://de.wikipedia.org/wiki/Suppressordiode

**Comment by Rmano** [comment]
They seem fast zener diodes. My doubt is whether to add a flag that changes the aspect of both ZZener and TVS or create new shapes. But I think I'll go for the flag...

**Comment by Rmano** [comment]
![image](https://github.com/user-attachments/assets/069fd0f4-6cd6-46c7-8d23-6d723240ceef)

@myzinsky what do you think
