### ISSUE TITLE
tripoles line thickness

### ISSUE THREAD

**Issue by ckuhlmann** [circuitikz/circuitikz#84]
Hi, would it be possible to introduce a key for the line thickness multiplier for tripoles, similar to the one that is used for bipole line thickness?
The fixed multiplier of 2 doesn't look very good when the bipole thickness is changed.
I suggest /tikz/circuitikz/tripoles/thickness

**Comment by ckuhlmann** [comment]
I've added a pull request that possibly implements the desired configurable width. However, these changes are **not** tested, so this still needs to be done.

**Comment by jason-s** [comment]
What version of tikz does this take effect in? I noticed this for the `schmitt` and `invschmitt` components.
