### ISSUE TITLE
Flip vamp upside down

### ISSUE THREAD

**Issue by senselessDev** [circuitikz/circuitikz#87]
Is it possible to flip all the "non-node" symbols for example upside down? I have no idea how to do it...

MWE: 
```
\documentclass{article}
\usepackage{tikz}
\usepackage[european,siunitx]{circuitikzgit}

\begin{document}

\begin{circuitikz}
  \draw
  (0,0) node[antenna, yscale=.5] (tx1) {}
  to ++(-1,0) to [vamp] ++(-2,0);
\end{circuitikz}

\end{document}
```

![vamp](https://user-images.githubusercontent.com/8526592/28249699-14da95c2-6a5b-11e7-9bd4-f6bb68c71213.png)

**Comment by sistlind** [comment]
Try [vamp,mirror]

Am 16.07.2017 19:15 schrieb "senselessDev" <notifications@github.com>:

**Comment by senselessDev** [comment]
Granted, stupid me. No I also found the documentation with mirror instead of flip..

But then another question popped up:

```
\documentclass{article}
\usepackage[european,siunitx]{circuitikzgit}

\begin{document}

\begin{circuitikz}
  \draw
  (0,0) node[antenna, yscale=.5] (tx1) {}
  to ++(-1,0) to [amp, t={\small VGA}] ++(-2,0)
  to [amp, invert, t={\small VGA}] ++(-2,0)
  to [amp, mirror, t={\small VGA}] ++(-2,0)
  to [amp, mirror, invert, t={\small VGA}] ++(-2,0);
\end{circuitikz}

\end{document}
```

![vga](https://user-images.githubusercontent.com/8526592/28249810-493f4ca2-6a5d-11e7-861a-a49fa3324fae.png)

Is it possible to get this right?

**Comment by sistlind** [comment]
You can put the text in a rotatebox or you have to place the text after
drawing the symbols.

Am 16.07.2017 19:31 schrieb "senselessDev" <notifications@github.com>:

**Comment by senselessDev** [comment]
Ok, so not directly via mirror-text or something like that. 
Thanks for your fast help!
