### ISSUE TITLE
xscale=-1 mirrors also label

### ISSUE THREAD

**Issue by der-stefan** [circuitikz/circuitikz#9]
When you mirror an element by xscale=-1, the labels are also mirrored.

Example:

``` latex
\begin{circuitikz} \draw
(0,0) node[npn,xscale=-1] (trans1) {T1}
(trans1.B) node[npn,anchor=B] (trans2) {T2}
;
\end{circuitikz}
```

![mirrored_label](https://f.cloud.github.com/assets/3618939/1429856/32fd4d26-40b9-11e3-82d6-d82318b9b3d6.png)

Note: If you place the label yourself by adding

``` latex
(trans1.text) node[] {T1}
```

it is not aligned correctly. (The anchor "text" is for the name of the node)

Furthermore, if you scale a device, the label also gets scaled. I am not sure if this behavior is wanted.
Example:

``` latex
\begin{circuitikz} \draw
(0,0) node[npn,xscale=-1] (trans1) {T1}
(trans1.B) node[npn,anchor=B,scale=2] (trans2) {T2}
;
\end{circuitikz}
```

![mirrored_label2](https://f.cloud.github.com/assets/3618939/1429954/928bc3c0-40ba-11e3-8658-28cd76b85697.png)

**edit:** This is no circuitikz specific bug (feature?), it's a thing of TikZ. So if you mirror something, place your labels as extra nodes.

**Comment by ivand58** [comment]
you can use scalebox -- `(0,0) node[npn,xscale=-1] (trans1){\scalebox{-1}[1]{$T1$}}`

**Comment by Rmano** [comment]
Notice that recent `circuitikz` has `\ctikzflipx{$T1$}` just for these cases. (Hey, this issue is 9 years old! 😉😉😉)
