### ISSUE TITLE
bug pgf-tikz with texlive 2017

### ISSUE THREAD

**Issue by herveb22** [circuitikz/circuitikz#90]
Hello,

when I compile the following code :[https://tex.stackexchange.com/questions/387336/bug-pgf-tikz-with-texlive-2017]( https://tex.stackexchange.com/questions/387336/bug-pgf-tikz-with-texlive-2017) I have a bug with the circuitikz ver. 0.83 but not with an older version (no issue with the ver. 0.6). I think there is a problem at the line "\pgf@y= \pgfkeysvalueof{/tikz/circuitikz/bipoles/length}".

Could you correct this bug ?

Thank you.

**Comment by sistlind** [comment]
Have a look at this commit: https://github.com/circuitikz/circuitikz/commit/061af7778e5f0833bb5a5f716cacacd5ed769468

Just use \pgf@circ@Rlen instead of \pgfkeysvalueof{/tikz/circuitikz/bipoles/length}

Best regards, Stefan
