### ISSUE TITLE
Circuit elements displayed incorrectly

### ISSUE THREAD

**Issue by hjmjohnson** [circuitikz/circuitikz#92]
The following code produces incorrect results:

=================
\documentclass[12pt]{article}
\pagestyle{plain}
\usepackage[american,siunitx]{circuitikz}

\begin{document}
TEST Failed rendering of circuit current and voltage sources: \\
	\begin{circuitikz}[scale=.25]
		\draw

		( 0, 0) to[R] (30,0)
		(30, 0) to[R] (30,15)
		(15,15) to[R,i_=$\SI{7}{\ampere}$] (30,15)
		(15,15) to[R,i<_=$I_1$] (15,30)
		(15,30) to[R] (0,30) -- (0,15)
		(0 ,15) to[R] (15,15)
		(15,30) to[short,i>_=$I_2$] (30,30)

		( 0, 15) to[I<=5A] (0,0)                              %FAILED CURRENT SOURCE ELEMENT RENDERING
		(30,15) to[V<=$\SI{6}{\volt}$] (30,30)   % FAILED VOLTAGE SORUCE ELEMENT RENDERING
		;
	\end{circuitikz}

\end{document}

===========================

<img width="814" alt="fail_circuit_pdf" src="https://user-images.githubusercontent.com/313970/30036419-cf09ba56-9178-11e7-95e7-e3e6fbaba76c.png">

SUCCESSFUL COMPILATION:
(/usr/local/texlive/2016/texmf-dist/tex/latex/circuitikz/circuitikz.sty
Package: circuitikz 2016/04/24{} The CircuiTikz circuit drawing package version
0.5

FAILED COMPILATION: 
(/usr/local/texlive/2017/texmf-dist/tex/latex/circuitikz/circuitikz.sty 
Package: circuitikz 2017/05/28{} The CircuiTikz circuit drawing package version 
 0.8.3

**Comment by hjmjohnson** [comment]
NOTE:  Issue #69 and commit ad8c384bcc9c1c4444c31bf43631f78e5ca3a187 change the backwards behavior of how circuits are drawn.

**Comment by hjmjohnson** [comment]
These two commits also break backward compatiblity with verison v0.5

commit 6a138ece477f2368bbdffb0617d2f2bdeca985ff (HEAD)
Author: Stefan Lindner <stefan.lindner@gmail.com>
Date:   Sat Apr 22 10:12:17 2017

    update documentation

commit 6524f2201368a3b2c7c570c39e7765a5b87b99fa (refs/bisect/bad)
Author: Stefan Lindner <stefan.lindner@gmail.com>
Date:   Sat Apr 22 09:16:15 2017

    current label now independent of regular label at current sources; code cleanup at current label drawing

**Comment by hjmjohnson** [comment]
Older documents compile with the new package, but give the wrong rendered results as compared to version 0.5

**Comment by sistlind** [comment]
This change was intended, because there was no rule in which direction voltages and currents are drawn. Therefore, it was some kind of trial and error at each symbol, which also changes, is the packet options were changed from european to american.

For the drawing direction you can use the package option "oldvoltagedirection", but there is no option for the labelplacement.

For compatibility reasons at older projects, you can use the released git-versions from here: https://circuitikz.github.io/circuitikz/
