### ISSUE TITLE
Changed scaling option gives compatibility problems

### ISSUE THREAD

**Issue by tcpluess** [circuitikz/circuitikz#93]
I have several old schematics drawn with Circuitikz, and unfortunately, these look ugly since the scaling option has changed. Previously, the bipoles/length scaling option did not scale transistors. Now, the option also scales transistors, which I don't want. Compare the two attached files. The transistor becomes incredibly small with the new scaling option. How can the old behaviour be restored?

Previous:
![a](https://user-images.githubusercontent.com/16662475/31055002-219ff668-a6be-11e7-9265-127773dec60e.png)

With the new scaling option:
![b](https://user-images.githubusercontent.com/16662475/31055003-21a1d9ce-a6be-11e7-806f-06e4a6a932dd.png)

**Comment by sistlind** [comment]
If i remeber correctly, the missing scaling at the transistors was a bug. Therefore, this will not reverted.
For older projects, try to use the older released git-versions from here:
https://circuitikz.github.io/circuitikz/

Just copy the correct one to your project folder and replace \usepackage{circuitikz} by \usepackage{circuitikzgit}
