### ISSUE TITLE
doc/LICENSE is missing

### ISSUE THREAD

**Issue by jonasstein** [circuitikz/circuitikz#94]
https://github.com/circuitikz/circuitikz/blob/master/tex/circuitikz.sty#L8

> % See the file doc/LICENSE for more details.

But there is no `doc/LICENSE`
The license text for GPL (which version?) and 
LaTeX Project Public License (which version? 1.3c?) is missing too.

From perspective of a packager, who is interested in distributing your software, I would strongly prefer two separate files like `gpl2_license.txt` and `latexppl_license.txt` in the top directory

**Comment by mredaelli** [comment]
Thanks for noticing! I made some changes in the last commits: feel free to close if you feel it's solved.

**Comment by jonasstein** [comment]
perfect, thank you.
