### ISSUE TITLE
Issues with switches

### ISSUE THREAD

**Issue by thejoker2** [circuitikz/circuitikz#95]
Hello,

I have issues with switches.
I cannot draw a normal switch without any arrow on it.

And the codes in the documentation don't give the expected symbols.

"**spst**" gives: 
![image](https://user-images.githubusercontent.com/24369435/32284904-02bf6e62-bf29-11e7-8d88-8f7e220e59f3.png)

"**ospst**" gives: 
![image](https://user-images.githubusercontent.com/24369435/32284987-47f82276-bf29-11e7-89ec-7391b9e5c921.png)

"**cspst**" gives: 
![image](https://user-images.githubusercontent.com/24369435/32285024-60dd83da-bf29-11e7-8f5f-84e7b1f38e73.png)

with is not what is expected.
And there is no way to get a "normal" switch without any arrow.

Thanks for your help!

**Comment by thejoker2** [comment]
I am the only one the face this issue?

**Comment by thejoker2** [comment]
Any help please?

**Comment by thejoker2** [comment]
:( .....

**Comment by Rmano** [comment]
I sympathize... but adding an element to circuitikz is not easy. You can do it with pure tikz, like 

```
 \draw (0,0) -- ++(0.2,0) 
        node (temp) [draw, inner sep=1pt, circle, fill=white]{} 
        ++(0.6,0) node [draw,inner sep=1pt, circle, fill=white]{} 
        -- ++(0.2,0);
    \draw [thick] (temp) -- ++(0.6, 0.3);
```


![selection_051](https://user-images.githubusercontent.com/6414907/32798898-6121ae00-c976-11e7-89d0-6dae676217b7.png)

(maybe in a macro, or in a `pic` environment).

**Comment by thejoker2** [comment]
Thank you for your answer. :)

But what does the code in the Circuitikz documentation not give the expected results about switches?

I am the only one facing this issue?

**Comment by sistlind** [comment]
Sorry for the late response :/
Please have a look at http://circuitikz.github.io/circuitikz/circuitikzmanualgit.pdf on page 19. There you find a few differen switching shapes. perhaps you are searching for the node "nos"?

**Comment by thejoker2** [comment]
I tried:
`\draw (v1) to [nos] (3,2.1) to [R,l_=$\frac{R}{2}$,i=$i_2$] (v2);`
But I got this error:

> ! Package pgfkeys Error: I do not know the key '/tikz/nos' and I am going to ig
nore it. Perhaps you misspelled it.
See the pgfkeys package documentation for explanation.

**Comment by sistlind** [comment]
Your code works here, please update your tex installation
