### ISSUE TITLE
No galvanometer or the ability to rotate components

### ISSUE THREAD

**Issue by musama95** [circuitikz/circuitikz#96]
Why is there no component as basic as a galvanometer? I can't seem to easily rotate any of the components either.

**Comment by musama95** [comment]
It's been about a month with no response from anyone.

**Comment by sistlind** [comment]
I think there is no galvanometer, because nobody created some yet. Just code it, i will include it.

Please have a look at the manual, there are the keys mirror/invert which can be used to rotate components.

**Comment by musama95** [comment]
Could you quote the place in the manual? I read almost all of it but I can't seem to find the inversion code. It would be really helpful! As for the galvanometer, I could make one on Illustrator, but making it in code would be impossible for me.

**Comment by sistlind** [comment]
http://circuitikz.github.io/circuitikz/circuitikzmanualgit.pdf page 43
