### ISSUE TITLE
Conflicting with IEC 60417 symbols

### ISSUE THREAD

**Issue by Dxhs** [circuitikz/circuitikz#97]
Why isn't the ground symbols designed according to IEC 60417 ground symbols?

**Comment by sistlind** [comment]
Could you provide a picture? I will add the symbol

**Comment by Rmano** [comment]
https://www.iso.org/obp/ui#iec:grs:60417:5017 
;-)

**Comment by sistlind** [comment]
Thia one ahould be included, pla have a look at the manual. Afaik it is
called rground

Romano Giannetti <notifications@github.com> schrieb am Di., 27. Feb. 2018,
19:31:

**Comment by Dxhs** [comment]
Not a problem in itself, but a noticeable detail.
![iec60417](https://user-images.githubusercontent.com/13475068/36761325-cb6394ae-1c1e-11e8-8e07-86b099d3e529.png)

References: 
https://www.iso.org/obp/ui#iso:pub:PUB400008:en
CircuiTikz manual (2016)

**Comment by Dxhs** [comment]
Geometry at the bottom: https://incompliancemag.com/article/the-grounding-symbols/

**Comment by sistlind** [comment]
Sorry for the delay, the new symbols are now available at the git version. The line thickness of the symbols and the connection can be adjusted indiviually using:
`\ctikzset{monopoles/ground/connectionthickness/.initial=1}`
`\ctikzset{monopoles/ground/thickness/.initial=2}`
