### ISSUE TITLE
Trivial Question

### ISSUE THREAD

**Issue by circuitikzuser** [circuitikz/circuitikz#98]
I am an old hand at LaTeX, but new to circuitikz. I read the very well written manual, and find  circuitikz to be one of the most useful packages for LaTeX.

Question 1
--------------
I have unfortunately a trivial issue I cannot resolve. Upon creating the headers as far as I could figure correctly from other examples, and then running the code as in the examples in the manual, I get a problem with the interpretation of component properties.

e.g.  the built in units are not interpreted by  circuitikz package.
I am breaking my head about this simple issue, but I cannot find the reason for this in the manual or online or in the archives.  I just cannot figure what is missing and why units are not  compiled.

See below from the compiler output.
Only if I convert the code to  the /SI option then the circuit is displayed with value and units.
So why doesnt it display the examples as presented correctly ?
Must be something in the headers I miss.

Error Output.

! Undefined control sequence.
\milli ->\ERROR 
                
l.77 ...2) -- (0,3) to[L, l=2<\milli\henry>] (5,3)
                                                   -- (5,2)
! Undefined control sequence.
\henry ->\ERROR 

Code that creates error output
 \begin{circuitikz}[scale=1.2]\draw
  (0,0) node[ground] {}
       to[V=$e(t)$, *-*] (0,2) to[C=4<\nano\farad>] (2,2)
       to[R, l_=.25<\kilo\ohm>, *-*] (2,0)
  (2,2) to[R=1<\kilo\ohm>] (4,2)
       to[C, l_=2<\nano\farad>, *-*] (4,0)
  (5,0) to[I, i_=$a(t)$, -*] (5,2) -- (4,2)
  (0,0) -- (5,0)
  (0,2) -- (0,3) to[L, l=2<\milli\henry>] (5,3) -- (5,2)
 {[anchor=south east] (0,2) node {1} (2,2) node {2} (4,2) node {3}}
;\end{circuitikz}

Question 2
--------------
Nowhere in the manual can I find that an opto FET symbol is included. Fine, there are many versions of fets and therefore many versions of opto FETs, but at least then an arrow symbol should be available, which I cannot locate either.
Thanks

**Comment by sistlind** [comment]
Regarding Question 1: Sorry, i am not familiar with SIunits.
Question 2: You are right, there is no such symbol. Maybe node[nigfete,nogate] helps you?

**Comment by Rmano** [comment]
I will try to have a look at the SIunits thing, although I normally use `\SI{}{}` which works everywhere and has no problem. 
Can you give an example of opto-fet?

**Comment by Rmano** [comment]
@circuitikzuser , your code works ok with the current git version of `circuitikz`: 

![image](https://user-images.githubusercontent.com/6414907/50045211-10947980-008f-11e9-99a2-0d41a5097d22.png)

**Comment by Rmano** [comment]
For the OptoFET, you have plenty of arrows in `arrows.meta` library of Tikz. For example:

```latex
\usetikzlibrary{arrows.meta}
\ctikzset{tripoles/mos style/arrows,}
\begin{circuitikz}[ 
    ]
    \draw (0,0) node[nmos,nogate](M1){};
    \draw[thin, -Latex] (M1.G) ++(-0.3,0.4) -- ++(0.6,-0.5);
    \draw[thin, -Latex] (M1.G) ++(-0.3,0.6) -- ++(0.6,-0.5);
\end{circuitikz}
```
results in 

![image](https://user-images.githubusercontent.com/6414907/50045295-92d16d80-0090-11e9-9ba5-12c7eb2eec36.png)

**Comment by Rmano** [comment]
I think I can close this issue. If you think it's not solved, feel free to re-open it.
